### ISSUE TITLE
sIpopt: dead support email address in Readme.txt

### ISSUE THREAD

**Issue by alexander-reiter-jku** [coin-or/Ipopt#19]
In the [sIpopt readme](https://github.com/coin-or/Ipopt/blob/master/Ipopt/contrib/sIPOPT/readme.txt) Hans Pirnay's email address is given as a support address. However, this email appears to be dead. Yesterday I received an error:

> The message that you sent was undeliverable to the following: 
> 	hans.pirnay@avt.rwth-aachen.de (550 #5.1.0 Address rejected.)

**Comment by sschnug** [comment]
Maybe try the mentioned alternative (mailing-list).

According to [this](https://de.linkedin.com/in/hans-pirnay-303ab261) and [this](http://www.avt.rwth-aachen.de/cms/AVT/Die-AVT/Team/Alumni/~jxap/Systemverfahrenstechnik/), he left RWTH Aachen.

**Comment by svigerske** [comment]
Removed the e-mail adress from the readme.
