### ISSUE TITLE
HSL MA27 issue Mac OS X

### ISSUE THREAD

**Issue by momovelo** [coin-or/Ipopt#20]
Hi,
By following the instructions: I've downloaded the HSL subroutines, compile it separately ("make check": success), re-unpack the archive, then move and rename the resulting directory so that it becomes `$IPOPTDIR/ThirdParty/HSL/coinhsl.` OK
But now i've an error message when i build Ipopt:

> checking whether finite is declared... yes
checking whether va_copy is declared... yes
checking whether -lblas has BLAS... yes
checking whether LAPACK is already available with BLAS library... no
checking whether -llapack has LAPACK... yes
configure: Checking for Harwell subroutine library
checking for ../.././Ipopt/../ThirdParty/HSL/ma27ad.f... no
checking for ../.././Ipopt/../ThirdParty/HSL/mc19ad.f... no
checking for ../.././Ipopt/../ThirdParty/HSL/ma57ad.f... no
configure: error: "No linear solver (such as MA27) available.  You need to provide at least one."
configure: error: /bin/sh '../.././Ipopt/configure' failed for Ipopt

Thanks for your help!

**Comment by svigerske** [comment]
You should not have to build HSL before. Which Ipopt version is this?

**Comment by svigerske** [comment]
This seems to be a very old version of the Ipopt code. Try 3.12.

**Comment by JMartinon** [comment]
Thanks for your reactivity. I use the last one, 3.2.1

**Comment by svigerske** [comment]
The current release is 3.12.9.
