### ISSUE TITLE
Aborted complilation

### ISSUE THREAD

**Issue by virpatel524** [coin-or/Ipopt#23]
Hi, 

I've been having a really hard time trying to install Ipopt, both the latest version as well as some that are older. I've tried installing some of the Third Party linear solvers, but notably the HSL and MUMPS seem to fail each time. I've tried running it without any of the Third Party solvers, but it still seems to fail. 

Attached are my ./configure output and the corresponding make file outputs (detailing where it crashed). My machine is an academic server that is fairly up to date, so I'm not sure what's going on here. Any suggestions would be much appreciated. 

[configuration.txt](https://github.com/coin-or/Ipopt/files/2106095/configuration.txt)
[make.txt](https://github.com/coin-or/Ipopt/files/2106096/make.txt)

**Comment by svigerske** [comment]
The error message from gfortran is not shown your make.txt.

**Comment by virpatel524** [comment]
My apologies! It's now included. 
[make_errorincluded.txt](https://github.com/coin-or/Ipopt/files/2106122/make_errorincluded.txt)

**Comment by svigerske** [comment]
It seems that your Fortran compiler is broken.
Try if you can compile some Fortran at all, e.g., `gfortran test.f && ./a.out` with test.f being
```
       PRINT *, "Hello World!"
       END
```

**Comment by virpatel524** [comment]
Hi Stefan,

Thanks for the advice. Unfortunately, it seems to be working fine. "Hello World!” printed just as it should have.

I also re-install the fortran compiler through the GCC 8.1 source code and it still didn’t seem to fix things.

Best,
Vir

**Comment by svigerske** [comment]
OK, but there is little I can do to fix a crash in your compiler.

config.log shows some strange flags that seem to be passed to configure
```
CPPFLAGS=-I/newhome/vdp5/bin/include/pcre.h' 'LDFLAGS=-L/home/vdp5/bin/include:/home/vdp5/bin/lib:/home/vdp5/source_code/boost_1.63.0
```
As your compiler already said, `/newhome/vdp5/bin/include/pcre.h` is not a directory, but a file.
Having an include directory with `-L` is strange, too. Also I don't think that one can specify several paths separated by a colon here, one would rather have an `-L` for each one.

**Comment by virpatel524** [comment]
Changing the -I flag fixed it perfectly. Thank you for your help!

Best,
Vir
