### ISSUE TITLE
unresolved external symbol _DPPSV

### ISSUE THREAD

**Issue by spyweik** [coin-or/Ipopt#26]
You might forgot add interface to FORTRAN routine DPPSV in IpOptFSS. When I compile ipopt 3.12.x use Visual Studio, I always failed with the error of unresolved external symbol _DPPSV which is not find in IpoptFSS.def, maybe you have not update the v8-ifort in sources.

**Comment by svigerske** [comment]
I added this in v8-ifort with r2746. I've no idea whether it is working, though.
