### ISSUE TITLE
Compilation of IPOPT on OS X El Capitan

### ISSUE THREAD

**Issue by svigerske** [coin-or/Ipopt#273]
Issue created by migration from Trac.

Original creator: abkum

Original creation time: 2016-05-15 00:17:03

Assignee: ipopt-team

Version: 3.12

I'm installing IPOPT for the first time and am having trouble with compilation on a Mac running OS X El Capitan. The configuration is successful, but when I run the make command, I get the error below. I'm not sure where to look for past queries or posts addressing this issue. Many thanks. 
```
Undefined symbols for architecture x86_64:
   "__intel_fast_memcpy", referenced from:
       _ma28part_ in libipopt.1.10.5.dylib-master.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make4b93956e64: *** [libipopt.la] Error 1
make6afa9fa918: *** [all-recursive] Error 1
make: *** [all-recursive] Error 1
```

(changed by @svigerske at 2016-05-15 17:34:26)

**Comment by svigerske** [comment]
Comment by @svigerske created at 2016-05-15 17:40:50

I would guess that linking of the ipopt library failed due to dependencies on some Intel Fortran runtime libraries.
A wild guess: Add `LDFLAGS=-lirc` to your configure flags.

One would need to know more information about used compilers, output of make, config.log files, etc. to give useful hints.

**Comment by svigerske** [comment]
Comment by @svigerske created at 2018-06-02 13:28:34

No response from reporter.

**Comment by svigerske** [comment]
Comment by @svigerske created at 2018-06-02 13:28:34

Resolution: worksforme

**Comment by timmyfaraday** [comment]
Hi, 

I run into the same issue on macOS Catalina v10.15.6. The `/configure` seems to run ok, but I get the following error when I run `make`.

```
Undefined symbols for architecture x86_64:
  "_mc68_default_control", referenced from:
      Ipopt::Ma86SolverInterface::InitializeStructure(int, int, int const*, int const*) in libipopt.1.10.10.dylib-master.o
      Ipopt::Ma77SolverInterface::InitializeStructure(int, int, int const*, int const*) in libipopt.1.10.10.dylib-master.o
  "_mc68_order", referenced from:
      Ipopt::Ma86SolverInterface::InitializeStructure(int, int, int const*, int const*) in libipopt.1.10.10.dylib-master.o
      Ipopt::Ma77SolverInterface::InitializeStructure(int, int, int const*, int const*) in libipopt.1.10.10.dylib-master.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libipopt.la] Error 1 
```

Attached you may find the config.log file 

[config.log](https://github.com/coin-or/Ipopt/files/5027518/config.log)

Thank you for your help.

Tom

**Comment by svigerske** [comment]
I see almost no similarity to the original issue.

HSL MA86 or HSL MA77 currently require MC68 to be present as well.
From the information given, I have no clue what has been made available in the HSL library, if any.
