### ISSUE TITLE
ipopt call order

### ISSUE THREAD

**Issue by svigerske** [coin-or/Ipopt#287]
Issue created by migration from Trac.

Original creator: alexho

Original creation time: 2017-09-01 09:32:34

Assignee: ipopt-team

Version: 3.12

Hi,

First thanks for your time. I'm using the matlab interface for ipopt and I have some objective function "objfun" that returns a set of function values and gradients [f,g] = objfun().

To fit this into the framework of ipopt I made two new function handles:

1) that runs the objective function (producing both function values and gradients) and outputs the gradient and saves the function values.

2) that loads the function values and outputs them.
 
I hence supply these two function handles to ipopt. From my point of view this may not be the most efficient way. 

My questions are; if I use this structure ipopt might not use linesearch, since the function values are loaded in, right? Also when I debug ipopt_auxdata.m it begins by calling the gradient function first, is this true? I would imagine it  begins by calling the objective function, but it does not seem to be the case.  In what order does ipopt do this then?

Thanks, Alexander.

**Comment by svigerske** [comment]
I don't think that there is a specific order one could rely on. It depends on the part of the algorithm that Ipopt is currently.

In most Ipopt interfaces, the eval callbacks get a flag to indicate whether some eval functions have been called for this x already. That is usually useful in situations where one evaluates all functions at once or reuses work from evaluation for computing derivatives. I'm not sure this `new_x` flag is also available in the Matlab interface.

The Matlab interface that came with Ipopt has been removed from Ipopt >= 3.13 - as it wasn't maintained. You may want to check at https://github.com/ebertolazzi/mexIPOPT on how to best use that Matlab interface nowadays.

**Comment by mottelet** [comment]
If you are interested, the Scilab interface to Ipopt implements at the C++ level the caching mechanism you are missing (and is maintained). For example you can make Ipopt calls like:

```
function [f,g] = fun(x,newx)
    xm1 = x-1;
    f = xm1*xm1;
    if argn(2) > 1
       g=2*xm1
    end
end

problem = struct();
problem.f = fun;
problem.x0 = 0;

x = ipopt(problem);
```
Not defining `problem.df` means that fun has to yield the gradient when required.

Scilab is available at http://www.scilab.org and Ipopt interface is installed by typing `atomsInstall sci_ipopt` on the command line.
