### ISSUE TITLE
Inaccurate calculation/reporting of infeasibility

### ISSUE THREAD

**Issue by svigerske** [coin-or/Ipopt#312]
Issue created by migration from Trac.

Original creator: nrontsis

Original creation time: 2018-11-15 18:52:20

Assignee: ipopt-team

Version: 3.12

Consider the following concave optimization problem that I attempt to solve with Ipopt:
```
max  x'x
s.t    Ax >= b
        -r =< x_i <= r
```
Sometimes Ipopt terminates claiming exactly zero constraint violation, i.e.
```
Constraint violation....:   0.0000000000000000e+00    0.0000000000000000e+00
```
but actually, the solution returned violates the constraints slightly (e.g. min(A*x - b) ~= -1e-7).

Here is a minimal example in MATLAB. System info: IPOPT version 3.12.9 called via mexIPOPT in MATLAB R2017b, macOS 10.13.6.
```
rng(1);
n = 24; m = 20;
A = randn(m, n);
b = randn(m, 1);
r = 10;

x_sol = call_ipopt(A, b, r, randn(n, 1));
fprintf("Returned solution's violation: %.5e\n", min(min(A*x_sol - b), 0))

function x = call_ipopt(A, b, r, x0)
  % Solves the convex maximization problem
  % max  x'x
  % s.t  Ax >= b
  %      -r <= x_i <= r
  % with Ipopt
  
  m = size(A, 1); n = size(A, 2);
  % Bound the variables to avoid the solution going to infinity
  options.lb = -r*ones(size(x0));
  options.ub = r*ones(size(x0));
  
  options.cl = b';   % Lower bounds on the constraint functions.
  options.cu = inf(size(b'));   % Upper bounds on the constraint functions.
  
  % Set the IPOPT options.
  options.ipopt.jac_d_constant   = 'yes';
  options.ipopt.hessian_constant = 'yes';
  
  % The callback functions.
  functions.objective         = `@`(x) -x'*x;
  functions.constraints       = `@`(x) A*x;
  functions.gradient          = `@`(x) -2*x;
  functions.jacobian          = `@`(x) sparse(A);
  functions.jacobianstructure = `@`() sparse(ones(m,n ));
  functions.hessian           = `@`(x, s, l) -s*speye(n);
  functions.hessianstructure  = `@`() speye(n);
  
  [x, ~] = ipopt(x0,functions,options);
end
```

**Comment by svigerske** [comment]
Comment by nrontsis created at 2018-11-15 18:55:14

Also, I observed the same issue when calling Ipopt via JuMP in Julia 1.0.1.

**Comment by nrontsis** [comment]
Just a follow up on this: setting `bound_relax_factor=0.0` seems to solve the problem.

May I suggest to perhaps

1. Change `IPOPT`'s logging output so as to print the actual constraint violation.
2. Change the documentation of `bound_relax_factor` to explicitly mention that a non-zero value could lead to (outside of the specified tolerances) constraint violation.

**Comment by svigerske** [comment]
Option [honor_original_bounds](https://coin-or.github.io/Ipopt/OPTIONS.html#OPT_honor_original_bounds) is probably relevant, too. That is the one responsible for not reporting to you the solution that had the zero-violation.

**Comment by svigerske** [comment]
With Ipopt 3.14, the new default is to not project the final solution onto the original bounds (`honor_original_bounds` is `no`). In addition, the bound relax has been changed to limit the absolute amount of relaxation by `constr_viol_tol`. Thus, variable bounds will be violated by no more than this tolerance (think of variable bounds as "bound _constraints_") eventually. Further, violation of original variable bounds is now reported in the log and SolveStatistics.
