### ISSUE TITLE
"Unresolved external symbol snprintf" when compiling with VS2015/ Ifort 2015?

### ISSUE THREAD

**Issue by nickvandewiele** [coin-or/Ipopt#315]
I am trying to compile Ipopt/MUMPS with 
- VS2015/ and 
- Intel ifort/MKL 2015 
- on a Win2012R2 x64 machine 
- through Cygwin, and MSVC++ compilers, 
- using Ipopt 3.12 from the svn repo
- Windows SDK 10

The (last) configure step of the Ipopt package showed the following error in the log:
```
configure:37890: checking for snprintf
configure:37955: cl -o conftest.exe -MT -O2 -nologo -wd4996 -D_CRT_SECURE_NO_DEPRECATE -DNDEBUG -DIPOPT_BUILD   conftest.c  >&5
conftest.c
conftest.obj : error LNK2001: unresolved external symbol snprintf
conftest.exe : fatal error LNK1120: 1 unresolved externals
cl : Command line warning D9035 : option 'o' has been deprecated and will be removed in a future release
configure:37961: $? = 2
configure: failed program was:
...
```

Although it did not crash during configure, the compilation step resulted in errors. S 

Sections in C files (e.g. [here](https://github.com/coin-or/Ipopt/blob/master/Ipopt/src/contrib/LinearSolverLoader/LibraryHandler.c#L18)) :
```
#ifdef HAVE_SNPRINTF
#define mysnprintf snprintf
#else
# ifdef HAVE__SNPRINTF
# define mysnprintf _snprintf
# else
#  define mysnprintf snprintf
#  error "Do not have function for save printing into a C-string (snprintf or _snprintf)"
# endif
#endif
```
that don't play nice with my VS2015 installation as the `snprintf` functions cannot be found, which was (silently) pointed out during the `configure`.

Has compilation of Ipopt 3.12 ever been tested with those specifics of VS/ifort?
What should my $LIB variable look like?

**Comment by tkralphs** [comment]
I have also seen this error when compiling Ipopt with VS and ifort at some point. I don't remember the details now, but I was able to get it to compile without needing to disable the linear solver loader. In case anyone else finds this issue later, I wanted to document that `--enable-doscompile=msvc` is deprecated. The argument has been changed to `--enable-msvc` and I also needed to explicitly specify `F77="ifort -fpp"` for a reason that I cannot remember now, but it might have had to do with this error.
