### ISSUE TITLE
Documentation of method intermediate_callback

### ISSUE THREAD

**Issue by michejansen** [coin-or/Ipopt#334]
Hello,

I think "ip_data" should be replaced by "ip_cq" in the part below of the documentation of the method intermediate_callback. The code does not compile without this change.

> Additionally, information about scaled violation of constraint 2 and violation of complementarity constraints can be obtained via
>   tnlp_adapter->ResortG(*ip_data->curr_c(), *ip_data->curr_d_minus_s(), ...)
>   tnlp_adapter->ResortBnds(*ip_data->curr_compl_x_L(), ...,
>                            *ip_data->curr_compl_x_U(), ...)
>   tnlp_adapter->ResortG(*ip_data->curr_compl_s_L(), ...)
>   tnlp_adapter->ResortG(*ip_data->curr_compl_s_U(), ...)

**Comment by svigerske** [comment]
I seem to be using `ip_data` just fine. Did you include `IpIpoptData.hpp` at the beginning?

**Comment by michejansen** [comment]
Hi, thanks for looking into this. Yes, `IpIpoptData.hpp` is included. Looking at this file the class `IpoptData` does not have these members (`curr_c,` `curr_d_minus_s`, etc.), while the class `IpoptCalculatedQuantities` does?

**Comment by svigerske** [comment]
Ah, I had looked at the wrong place, some lines before.
Thanks for staying persistent.
