### ISSUE TITLE
Installa Ipopt with Cygwin using the MSVC++ compiler

### ISSUE THREAD

**Issue by JackRen88** [coin-or/Ipopt#337]
Hello.
according to https://www.coin-or.org/Ipopt/documentation/node15.html#it:cyg_inst,running ./configure -enable-doscompile=msvc is successful,but running `make` to compile code,there is a problem that
`Making all in ThirdParty/Mumps
make[1]: 进入目录“/home/rcj/Ipopt-3.12.8/ThirdParty/Mumps”
/bin/sh ./../../libtool --tag=F77 --mode=compile ifort  -I. -I`cygpath -w .`  -I`cygpath -w ./MUMPS/src` -I`cygpath -w ./MUMPS/libseq` -I`cygpath -w ./MUMPS/include`   -Dmetis -c -o dmumps_comm_buffer.lo `test -f 'MUMPS/src/dmumps_comm_buffer.F' || echo './'`MUMPS/src/dmumps_comm_buffer.F
 ifort -I. -I. -IMUMPS\\src -IMUMPS\\libseq -IMUMPS\\include -Dmetis -c MUMPS\\src\\dmumps_comm_buffer.F -o dmumps_comm_buffer.obj
Intel(R) Visual Fortran Intel(R) 64 Compiler for applications running on Intel(R) 64, Version 19.0.3.203 Build 20190206
Copyright (C) 1985-2019 Intel Corporation.  All rights reserved.

ifort: NOTE: The evaluation period for this product ends on 11-may-2019 UTC.
MUMPS\src\dmumps_comm_buffer.F(1128): warning #5117: Bad # preprocessor line
#if ! defined(DBG_SMB3)
-^
MUMPS\src\dmumps_comm_buffer.F(1136): warning #5117: Bad # preprocessor line
#endif
-^
MUMPS\src\dmumps_comm_buffer.F(1840): warning #5117: Bad # preprocessor line
#if ! defined(DBG_SMB3)
-^
MUMPS\src\dmumps_comm_buffer.F(1849): warning #5117: Bad # preprocessor line
#endif
-^
MUMPS\src\dmumps_comm_buffer.F(2236): warning #5117: Bad # preprocessor line
#if ! defined(OLD_LOAD_MECHANISM)
-^
MUMPS\src\dmumps_comm_buffer.F(2238): warning #5117: Bad # preprocessor line
#endif
-^
MUMPS\src\dmumps_comm_buffer.F(2242): warning #5117: Bad # preprocessor line
#if ! defined(OLD_LOAD_MECHANISM)
-^
MUMPS\src\dmumps_comm_buffer.F(2244): warning #5117: Bad # preprocessor line
#endif
-^
MUMPS\src\dmumps_comm_buffer.F(2259): warning #5117: Bad # preprocessor line
#if ! defined(OLD_LOAD_MECHANISM)
-^
MUMPS\src\dmumps_comm_buffer.F(2266): warning #5117: Bad # preprocessor line
#endif
-^
MUMPS\src\dmumps_comm_buffer.F(2325): warning #5117: Bad # preprocessor line
#if ! defined(OLD_LOAD_MECHANISM)
-^
MUMPS\src\dmumps_comm_buffer.F(2327): warning #5117: Bad # preprocessor line
#else
-^
MUMPS\src\dmumps_comm_buffer.F(2329): warning #5117: Bad # preprocessor line
#endif
-^
MUMPS\src\dmumps_comm_buffer.F(2350): warning #5117: Bad # preprocessor line
#if ! defined(OLD_LOAD_MECHANISM)
-^
MUMPS\src\dmumps_comm_buffer.F(2352): warning #5117: Bad # preprocessor line
#endif
-^
MUMPS\src\dmumps_comm_buffer.F(2364): warning #5117: Bad # preprocessor line
#if ! defined(OLD_LOAD_MECHANISM)
-^
MUMPS\src\dmumps_comm_buffer.F(2366): warning #5117: Bad # preprocessor line
#endif
-^
MUMPS\src\dmumps_comm_buffer.F(2377): warning #5117: Bad # preprocessor line
#if ! defined(OLD_LOAD_MECHANISM)
-^
MUMPS\src\dmumps_comm_buffer.F(2384): warning #5117: Bad # preprocessor line
#endif
-^
MUMPS\src\dmumps_comm_buffer.F(2427): warning #5117: Bad # preprocessor line
#if ! defined(OLD_LOAD_MECHANISM)
-^
MUMPS\src\dmumps_comm_buffer.F(2429): warning #5117: Bad # preprocessor line
#else
-^
MUMPS\src\dmumps_comm_buffer.F(2431): warning #5117: Bad # preprocessor line
#endif
-^
MUMPS\src\dmumps_comm_buffer.F(2592): warning #5117: Bad # preprocessor line
#if ! defined(OLD_LOAD_MECHANISM)
-^
MUMPS\src\dmumps_comm_buffer.F(2594): warning #5117: Bad # preprocessor line
#endif
-^
MUMPS\src\dmumps_comm_buffer.F(2604): warning #5117: Bad # preprocessor line
#if ! defined(OLD_LOAD_MECHANISM)
-^
MUMPS\src\dmumps_comm_buffer.F(2606): warning #5117: Bad # preprocessor line
#endif
-^
MUMPS\src\dmumps_comm_buffer.F(2619): warning #5117: Bad # preprocessor line
#if ! defined(OLD_LOAD_MECHANISM)
-^
MUMPS\src\dmumps_comm_buffer.F(2626): warning #5117: Bad # preprocessor line
#else
-^
MUMPS\src\dmumps_comm_buffer.F(2628): warning #5117: Bad # preprocessor line
#endif
-^
MUMPS\src\dmumps_comm_buffer.F(2688): warning #5117: Bad # preprocessor line
#if ! defined(OLD_LOAD_MECHANISM)
-^
MUMPS\src\dmumps_comm_buffer.F(2690): warning #5117: Bad # preprocessor line
#else
-^
MUMPS\src\dmumps_comm_buffer.F(2692): warning #5117: Bad # preprocessor line
#endif
-^
MUMPS\src\dmumps_comm_buffer.F(2337): error #6099: An ENDDO statement occurred without a corresponding DO or DO WHILE statement.
        END DO
^
MUMPS\src\dmumps_comm_buffer.F(2326): error #6321: An unterminated block exists.
        IF ( I .NE. MYID .AND. FUTURE_NIV2(I+1) .NE. 0) THEN
^
MUMPS\src\dmumps_comm_buffer.F(2324): error #6321: An unterminated block exists.
        DO I = 0, NPROCS - 1
^
MUMPS\src\dmumps_comm_buffer.F(2439): error #6099: An ENDDO statement occurred without a corresponding DO or DO WHILE statement.
        END DO
^
MUMPS\src\dmumps_comm_buffer.F(2428): error #6321: An unterminated block exists.
          IF ( I .NE. MYID .AND. FUTURE_NIV2(I+1) .NE. 0) THEN
^
MUMPS\src\dmumps_comm_buffer.F(2426): error #6321: An unterminated block exists.
        DO I = 0, NPROCS - 1
^
MUMPS\src\dmumps_comm_buffer.F(2700): error #6099: An ENDDO statement occurred without a corresponding DO or DO WHILE statement.
        END DO
^
MUMPS\src\dmumps_comm_buffer.F(2689): error #6321: An unterminated block exists.
        IF ( I .NE. MYID .AND. FUTURE_NIV2(I+1) .NE. 0) THEN
^
MUMPS\src\dmumps_comm_buffer.F(2687): error #6321: An unterminated block exists.
        DO I = 0, NPROCS - 1
^
compilation aborted for MUMPS\src\dmumps_comm_buffer.F (code 1)
make[1]: *** [Makefile:479：dmumps_comm_buffer.lo] 错误 1
make[1]: 离开目录“/home/rcj/Ipopt-3.12.8/ThirdParty/Mumps”
make: *** [Makefile:323：all-recursive] 错误 1
`
How should I solved it ?

**Comment by svigerske** [comment]
Looks like ifort doesn't run the preprocessor.
Maybe try configure with `ADD_FFLAGS=-fpp`

**Comment by tkralphs** [comment]
I do remember needing to do what Stefan is suggesting at one point, but looking at `coin.m4`, that flag is supposed to get added automatically now in CYGWIN with `ifort`. I will try building it again on WIndows later today. It would be good to track down what's happening. 

The instructions in the manual do seems a little out of date. The option for building with `cl` and `ifort` has been renamed `--enable-msvc`. That shouldn't make any difference, though.

**Comment by JackRen88** [comment]
Hello.
@svigerske .According to your instruction,I run the `export ADD_FFLAGS=-fpp  ` and `./configure  --enable-msvc` in the CYGWIN's terminal，the last message is Main  configuration of Ipopt successful,but running the code `make`,there is a problem above.
According to the instruction that is https://projects.coin-or.org/BuildTools/wiki/current-issues,I edit the files ifort.cfg in the Intel compiler installation（I installed Intel® Parallel Studio XE 2019 for Windows ）add code as follows:
`-Qlocation，link，“C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\Hostx64\x64”`

environment variables PATH is set as :
`/usr/local/bin:/usr/bin:/cygdrive/c/Program Files (x86)/IntelSWTools/compilers_and_libraries_2019.3.203/windows/mpi/intel64/bin:/cygdrive/c/Program Files (x86)/Common Files/Intel/Shared Libraries/redist/intel64_win/mpirt:/cygdrive/c/Program Files (x86)/Common Files/Intel/Shared Libraries/redist/ia32_win/mpirt:/cygdrive/c/Program Files (x86)/Common Files/Intel/Shared Libraries/redist/intel64_win/compiler:/cygdrive/c/Program Files (x86)/Common Files/Intel/Shared Libraries/redist/ia32_win/compiler:/cygdrive/c/Windows/system32:/cygdrive/c/Windows:/cygdrive/c/Windows/System32/Wbem:/cygdrive/c/Windows/System32/WindowsPowerShell/v1.0:/cygdrive/c/Windows/System32/OpenSSH:/cygdrive/c/Program Files/MATLAB/R2011a/runtime/win64:/cygdrive/c/Program Files/MATLAB/R2011a/bin:/cygdrive/c/Program Files/Microsoft SQL Server/110/Tools/Binn:/cygdrive/c/Program Files/dotnet:/cygdrive/c/ProgramData/chocolatey/bin:/cygdrive/c/Program Files/Git/cmd:/cygdrive/c/Program Files/Mercurial:/cygdrive/c/Program Files/CMake/bin:/cygdrive/c/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64:/cygdrive/c/Program Files (x86)/IntelSWTools/compilers_and_libraries_2019.3.203/windows/bin/intel64:/cygdrive/c/Users/rcj/AppData/Local/Microsoft/WindowsApps`

@tkralphs Do you  try building it on windows? Is there some issues as I mentioned above?
My system configuration：
Windows 10
Microsoft Visual Studio 2017 （ MSVC++ compiler cl）
Intel® Parallel Studio XE 2019 (Intel Fortran compiler ifort)
Ipopt-3.12.8
Running configure scripts ./configure ,there is a configuration log file config.log.


Please help solve the compile problem on windows, I have compiled the Ipopt for five days !!

**Comment by JackRen88** [comment]
[Uploading config.log…]()

**Comment by tkralphs** [comment]
I just built with `ifort` in Msys on Windows and had no issues. It shouldn't be any different on CYGWIN, so the most likely origin for the problem would be an incorrect `build` platform, which could result in the wrong compiler flags being used. Could you post your `config.log` and `config.status` in a gist or just find what build platform is detected (grep `config.log` for `build=`) and what flags are used (grep `config.status` for `FLAGS`)?

**Comment by tkralphs** [comment]
By the way, if you are not specifically tied to CYGWIN, Msys2 is much better overall (at least as far as I'm concerned). It has a much smaller footprint, plays better with WIndows (paths, etc.), has a very nice package manager, produces executables that are completely portable and don't require the CYGWIN DLL (Of course, this can also be accomplished in CYGWIN by using the MinGW compilers).

**Comment by JackRen88** [comment]
[config.log](https://github.com/coin-or/Ipopt/files/3078134/config.log)

**Comment by JackRen88** [comment]
[ipopt_config.zip](https://github.com/coin-or/Ipopt/files/3078143/ipopt_config.zip)
Hello, @tkralphs .
Thank you very much for your patience.The above is the generated log file.Please help me with finding out where problem is.
Thanks!

**Comment by tkralphs** [comment]
I have a guess about what the problem is. I recall now coming up against it myself. What is basically happening is that the compilation of a test program with `ifort` that the `configure` script uses to determine if the compiler is working properly with the given flags seems to be failing. As a result, the `configure` script concludes that the flags you asked for are not working, so it falls back to a default set of flags. But these also do not work (because the preprocessor is not called). If you open `config.log` and search for "ifort", you will see what the failed programs look like. One of them is this:
``` 
       program main
       integer i
       end
```
Can you try compiling this simple program with `ifort` and see that the output is? The `configure` script is looking for `conftest.exe`, but I suspect that you are getting `conftest` (without any extension) because you are in CYGWIN. I don't remember the details anymore of this behavior, but I guess that this is the standard in CYGWIN (as in Linux), whereas in MSys and in Visual Studio, the output would be `conftest.exe`. 

I think your easiest path right now is to switch to MSys, which will work without problems. We don't really support CYGWIN much anymore, since it is tricky (problems like this arise) and generally not the best option on Windows these days. I can't guarantee we'll be able to find a fix that is easy to implement. But give compilation of the test program a try and let me know what the output is. Then we can go from there. I guess there should be a way to totally over-ride these checks and force the flags that work in the worst case.

Did you try `--enable-msvc`? I noticed the config.log you sent still was using `--enable-doscompile=msvc`.

**Comment by tkralphs** [comment]
Actually, thinking about this some more, it should work to do
```
./configure CC=cl CXX=cl F77=ifort
```
If you do _not_ add `--enable-doscompile` or `--enable-msvc`, `configure` should default to the Linux convention of no extensions for binaries when checking whether the compiler works and then I guess there should be no problem.

**Comment by JackRen88** [comment]
@tkralphs 
According to your instruction, running the code `make`,there is also a issue that
`compilation aborted for MUMPS\src\dmumps_comm_buffer.F (code 1)
make[1]: *** [Makefile:479：dmumps_comm_buffer.lo] 错误 1
make[1]: 离开目录“/home/rcj/Ipopt-3.12.8/ThirdParty/Mumps”
make: *** [Makefile:323：all-recursive] 错误 1
`
It’s really a headache

**Comment by JackRen88** [comment]
Hello， @tkralphs 
Now I install msys2(64 bits), can you tell me that how to  install Ipopt with MSys2 using the MSVC++ compiler，can you give me some instruction in detail?
Thanks!

**Comment by JackRen88** [comment]
Hello， @tkralphs 
According to your instruction,I have some inspiration。Now I use cl and ifort to compile the Ipopt in the Compiler 19.0 Update 3 for Intel 64 Visual Studio 2017 environment.
During running `make` to compile the code ,I get the error that
`LibraryHandler.c
LibraryHandler.c(25): fatal error C1189: #error:  "Do not have function for save printing into a C-string (snprintf or _snprintf)"`
Can you help me to solve  the issue?
Thanks!

**Comment by tkralphs** [comment]
I have also seen the error you report just [above](https://github.com/coin-or/Ipopt/issues/337#issuecomment-483944151) before. @svigerske can probably say better what to do about it. 

For building under Msys. There are general instructions under construction here using the `coinbrew` script, a general script for building COIN-OR projects with dependencies:
https://coin-or.github.io/user_introduction.html#windows-1
The important piece is to get the right packages installed in MSys:
```
bash
pacman -S make wget tar patch dos2unix diffutils git svn
```
After that, you should be able to build as you were in CYGWIN (if you don't want to use the `coinbrew` script).

**Comment by svigerske** [comment]
Sometimes, configure with MS compilers has problems detecting `snprintf` or `_snprintf`). In recent Ipopt versions, we just removed the `#error` line in LibraryHandler.c. If you really need to use the old 3.12.8 release, then try with just removing the problematic line in LibraryHandler.c.

**Comment by tkralphs** [comment]
Just to follow up in case someone finds this issue by searching this error, I discovered that it can also be caused by having the directories in your `PATH` listed in the wrong order. It's very important that the `link` executable that is found is the Windows one, not the Linux one. In other words, the path added by running `ifortvars.bat` must come before the directory `C:\msys64\usr\bin` in the Windows `PATH` variable. If you have this failure, so
```
which link
```
on the command line in Msys2 bash and if the result is
```
\usr\bin\link
```
then you need to reorder your `PATH`.  The result should be something like
```
/c/Program Files (x86)/Microsoft Visual Studio 14.0/VC/BIN/x86_amd64/link
```
