### ISSUE TITLE
[regression in 3.12.13] Shared libs lost version numbers

### ISSUE THREAD

**Issue by yurivict** [coin-or/Ipopt#340]
```
===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: lib/libcoinmetis.so.0
Error: Orphaned: lib/libcoinmetis.so.0.0.0
Error: Orphaned: lib/libcoinmumps.so.0
Error: Orphaned: lib/libcoinmumps.so.0.0.0
Error: Orphaned: lib/libipopt.so.0
Error: Orphaned: lib/libipopt.so.0.0.0
===> Checking for items in pkg-plist which are not in STAGEDIR
Error: Missing: lib/libcoinmetis.so.1
Error: Missing: lib/libcoinmetis.so.1.3.6
Error: Missing: lib/libcoinmumps.so.1
Error: Missing: lib/libcoinmumps.so.1.6.1
Error: Missing: lib/libipopt.so.1
Error: Missing: lib/libipopt.so.1.10.12
===> Error: Plist issues found.
```

configure is now printing these warnings:
```
checking if library version is set... no
```

**Comment by svigerske** [comment]
Yeah, I can reproduce this. There must have been some glitch when the release was produced. The base directory configure doesn't have the libversion set, but the one in the project directory (Ipopt/configure) does.
Will check closely when the next release is produced.

**Comment by yurivict** [comment]
This makes the project broken. I can't update the FreeBSD port because ```0.0.0``` versions mean that all dependent ports need to be bumped, which might not even be necessary.

**Comment by svigerske** [comment]
OK. But are there any other issues than this one and #339?

**Comment by yurivict** [comment]
> OK. But are there any other issues than this one and #339?

Just these two.

**Comment by svigerske** [comment]
What I wrote in https://github.com/coin-or/Ipopt/issues/340#issuecomment-487449388 was actually expected behavior. It is sufficient when Ipopt/configure has the right libtool version.

However, the tarball https://www.coin-or.org/download/source/Ipopt/Ipopt-3.12.13.tgz was completely wrong. It seems that this contained master instead of the release. I've now replaced it by a tarball with the actual 3.12.13 release. With this one, I seem to get proper library versions:
```
$ ls -1
libcoinmumps.la
libcoinmumps.so
libcoinmumps.so.1
libcoinmumps.so.1.6.1
libipopt.la
libipopt.so
libipopt.so.1
libipopt.so.1.10.13
```

**Comment by yurivict** [comment]
You shouldn't replace tarballs. This would break packages that already use them because of fingerprint change. In such case a new release should be made.

**Comment by svigerske** [comment]
Yes, but the release is actually correct. The problem was that the tarball didn't contain the release. If some projects get notified this way that there were not using the release that they thought they would, even better.

**Comment by yurivict** [comment]
This happened before with other projects. It looks like package breakage, or like somebody tries to substitute the tarball. Usually they say that such tarball replacement needs to be investigated for security violations, etc.

**Comment by svigerske** [comment]
Yeah, I'm a stubborn person. :)

Thank you very much for maintaining the Ipopt package in FreeBSD and reporting issues.
