### ISSUE TITLE
CPP_Example failing to run [Linux]

### ISSUE THREAD

**Issue by VigneshSella** [coin-or/Ipopt#344]
Hi, I'm using Ubuntu LTS 18.04 I believe. I copy + pasted all the header files and stuff from $IPOPTDIR/build/include/coin to my example folder. I am using the IDE CLion which automatically generates my makefile for me. I opened a new "hello world" project, and then replaced the executable in the CMakeLists.txt to cpp_example.cpp. 

```
cmake_minimum_required(VERSION 3.14)
project(testing)

set(CMAKE_CXX_STANDARD 14)

add_executable(testing cpp_example.cpp)
```

the error I get when I try running is the following: 

```
`====================[ Build | testing | Debug ]=================================
/opt/clion-2019.2/bin/cmake/linux/bin/cmake --build /home/vigneshsella/CLionProjects/testing/cmake-build-debug --target testing -- -j 2
[ 50%] Building CXX object CMakeFiles/testing.dir/cpp_example.cpp.o
[100%] Linking CXX executable testing
CMakeFiles/testing.dir/cpp_example.cpp.o: In function `main':
/home/vigneshsella/CLionProjects/testing/cpp_example.cpp:20: undefined reference to `MyNLP::MyNLP()'
/home/vigneshsella/CLionProjects/testing/cpp_example.cpp:26: undefined reference to `IpoptApplicationFactory'
collect2: error: ld returned 1 exit status
CMakeFiles/testing.dir/build.make:83: recipe for target 'testing' failed
make[3]: *** [testing] Error 1
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/testing.dir/all' failed
make[2]: *** [CMakeFiles/testing.dir/all] Error 2
CMakeFiles/Makefile2:84: recipe for target 'CMakeFiles/testing.dir/rule' failed
make[1]: *** [CMakeFiles/testing.dir/rule] Error 2
Makefile:118: recipe for target 'testing' failed
make: *** [testing] Error 2`
```

**Comment by svigerske** [comment]
Look like you missed MyNLP.cpp.

**Comment by VigneshSella** [comment]
![Screenshot from 2019-07-31 13-26-16](https://user-images.githubusercontent.com/44992615/62237578-d3b79180-b396-11e9-844e-5bf707f23d11.png)

I do in fact have MyNLP.cpp, it still fails to run. It's in the folder cpp_example is located in and running from.

**Comment by svigerske** [comment]
It should work fine with the Makefile provided by Ipopt. I will not look into fixing up your setup for you.

**Comment by VigneshSella** [comment]
![Screenshot from 2019-07-31 16-43-45](https://user-images.githubusercontent.com/44992615/62250377-63b70480-b3b2-11e9-9162-4a6b002f5569.png)

I'm having issues with the Makefile provided by Ipopt. I didn't make any adjustments, and this is what keeps appearing at runtime.

**Comment by svigerske** [comment]
Looks like you copied it somewhere else.

There is also https://projects.coin-or.org/BuildTools/wiki/user-examples

**Comment by zhumingpassional** [comment]
@VigneshSella @svigerske 

have you solved this problem?
I also encountered this issue.  The makefile version works, but my cmake version does not work.
