### ISSUE TITLE
problem with compilation on windows

### ISSUE THREAD

**Issue by zliao4** [coin-or/Ipopt#346]
When I tride to install Ipopt in windows (with cygwin), while I input command " make", it would return the error as the following picture shows:
![1](https://user-images.githubusercontent.com/25992217/65561684-62690a80-df11-11e9-92ba-c4564c0b9ee1.png)

Yeah I found that in the documentation it said I need to "need to download the fixed version from http://www.cmake.org/files/cygwin/make.exe or http://www.cmake.org/files/cygwin/make.exe-cygwin1.7", but I have tried and it turn out to be like this:
![2](https://user-images.githubusercontent.com/25992217/65561532-ca6b2100-df10-11e9-8497-55621f43260c.png)

so I was now wodering how to solve it? Thank you!

**Comment by svigerske** [comment]
You should run configure before make. https://coin-or.github.io/Ipopt/INSTALL.html#COMPILEINSTALL

**Comment by zliao4** [comment]
I already configured it...

**Comment by zliao4** [comment]
> You should run configure before make. https://coin-or.github.io/Ipopt/INSTALL.html#COMPILEINSTALL

Though the screen shot did not show, but I already configured it before I try to make

**Comment by zliao4** [comment]
> > You should run configure before make. https://coin-or.github.io/Ipopt/INSTALL.html#COMPILEINSTALL
> 
> Though the screen shot did not show, but I already configured it before I try to make


And here I tried it again, the problem still exists:

lzh11@DESKTOP-MDUR7HF ~
$ cd Ipopt/

lzh11@DESKTOP-MDUR7HF ~/Ipopt
$ ./configure
checking build system type... x86_64-unknown-cygwin
checking for gcc... gcc
checking host system type... x86_64-unknown-cygwin
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking whether make supports the include directive... yes (GNU style)
checking whether the C compiler works... yes
checking for C compiler default output file name... a.exe
checking for suffix of executables... .exe
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
checking whether g++ understands -c and -o together... yes
checking for gfortran... gfortran
checking whether we are using the GNU Fortran 77 compiler... yes
checking whether gfortran accepts -g... yes
checking how to get verbose linking output from gfortran... -v
checking for Fortran 77 libraries of gfortran...  -L/usr/lib/gcc/x86_64-pc-cygwin/7.4.0 -L/usr/lib/gcc/x86_64-pc-cygwin/7.4.0/../../../../x86_64-pc-cygwin/lib/../lib -L/usr/lib/gcc/x86_64-pc-cygwin/7.4.0/../../../../lib -L/lib/../lib -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-pc-cygwin/7.4.0/../../../../x86_64-pc-cygwin/lib -L/usr/lib/gcc/x86_64-pc-cygwin/7.4.0/../../.. -lgfortran -lquadmath -lm -lcygwin -ladvapi32 -lshell32 -luser32
checking for dummy main to link with Fortran 77 libraries... none
checking for Fortran 77 name-mangling scheme... lower case, underscore, no extra underscore
checking whether gfortran understands -c and -o together... yes
checking how to print strings... printf
checking for a sed that does not truncate output... /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /usr/x86_64-pc-cygwin/bin/ld.exe
checking if the linker (/usr/x86_64-pc-cygwin/bin/ld.exe) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 8192
checking how to convert x86_64-unknown-cygwin file names to x86_64-unknown-cygwin format... func_convert_file_noop
checking how to convert x86_64-unknown-cygwin file names to toolchain format... func_convert_file_noop
checking for /usr/x86_64-pc-cygwin/bin/ld.exe option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... file_magic ^x86 archive import|^x86 DLL
checking for dlltool... dlltool
checking how to associate runtime and link libraries... func_cygming_dll_for_implib
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /usr/bin/dd
checking how to truncate binary pipes... /usr/bin/dd bs=4096 count=1
checking for mt... no
checking if : is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for as... as
checking for dlltool... (cached) dlltool
checking for objdump... (cached) objdump
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -DDLL_EXPORT -DPIC
checking if gcc PIC flag -DDLL_EXPORT -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/x86_64-pc-cygwin/bin/ld.exe) supports shared libraries... yes
checking whether -lc should be explicitly linked in... yes
checking dynamic linker characteristics... Win32 ld.exe
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /usr/x86_64-pc-cygwin/bin/ld.exe
checking if the linker (/usr/x86_64-pc-cygwin/bin/ld.exe) is GNU ld... yes
checking whether the g++ linker (/usr/x86_64-pc-cygwin/bin/ld.exe) supports shared libraries... yes
checking for g++ option to produce PIC... -DDLL_EXPORT -DPIC
checking if g++ PIC flag -DDLL_EXPORT -DPIC works... yes
checking if g++ static flag -static works... yes
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/usr/x86_64-pc-cygwin/bin/ld.exe) supports shared libraries... yes
checking dynamic linker characteristics... Win32 ld.exe
checking how to hardcode library paths into programs... immediate
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
checking for gfortran option to produce PIC... -DDLL_EXPORT
checking if gfortran PIC flag -DDLL_EXPORT works... yes
checking if gfortran static flag -static works... no
checking if gfortran supports -c -o file.o... yes
checking if gfortran supports -c -o file.o... (cached) yes
checking whether the gfortran linker (/usr/x86_64-pc-cygwin/bin/ld.exe) supports shared libraries... yes
checking dynamic linker characteristics... Win32 ld.exe
checking how to hardcode library paths into programs... immediate
configure: libtool version info: -version-number 3:13:0
configure: WARNING: Could not automatically determine how to tell the linker about automatic inclusion of the path for shared libraries.  The test examples might not work if you link against shared objects.  You will need to set the LD_LIBRARY_PATH, DYLP_LIBRARY_PATH, or LIBDIR variable manually.
configure: Assuming that CXXLIBS is "-lstdc++ -lm".
configure: configuring doxygen documentation options
checking for doxygen... no
checking for latex... no
checking for dot... NO
checking for library containing cos... none required
checking for pkgconf... pkgconf
checking pkgconf is at least version 0.16.0... yes: 1.6.0
configure: pkgconf path is "/usr/local/lib/pkgconfig:"
checking for function dsyev_ in mkl_intel_lp64_dll.lib mkl_sequential_dll.lib mkl_core_dll.lib ... no
checking for function dsyev in mkl_intel_lp64_dll.lib mkl_sequential_dll.lib mkl_core_dll.lib ... no
checking for function DSYEV_ in mkl_intel_lp64_dll.lib mkl_sequential_dll.lib mkl_core_dll.lib ... no
checking for function DSYEV in mkl_intel_lp64_dll.lib mkl_sequential_dll.lib mkl_core_dll.lib ... no
checking for lapack.pc and blas.pc... no
checking for function dsyev_ in -llapack -lblas ... no
checking for function dsyev in -llapack -lblas ... no
checking for function DSYEV_ in -llapack -lblas ... no
checking for function DSYEV in -llapack -lblas ... no
configure: error: Required package LAPACK not found.

lzh11@DESKTOP-MDUR7HF ~/Ipopt
$ make --version
GNU Make 4.2.1
Built for x86_64-unknown-cygwin
Copyright (C) 1988-2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

lzh11@DESKTOP-MDUR7HF ~/Ipopt
$ make
make: *** No targets specified and no makefile found.  Stop.

**Comment by zliao4** [comment]
> > > You should run configure before make. https://coin-or.github.io/Ipopt/INSTALL.html#COMPILEINSTALL
> > 
> > 
> > Though the screen shot did not show, but I already configured it before I try to make
> 
> And here I tried it again, the problem still exists:
> 
> lzh11@DESKTOP-MDUR7HF ~
> $ cd Ipopt/
> 
> lzh11@DESKTOP-MDUR7HF ~/Ipopt
> $ ./configure
> checking build system type... x86_64-unknown-cygwin
> checking for gcc... gcc
> checking host system type... x86_64-unknown-cygwin
> checking for a BSD-compatible install... /usr/bin/install -c
> checking whether build environment is sane... yes
> checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
> checking for gawk... gawk
> checking whether make sets $(MAKE)... yes
> checking whether make supports nested variables... yes
> checking whether to enable maintainer-specific portions of Makefiles... no
> checking whether make supports the include directive... yes (GNU style)
> checking whether the C compiler works... yes
> checking for C compiler default output file name... a.exe
> checking for suffix of executables... .exe
> checking whether we are cross compiling... no
> checking for suffix of object files... o
> checking whether we are using the GNU C compiler... yes
> checking whether gcc accepts -g... yes
> checking for gcc option to accept ISO C89... none needed
> checking whether gcc understands -c and -o together... yes
> checking dependency style of gcc... gcc3
> checking for g++... g++
> checking whether we are using the GNU C++ compiler... yes
> checking whether g++ accepts -g... yes
> checking dependency style of g++... gcc3
> checking whether g++ understands -c and -o together... yes
> checking for gfortran... gfortran
> checking whether we are using the GNU Fortran 77 compiler... yes
> checking whether gfortran accepts -g... yes
> checking how to get verbose linking output from gfortran... -v
> checking for Fortran 77 libraries of gfortran... -L/usr/lib/gcc/x86_64-pc-cygwin/7.4.0 -L/usr/lib/gcc/x86_64-pc-cygwin/7.4.0/../../../../x86_64-pc-cygwin/lib/../lib -L/usr/lib/gcc/x86_64-pc-cygwin/7.4.0/../../../../lib -L/lib/../lib -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-pc-cygwin/7.4.0/../../../../x86_64-pc-cygwin/lib -L/usr/lib/gcc/x86_64-pc-cygwin/7.4.0/../../.. -lgfortran -lquadmath -lm -lcygwin -ladvapi32 -lshell32 -luser32
> checking for dummy main to link with Fortran 77 libraries... none
> checking for Fortran 77 name-mangling scheme... lower case, underscore, no extra underscore
> checking whether gfortran understands -c and -o together... yes
> checking how to print strings... printf
> checking for a sed that does not truncate output... /usr/bin/sed
> checking for grep that handles long lines and -e... /usr/bin/grep
> checking for egrep... /usr/bin/grep -E
> checking for fgrep... /usr/bin/grep -F
> checking for ld used by gcc... /usr/x86_64-pc-cygwin/bin/ld.exe
> checking if the linker (/usr/x86_64-pc-cygwin/bin/ld.exe) is GNU ld... yes
> checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
> checking the name lister (/usr/bin/nm -B) interface... BSD nm
> checking whether ln -s works... yes
> checking the maximum length of command line arguments... 8192
> checking how to convert x86_64-unknown-cygwin file names to x86_64-unknown-cygwin format... func_convert_file_noop
> checking how to convert x86_64-unknown-cygwin file names to toolchain format... func_convert_file_noop
> checking for /usr/x86_64-pc-cygwin/bin/ld.exe option to reload object files... -r
> checking for objdump... objdump
> checking how to recognize dependent libraries... file_magic ^x86 archive import|^x86 DLL
> checking for dlltool... dlltool
> checking how to associate runtime and link libraries... func_cygming_dll_for_implib
> checking for ar... ar
> checking for archiver @file support... @
> checking for strip... strip
> checking for ranlib... ranlib
> checking command to parse /usr/bin/nm -B output from gcc object... ok
> checking for sysroot... no
> checking for a working dd... /usr/bin/dd
> checking how to truncate binary pipes... /usr/bin/dd bs=4096 count=1
> checking for mt... no
> checking if : is a manifest tool... no
> checking how to run the C preprocessor... gcc -E
> checking for ANSI C header files... yes
> checking for sys/types.h... yes
> checking for sys/stat.h... yes
> checking for stdlib.h... yes
> checking for string.h... yes
> checking for memory.h... yes
> checking for strings.h... yes
> checking for inttypes.h... yes
> checking for stdint.h... yes
> checking for unistd.h... yes
> checking for dlfcn.h... yes
> checking for as... as
> checking for dlltool... (cached) dlltool
> checking for objdump... (cached) objdump
> checking for objdir... .libs
> checking if gcc supports -fno-rtti -fno-exceptions... no
> checking for gcc option to produce PIC... -DDLL_EXPORT -DPIC
> checking if gcc PIC flag -DDLL_EXPORT -DPIC works... yes
> checking if gcc static flag -static works... yes
> checking if gcc supports -c -o file.o... yes
> checking if gcc supports -c -o file.o... (cached) yes
> checking whether the gcc linker (/usr/x86_64-pc-cygwin/bin/ld.exe) supports shared libraries... yes
> checking whether -lc should be explicitly linked in... yes
> checking dynamic linker characteristics... Win32 ld.exe
> checking how to hardcode library paths into programs... immediate
> checking whether stripping libraries is possible... yes
> checking if libtool supports shared libraries... yes
> checking whether to build shared libraries... yes
> checking whether to build static libraries... no
> checking how to run the C++ preprocessor... g++ -E
> checking for ld used by g++... /usr/x86_64-pc-cygwin/bin/ld.exe
> checking if the linker (/usr/x86_64-pc-cygwin/bin/ld.exe) is GNU ld... yes
> checking whether the g++ linker (/usr/x86_64-pc-cygwin/bin/ld.exe) supports shared libraries... yes
> checking for g++ option to produce PIC... -DDLL_EXPORT -DPIC
> checking if g++ PIC flag -DDLL_EXPORT -DPIC works... yes
> checking if g++ static flag -static works... yes
> checking if g++ supports -c -o file.o... yes
> checking if g++ supports -c -o file.o... (cached) yes
> checking whether the g++ linker (/usr/x86_64-pc-cygwin/bin/ld.exe) supports shared libraries... yes
> checking dynamic linker characteristics... Win32 ld.exe
> checking how to hardcode library paths into programs... immediate
> checking if libtool supports shared libraries... yes
> checking whether to build shared libraries... yes
> checking whether to build static libraries... no
> checking for gfortran option to produce PIC... -DDLL_EXPORT
> checking if gfortran PIC flag -DDLL_EXPORT works... yes
> checking if gfortran static flag -static works... no
> checking if gfortran supports -c -o file.o... yes
> checking if gfortran supports -c -o file.o... (cached) yes
> checking whether the gfortran linker (/usr/x86_64-pc-cygwin/bin/ld.exe) supports shared libraries... yes
> checking dynamic linker characteristics... Win32 ld.exe
> checking how to hardcode library paths into programs... immediate
> configure: libtool version info: -version-number 3:13:0
> configure: WARNING: Could not automatically determine how to tell the linker about automatic inclusion of the path for shared libraries. The test examples might not work if you link against shared objects. You will need to set the LD_LIBRARY_PATH, DYLP_LIBRARY_PATH, or LIBDIR variable manually.
> configure: Assuming that CXXLIBS is "-lstdc++ -lm".
> configure: configuring doxygen documentation options
> checking for doxygen... no
> checking for latex... no
> checking for dot... NO
> checking for library containing cos... none required
> checking for pkgconf... pkgconf
> checking pkgconf is at least version 0.16.0... yes: 1.6.0
> configure: pkgconf path is "/usr/local/lib/pkgconfig:"
> checking for function dsyev_ in mkl_intel_lp64_dll.lib mkl_sequential_dll.lib mkl_core_dll.lib ... no
> checking for function dsyev in mkl_intel_lp64_dll.lib mkl_sequential_dll.lib mkl_core_dll.lib ... no
> checking for function DSYEV_ in mkl_intel_lp64_dll.lib mkl_sequential_dll.lib mkl_core_dll.lib ... no
> checking for function DSYEV in mkl_intel_lp64_dll.lib mkl_sequential_dll.lib mkl_core_dll.lib ... no
> checking for lapack.pc and blas.pc... no
> checking for function dsyev_ in -llapack -lblas ... no
> checking for function dsyev in -llapack -lblas ... no
> checking for function DSYEV_ in -llapack -lblas ... no
> checking for function DSYEV in -llapack -lblas ... no
> configure: error: Required package LAPACK not found.
> 
> lzh11@DESKTOP-MDUR7HF ~/Ipopt
> $ make --version
> GNU Make 4.2.1
> Built for x86_64-unknown-cygwin
> Copyright (C) 1988-2016 Free Software Foundation, Inc.
> License GPLv3+: GNU GPL version 3 or later http://gnu.org/licenses/gpl.html
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.
> 
> lzh11@DESKTOP-MDUR7HF ~/Ipopt
> $ make
> make: *** No targets specified and no makefile found. Stop.

Ok, I see ...
so the problem is that I did not install LAPACK ...
so how to install LAPACK on windows10?

**Comment by svigerske** [comment]
Since you are under Cygwin, check whether Cygwin has a way to install Lapack with its package manager (https://stackoverflow.com/questions/41137926/how-to-install-lapack-and-blas-using-cygwin).

I haven't used Cygwin for a long while and don't know whether building Ipopt on Cygwin is still working.

You seem to have checked out the master branch of Ipopt, which has a lot of changes w.r.t. the last stable version. You may want to consider using that one instead: https://coin-or.github.io/Ipopt/INSTALL.html#GETIPOPT
