### ISSUE TITLE
subversion and github repo are not in sync

### ISSUE THREAD

**Issue by ycollet** [coin-or/Ipopt#347]
The subversion repo at https://projects.coin-or.org/svn/Ipopt/trunk is not in sync with the github repo.

**Comment by svigerske** [comment]
Yes, that's right.

As [announced](https://list.coin-or.org/pipermail/ipopt/2019-April/004635.html) and [shown](https://projects.coin-or.org/Ipopt/), Ipopt moved to GitHub.

**Comment by ycollet** [comment]
Thanks for the reply.
I had posted this because all the others main repos of coinor are in sync ..
I will checked out the github version ...
