### ISSUE TITLE
Building Ipopt

### ISSUE THREAD

**Issue by apigott** [coin-or/Ipopt#348]
Having some issues building Ipopt referencing this documentation: https://www.coin-or.org/Ipopt/documentation/node14.html (admittedly new to building from a .tar)

(I'm working on a mac)

I downloaded the Ipopt .tar and the HSL .tar. I have a base directory that I renamed to CoinIpopt which contains some build files, etc. the Ipopt directory and the ThirdParty directory.

In the ThirdParty directory I moved HSL/HSL to just HSL, renamed the ma27d.f file to ma27ad.f and ran ./configure, make install. Worked without error.

Then I went back to CoinIpopt/Ipopt and ran ./configure without error. Then I tried make install and it came back with this:

`Making install in CUTErInterface
if test -z "$MYCUTER" -o -z "$CUTER"; then \
	  rm -f  ipoma.f; \
	  cp ./ipoma-dummy.f ipoma.f; \
	else \
	  sed "/#{sizing}/r $MYCUTER/double/config/tools.siz" CUTErInterface.f | sed -f $MYCUTER/double/config/cast.sed | sed "s/C64BIT//" > ipoma.f; \
	fi
/bin/sh ../../../libtool --tag=F77 --mode=compile gfortran  -O3 -fomit-frame-pointer -pipe -DNDEBUG   -c -o ipoma.lo ipoma.f
mkdir .libs
 gfortran -O3 -fomit-frame-pointer -pipe -DNDEBUG -c ipoma.f  -fno-common -o .libs/ipoma.o
/bin/sh ../../../libtool --tag=F77 --mode=link gfortran  -O3 -fomit-frame-pointer -pipe -DNDEBUG    -L/usr/local/opt/openblas/lib -o libdummy.la   ipoma.lo  
ar cru .libs/libdummy.a .libs/ipoma.o
ranlib .libs/libdummy.a
creating libdummy.la
(cd .libs && rm -f libdummy.la && ln -s ../libdummy.la libdummy.la)
make[3]: Nothing to be done for `install-exec-am'.
make[3]: Nothing to be done for `install-data-am'.
make[3]: Nothing to be done for `install-exec-am'.
make[3]: Nothing to be done for `install-data-am'.
make[2]: Nothing to be done for `install-exec-am'.
make[2]: Nothing to be done for `install-data-am'.`

I found some forums where it says "Nothing to be done" isn't necessarily bad news but the bash cmd ipopt -help still can't find ipopt.

The basedir CoinIpopt is still in my downloads folder btw, not sure if that makes a difference or where they should be installed.

**Comment by svigerske** [comment]
The messages from make say that everything went fine and the Ipopt libraries and header files should have been installed. If you didn't get the ASL source, then there will be no Ipopt binary.
I don't understand the part about moving "HSL/HSL to just HSL" and why you would have to rename HSL source files. If you got the HSL for Ipopt package from http://www.hsl.rl.ac.uk/ipopt/, you should only have to rename coinhsl-2013.05.30 to coinhsl.

Btw, the current Ipopt docu is at https://coin-or.github.io/Ipopt/.

**Comment by apigott** [comment]
Yep that's where I got the HSL package. I think actually what happened was there was an HSL directory in CoinIpopt (similar to BLAS, etc) but when I added the HSL directory from the downloaded tar I layered them when I should have just deleted the CoinIpopt directory and added the HSL straight from the tar.

So after that was figured out I had HSL/ma27d.f but the configure script in CoinIpopt kept throwing an error about not being able to find HSL/ma27ad.f. I found this documentation that suggests manually renaming (although now I see that it is old): https://projects.coin-or.org/svn/BuildTools/ThirdParty/HSL/stable/1.3/INSTALL.HSL.

I only have coinhsl.pc, coinhsl.pc.in, CoinHslConfig.h.in, so I'm not sure what coinhsl-version is.

At this point I feel like I've messed it up so much I need to restart. Is there a special method for deleting all these files I've unpacked from the .tar?

**Comment by svigerske** [comment]
rm -r and then unpack the tar again?

**Comment by apigott** [comment]
I feel like the install is cleaner after deleting and unpacking again but the ASL still isn't compiled right. In the docu you linked it has me do `./get` for the ASL subdirectory but `make test` still returns `no AMPL solver found, skipping test...`

So I understand this means that I need to download the solvers.tar from AMPL but then do I just rename the unpacked tar coinasl and move it to the /ASL directory?

<img width="409" alt="Screen Shot 2019-10-10 at 8 37 07 AM" src="https://user-images.githubusercontent.com/34166094/66578896-26e95580-eb39-11e9-91e7-97b837664fc0.png">

**Comment by svigerske** [comment]
It is `./get.ASL`, not `./get`.  Did the latter did anything that made you think it ran successful?

**Comment by apigott** [comment]
Sorry, checking my history I did run `./get.ASL`. Do I still need to download the .tar?

**Comment by apigott** [comment]
I take that back I should instead be running `configure`, `make`, `make install` in each subdirectory (BLAS, ASL, LAPACK) right?

**Comment by svigerske** [comment]
No, running configure, make, and make install in the Ipopt base directory will suffice.

So if you ran get.ASL, but the solvers directory was not created, then go on and investigate why this has happened.

**Comment by apigott** [comment]
Ah so I got the solvers directory and `make test` passes now with all the tests. However the ipopt directory is still not on the path (the bash command `ipopt` fails).

When I add the CoinIpopt directory do I just add the base directory? E.g. `export PATH=$PATH:~/CoinIpopt` or must I go deeper into the subdirectories? Nothing is in my `build` folder which I know is wrong but the executable still has to be there for `make test` and `make install` to work right? How do I find out where the .exe is so I can store that in my PATH?

**Comment by svigerske** [comment]
OK, this are now enough how-to-use-my-computer questions. You can figure this out easily by reading a good book or searching the internet. I'll close this issue.
