### ISSUE TITLE
cmake necessary for IDE like Clion

### ISSUE THREAD

**Issue by sogoogos** [coin-or/Ipopt#349]
I am trying to debug my code with Ipopt in Clion. I can compile the code with makefile provided. However, in order to use the full functionality of Clion as an IDE, I need cmake (CMakeList.txt).  Does such a cmake file exist for Ipopt? or Is there any good way to convert the makefile to cmake file?Writing a cmake file from scratch sounds a little overwhelming to me. 

I use Ubuntu LTS 18.04.

**Comment by svigerske** [comment]
I don't have cmake files and am not considering to write or add any.

**Comment by ycollet** [comment]
Hello,
Maybe you can have a look here:
https://github.com/ycollet/coinor-cmake/

It's a little bit "experimental", so, feel free to report bugs ...

**Comment by sogoogos** [comment]
@ycollet  thank you! I will try with it
