### ISSUE TITLE
make test fails

### ISSUE THREAD

**Issue by Leersmaekers** [coin-or/Ipopt#351]
Dear,

I tried to install IpOpt on a Windows 10 machine, by using cygwin. Furthermore I'm making use of the intel MKL (for Blas and Lapack), as well as coinHSL. The visual studio version I use, is VS2019. I'm not sure if it is important to mention that I used the compile_f2c for the Fortran code conversion.

In order to configure IpOpt, I first modified my Cygwin.bat file, by adding the following line:
call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"

After entering the CoinIpopt folder, I use this entry to configure:
MKLROOT="C:\Program Files (x86)\IntelSWTools\compilers_and_libraries_2019.1.144\windows\mkl"
 MKL_LIBS="-L${MKLROOT}/lib/intel64 -Wl,--no-as-needed -lmkl_intel_lp64
    -lmkl_lapack95_lp64 -lmkl_sequential -lmkl_core -lgfortran -fopenmp -lpthread -lm -ldl"
  ADD_CFLAGS="-fopenmp -fno-common -fexceptions"
  ADD_CXXFLAGS="-fopenmp -fno-common -fexceptions"
  ADD_FFLAGS="-fopenmp -fexceptions"

  ./configure -enable-doscompile=msvc --with-blas-lib="${MKL_LIBS}" --with-lapack-lib="${MKL_LIBS}"

./configure succeeded.
Next I run 'make', which also succeeds.
However, when running 'make test', I encounter some errors (needed to translate it though):

make[2]: Entering '/home/LaurentK/CoinIpopt/Ipopt/test'
make[2]: *** There is no rule to create target 'Files', needed for 'hs071_cpp.exe'. Stopped.
make[2]: Leaving '/home/LaurentK/CoinIpopt/Ipopt/test'
make[1]: *** [Makefile:1063: unitTest] Error 2
make[1]: Leaving '/home/LaurentK/CoinIpopt/Ipopt'
make: *** [Makefile:694: test] Error 2

Does anyone have an idea what is going wrong here? It would be nice if 'make test' works, such that I have an example solution for the projects I'm planning.

Kind regards,
Laurent Keersmaekers

**Comment by svigerske** [comment]
Maybe it's a problem with the space in the path to MKL. Try using the shortened dos-compatible path (something with `~1` or `~2`) for MKLROOT.

**Comment by Leersmaekers** [comment]
I've now modified the configure lines to:

MKLROOT="C:/progra~2/IntelSWTools/compilers_and_libraries_2019.1.144/windows/mkl"
 MKL_LIBS="-L${MKLROOT}/lib/intel64 -Wl,--no-as-needed -lmkl_intel_lp64
    -lmkl_lapack95_lp64 -lmkl_sequential -lmkl_core -lgfortran -fopenmp -lpthread -lm -ldl"
  ADD_CFLAGS="-fopenmp -fno-common -fexceptions"
  ADD_CXXFLAGS="-fopenmp -fno-common -fexceptions"
  ADD_FFLAGS="-fopenmp -fexceptions"

  ./configure -enable-doscompile=msvc --with-blas-lib="${MKL_LIBS}" --with-lapack-lib="${MKL_LIBS}"

As you can see, it's now using "progra~2", as well as slashes instead of back-slashes, as the latter was ignored somehow.
However, running "make test" still leads to the same error.

**Comment by Leersmaekers** [comment]
In between the output lines, I saw there was no 'dos2unix' executable. I now added the executable in the folder 'C:\cygwin64\usr\local\bin'. It still didn't succeed to run the 'make test' without errors, but now I observe the following irregularities:

cl : Command line warning D9035 : option 'o' has been deprecated and will be removed in a future release
cl : Command line warning D9002 : ignoring unknown option '--no-as-needed'
cl : Command line warning D9002 : ignoring unknown option '-fopenmp'
cl : Command line warning D9002 : ignoring unknown option '--no-as-needed'
cl : Command line warning D9002 : ignoring unknown option '-fopenmp'
cl : Command line warning D9002 : ignoring unknown option '-LC:/progra~2/IntelSWTools/compilers_and_libraries_2019.1.144/windows/mkl/lib/intel64'
cl : Command line warning D9002 : ignoring unknown option '-lmkl_intel_lp64'
cl : Command line warning D9002 : ignoring unknown option '-lmkl_lapack95_lp64'
cl : Command line warning D9002 : ignoring unknown option '-lmkl_sequential'
cl : Command line warning D9002 : ignoring unknown option '-lmkl_core'
cl : Command line warning D9002 : ignoring unknown option '-lgfortran'
cl : Command line warning D9002 : ignoring unknown option '-lpthread'
cl : Command line warning D9002 : ignoring unknown option '-ldl'

Followed by many link errors:
libipopt.lib(IpIpoptApplication.obj) : error LNK2019: unresolved external symbol "public: __cdecl Ipopt::Journalist::Journalist(void)" (??0Journalist@Ipopt@@QEAA@XZ) referenced in function "public: __cdecl Ipopt::IpoptApplication::IpoptApplication(bool,bool)" (??0IpoptApplication@Ipopt@@QEAA@_N0@Z)
.
.
.

hs071_cpp.exe : fatal error LNK1120: 69 unresolved externals
make[2]: *** [Makefile:435: hs071_cpp.exe] Error 2
make[2]: Leaving '/home/LaurentK/CoinIpopt/Ipopt/test'
make[1]: *** [Makefile:1063: unitTest] Error 2
make[1]: Leaving '/home/LaurentK/CoinIpopt/Ipopt'
make: *** [Makefile:694: test] Error 2

**Comment by svigerske** [comment]
The syntax of the flags you specify (`-L`, `-l`, `-f`) are specific for GNU, clang, and some other compilers, but are not understood by MS cl. (Current Ipopt versions would translate the `-L`, `-l`, but you seem to use an older version.)

**Comment by Leersmaekers** [comment]
I'm using Ipopt version 3.12. Do you suggest to use another version? If not, how should I modify the configure line in order to use it with Ms cl?

**Comment by svigerske** [comment]
I would suggest to try Ipopt 3.13 and use Msys2 instead of Cygwin.
Installation instructions are at https://coin-or.github.io/Ipopt/INSTALL.html

For MKL, I think there is some environment variable (`LIB`?) you can set where MS cl will look automatically for libraries. Then configure might pick up MKL automatically and you can skip all of your flags (except for `--enable-doscompile=msvc` if still on Ipopt 3.12).

**Comment by Leersmaekers** [comment]
I'm not aware of this LIB environment variable.
Are the "--enable-doscompile=msvc", "--with-blas-lib" and "--with-lapack-lib" still valid with ipopt 3.13?

**Comment by svigerske** [comment]
> I'm not aware of this LIB environment variable.
> Are the "--enable-doscompile=msvc", "--with-blas-lib" and "--with-lapack-lib" still valid with ipopt 3.13?

No, `--enable-doscompile=msvc` has become `--enable-msvc` (https://coin-or.github.io/Ipopt/INSTALL.html#SYSTEMPACKAGES_MSYS) and there is `--with-lapack` to specify linker flags to use Lapack (https://coin-or.github.io/Ipopt/INSTALL.html#EXTERNALCODE_LINALG).

**Comment by Leersmaekers** [comment]
I now get a warning while configuring:
configure: WARNING: Could not automatically determine how to tell the linker about automatic inclusion of the path for shared libraries.  The test examples might not work if you link against shared objects.  You will need to set the LD_LIBRARY_PATH, DYLP_LIBRARY_PATH, or LIBDIR variable manually.

And warnings/errors when doing 'make':
*** Warning: Linking the shared library libipopt.la against the
*** static library mkl_intel_lp64_dll.lib is not portable!

*** Warning: Linking the shared library libipopt.la against the
*** static library mkl_sequential_dll.lib is not portable!

*** Warning: Linking the shared library libipopt.la against the
*** static library mkl_core_dll.lib is not portable!
LINK : fatal error LNK1131: no library file specified

**Comment by svigerske** [comment]
The warnings are "ok", I don't know how to get rid of themm.

Can you call make with V=1, so we can see what it tried to do?

**Comment by Leersmaekers** [comment]
Well, that still didn't work in cygwin. But as you suggested above, I tried msys2. The behviour of both systems is equal, until the warnings mentioned above are encountered:
- cygwin stops with the LNK fatal errors
- msys2 shows the warnings, but proceeds

With msys2, the tests succeeded now, as well as the example.exe's.

The only step I still need to do, is to use Ipopt in an own VS project (I suppose the makefile should help me here?).

**Comment by svigerske** [comment]
make install should install header files and libraries into `$prefix/include/coin-or`, `$prefix/lib` and `$prefix/bin`. Somehow you can tell MSVS to use them, I guess.

**Comment by Leersmaekers** [comment]
Thanks a lot, everything worked fine in VS now!

I was a bit confused with the libraries $prefix/include/coin-or, $prefix/include/lib and $prefix/include/bin, since they are now installed into a different location, compared to earlier Ipopt versions.

**Comment by svigerske** [comment]
There were so many changes regarding the buildsystem for 3.13 (https://coin-or.github.io/Ipopt/CHANGELOG.html) that it seemed to be a good opportunity to also improve (in my opinion :)) on the default installation locations.

**Comment by tkralphs** [comment]
@svigerske are libraries and binaries really installed in `$prefix/include/bin` and `$prefix/include/lib` or is that a typo above?

**Comment by svigerske** [comment]
That is a typo. The .lib goes into `$prefix/lib` and the DLL and exe goes into `$prefix/bin`. I think libtool puts the DLLs into the bindir, because there is no rpath-magic available that could be used to tell the exe where to find the DLL.

**Comment by tkralphs** [comment]
Do you want to just edit your original comment to remove the typo and then I'll just delete these comments in case anyone looks at this issue in the future?
