### ISSUE TITLE
TNLPAdapter::ResortBnds may return uninitialized values  

### ISSUE THREAD

**Issue by cnpetra** [coin-or/Ipopt#352]
Calling TNLPAdapter::ResortBnds from TNLP::intermediate_callback leaves entries in the (output) second and fourth double arrays uninitialized. Please note that the uninitialized entries occur both when 'fixed_variable_treatment' is  'make_parameter' and 'make_constraint'. These uninitialized values/multipliers (seem to) correspond to the fixed variables, as expected. I can provide a modification of the simple Cpp_example for which valgrind reports uninitialized values.

First, I find that it is not good practice to let uninitialized values in an output array for obvious reasons. For my code, this creates some serious damage since I'm sending these arrays over MPI and some low-level system socket communication functions just freeze on a particular OS. 

Second, it is a intriguing that this occurs also when 'fixed_variable_treatment' is  'make_constraint'. Isn't ResortBnds supposed to compute bound multipliers for fixed variables?

A quick fix on the caller code side is to initialize the two bound multipliers once prior to calling ResortBnds. But I hope this can be also fixed inside Ipopt or at least the method's signature to be changed to make it clear that not all values are returned (e.g., should also return a flag and indexes of the bounds computed/returned).

Cosmin

**Comment by svigerske** [comment]
ResortBnds doesn't compute multipliers, it only fills the entries of the given arrays that do not correspond to fixed variables.
The bound multipliers for fixed variables after set after the call to ResortBnds, see from https://github.com/coin-or/Ipopt/blob/master/src/Interfaces/IpTNLPAdapter.cpp#L2101 on.

I think I can change the method to initialize all array entries to 0.0 by default and add a flag that allows to disable this.
