### ISSUE TITLE
include/coin-or

### ISSUE THREAD

**Issue by jschueller** [coin-or/Ipopt#354]
hello,

in #345 the include dir change from PREFIX/include/coin to PREFIX/include/coin-or
we have to adapt our build systems
do we expect other coin-or packages to use that layout ? currently it doesn't seem like such changes are happening, eg rdepends packages such as bonmin do not compile anymore

cc @svigerske

**Comment by svigerske** [comment]
I would expect so. Changes are happening - very slowly.

pkg-config should always return the right include path.
