### ISSUE TITLE
IOError:./2.PM2.structure.pdb.txt not find

### ISSUE THREAD

**Issue by drbinguo** [coin-or/Ipopt#355]
I compiled the ipopt with Blas, Lapack, ASL，HSL，Metis ,pyIpopt and Mumps.
I found it could be reproduced using the binary file in here(the Ipopt-3.3.1 Ubuntu18.04.1 package).
and here is the example I changed to reproduce the problem with the command  pastis-pm2 .  :

IoError:/2.PM2.structure.pdb.txt not found

Please tell me how can I fix it.
Any help is appreciated.

Thank you

**Comment by svigerske** [comment]
I have no idea what I should do here.
It seems that some file wasn't found. The name that it looks for (2.PM2.structure.pdb.txt??) has nothing to do with Ipopt itself. Maybe it's an issue with the "command pastis-pm2", whatever that is.

**Comment by drbinguo** [comment]
OK, Thanks

At 2019-12-04 00:33:37, "Stefan Vigerske" <notifications@github.com> wrote:


I have no idea what I should do here.
It seems that some file wasn't found. The name that it looks for (2.PM2.structure.pdb.txt??) has nothing to do with Ipopt itself. Maybe it's an issue with the "command pastis-pm2", whatever that is.
