### ISSUE TITLE
EXIT:Restoration Failed!

### ISSUE THREAD

**Issue by drbinguo** [coin-or/Ipopt#356]
There was an issue in the  Ipopt version 3.12.4, running with linear solver ma27.
It shows that "EXIT: Restoration Failed!" 

Number of Iterations .... : 45909
It shows that "Restoration phase converged to a feasible point that is unacceptable to the filter for the original problem. Restoration phase in the restoration phase failed." in the file "2.PM2.log“.
Number of objective function evaluations = 198573
Number of objective gradient evaluations = 45834
Number of equality constratint evaluations =0
Number of inequality constraint evaluations = 198573
Number of equality constraint Jacobian evaluations =0
Number of inequality constraint Jacobian evaluations = 45941
Number of Lagrangian Hessian evaluations =0
Total CPU secs in IPOPT(w/o function evaluations)=83.574
Total CPU secs in NLP function evaluations = 1595.183
Objective value 
f(x*)=-5.339160e+06

Any help is appreciated.

Thank you

**Comment by svigerske** [comment]
I don't know what to do about that. Ipopt got stuck in a local infeasible point, maybe.
