### ISSUE TITLE
Complementary slackness violated when scaling

### ISSUE THREAD

**Issue by mzanon** [coin-or/Ipopt#358]
First of all thank you very much for giving us such a wonderful solver!

I realized that in some cases Ipopt is returning a solution which violates the complementary slackness condition. I realized that in my case I got lambda*g = 10 mu, this might be random but might help tracing the issue.

I realized that this issue is not there if I set the option nlp_scaling_method = 'none'.

**Comment by svigerske** [comment]
Hmm, by how much is the complementarity violated?
According to the [termination options](https://coin-or.github.io/Ipopt/OPTIONS.html#OPT_Termination), it's sufficient to have the "max-norm of the (unscaled) complementarity" to be below 0.0001.

**Comment by mzanon** [comment]
Hi Stefan,

thank you for your quick answer!
These are the options I am setting:

tol = 1e-12
dual_inf_tol = 1e-12
constr_viol_tol = 1e-12
compl_inf_tol = 1e-12
acceptable_tol = 1e-6
acceptable_dual_inf_tol = 1e-6
acceptable_constr_viol_tol = 1e-6
acceptable_compl_inf_tol = 1e-6
bound_relax_factor = 0
honor_original_bounds = 'no'
fixed_variable_treatment = 'make_constraint'

If I add

nlp_scaling_method = 'none'

then I get the correct result, otherwise the product of the inequality multipliers with the constraint they correspond to is 10 times larger than it should.

I am calling Ipopt through casadi, I don't know if that might be part of the issue.

**Comment by svigerske** [comment]
Well, the stopping criteria of Ipopt have been a mystery for many, including me. :)
The criterion that uses "tol" depends on scaling, so there could be an effect when scaling is disabled (apart from all iterates being different, probably).

One could need to look at the detailed Ipopt log to see why it thought that it can stop and what the final violation of complementarity is according to Ipopt.

**Comment by mzanon** [comment]
Right, I am sorry but I forgot to mention that I did check whether the (IP-relaxed) KKT conditions are satisfied and they indeed are, but for a barrier parameter which is 10 times larger than the one declared by Ipopt. I also tried the option

mu_target = 1e-12

and the KKTs were satisfied for mu = 1e-11. So I think the stopping is perfectly legit (for mu = 1e-11). Essentially this makes the "bug" quite unnoticeable and harmless, it's more a matter of consistency than anything else.

**Comment by svigerske** [comment]
~~The actual value of mu shouldn't matter for the complementarity tolerance. If compl_inf_tol is 1e-12, then you should get a solution where complementarity is violated by 1e-12 at most, I would think (as long as Ipopt claimed to have stopped with an optimal solution and not just for some other reason).~~
EDIT: If setting mu_target, then complementarity is evaluated with respect to this mu_target.

**Comment by svigerske** [comment]
Sorry, my previous response was wrong.

If mu_target is set, then complementarity for inequality constraints is measured as max(||(s-s_L)min(lambda,0)-mu_target||,|(s-s_U)max(lambda,0)-mu_target||), where the norm is the infinity-norm, s are the values of the slack variables (think of it as g(x)), and s_L and s_U are the left- and right-hand-side, resp., of the inequality constraints.
This is for the scaled problem. Code is at https://github.com/coin-or/Ipopt/blob/master/src/Algorithm/IpIpoptCalculatedQuantities.cpp#L2489   
For the unscaled problem, this quantity is divided by the scaling factor for the objective function (https://github.com/coin-or/Ipopt/blob/master/src/Algorithm/IpIpoptCalculatedQuantities.cpp#L2637).
But also the multipliers that are reported back in finalize_solution are divided by the scaling factor for the objective function.

There can be a small error ||s-g(x)||, but according to your tolerances, this should also be in the order of 1e-12.

The decision on whether the iterate satisfies all tolerances is made at https://github.com/coin-or/Ipopt/blob/master/src/Algorithm/IpOptErrorConvCheck.cpp#L224-L225 Maybe you can debug a bit in this code and the mentioned places in IpIpoptCalculatedQuantities.cpp to see what is going on.
