### ISSUE TITLE
Run Derivative Checker programmatically

### ISSUE THREAD

**Issue by pattacini** [coin-or/Ipopt#360]
Hi, 

I'm wondering whether there exists a way to run the Derivative Checker programmatically, meaning upon function call, so that I could verify if there are errors by analyzing the object returned by the function.

I've gone through the documentation and made a search on Google as well but unfruitfully. Apparently, there is available [`Ipopt::TNLPAdapter::CheckDerivatives`][1], quite undocumented though. However, I don't seem I managed to get it to work correctly.

Instead, it'd be great if one could achieve this check via the main `Ipopt::IpoptApplication` class. Is it somehow implemented?

I would need this as I'm preparing an assignment for students and I'd like to give scores also on the basis of the correctness of the derivatives implementation.

Thanks a lot in advance!

[1]: https://coin-or.github.io/Ipopt/classIpopt_1_1TNLPAdapter.html#a78902bb3776b2bc23865eae0c8423664

**Comment by svigerske** [comment]
Where did you get stuck in calling `Ipopt::TNLPAdapter::CheckDerivatives` directly?
Getting the TNLPAdapter could be difficult. https://coin-or.github.io/Ipopt/INTERFACES.html#INTERFACE_CPP_ADDITIONAL gives some hints on how to get it from the TNLP intermediate_callback.

Making it accessible via `Ipopt::IpoptApplication` or as a method of `TNLP` should be possible, but it's not there so far.

**Comment by pattacini** [comment]
Thanks @svigerske for the heads-up.

Assuming that the class `A` inherits from `TNLP`, I've tried both the following approaches:

1. Using the `TNLPAdapter` constructor straight away.
   ```c++
    Ipopt::SmartPtr<A> nlp=new A();
    Ipopt::SmartPtr<Ipopt::TNLPAdapter> tnlp_adapter=new Ipopt::TNLPAdapter(nlp);
    tnlp_adapter->CheckDerivatives(Ipopt::TNLPAdapter::FIRST_ORDER_TEST,0);
    ```
1. Inspired from the pointer you gave above.
    ```c++
    Ipopt::SmartPtr<A> nlp=new A();
    Ipopt::TNLPAdapter* tnlp_adapter=dynamic_cast<Ipopt::TNLPAdapter*>(Ipopt::GetRawPtr(nlp));
    tnlp_adapter->CheckDerivatives(Ipopt::TNLPAdapter::FIRST_ORDER_TEST,0);
    ```

However, the call to `CheckDerivatives` seg-faults in both cases. Interestingly, for the first approach, I can also see this error message:
```
terminate called after throwing an instance of 'Ipopt::TNLPAdapter::ERROR_IN_TNLP_DERIVATIVE_TEST'
```

Do you have any hints on this?

**Comment by svigerske** [comment]
In the first case, can you catch the exception and get its message? Probably the problem is that you the TNLPAdapter didn't have a journalist (2nd argument to TNLPAdapter).

In the second case, tnlp_adapter was probably NULL, because if A is a TNLP, then it cannot be cast to a TNLPAdapter.

**Comment by pattacini** [comment]
>In the second case, tnlp_adapter was probably NULL, because if A is a TNLP, then it cannot be cast to a TNLPAdapter.

Got it 👍 although I got trapped by the following line reachable at the link you posted earlier:
```c++
tnlp_adapter = dynamic_cast<TNLPAdapter*>(GetRawPtr(orignlp->nlp()));
```

>Probably the problem is that you the TNLPAdapter didn't have a journalist (2nd argument to TNLPAdapter).

You were right 👍 
Now the following snippet is not seg-faulting:
```c++
Ipopt::SmartPtr<Ipopt::Journal> jrnl=new Ipopt::StreamJournal("derivative-checker",Ipopt::EJournalLevel::J_ALL);
Ipopt::SmartPtr<Ipopt::Journalist> jnlst=new Ipopt::Journalist();
jnlst->AddJournal(jrnl);

Ipopt::SmartPtr<A> nlp=new A();
Ipopt::SmartPtr<Ipopt::TNLPAdapter> tnlp_adapter=new Ipopt::TNLPAdapter(nlp,jnlst);
bool correct=tnlp_adapter->CheckDerivatives(Ipopt::TNLPAdapter::FIRST_ORDER_TEST,0);
```

:warning: The problem is that `correct` is always true regardless of the correctness of the derivative test. Anyway, I can imagine that I could retrieve the information I need by relying on the Journalist `jnlst`. However, nothing gets printed.

As I'm not really into the "Journalism" of Ipopt, would you be so kind as to give me the right direction to go in this context? How could I force it to print the journal?

**Comment by pattacini** [comment]
Got it 👍 
I missed specifying the output stream. Infact, this is working fine now:
```c++
std::ostringstream ss;
Ipopt::SmartPtr<Ipopt::StreamJournal> jrnl=new Ipopt::StreamJournal("derivative-checker",Ipopt::EJournalLevel::J_ALL);
jrnl->SetOutputStream(&ss);
```

Thanks again for the help.
