### ISSUE TITLE
Fortran 90 Interface?

### ISSUE THREAD

**Issue by zz273** [coin-or/Ipopt#362]
Hi, all!

I have tried the pyipopt to run IPOPT. That works well. Thanks!

But I am using Fortran 90 now. I look into hs071_f for the Fortran interface. I guess it is written in Fortran 77? Unfortunately, I really don't understand.

I was wondering whether there was a Fortran 90 interface? 

Looking forward to anyone's advice! Thanks in advance.

**Comment by zz273** [comment]
I just found a Fortran90 Interface Source from http://apmonitor.com/wiki/index.php/Main/DownloadIpopt.

But I cannot build it. It is because I am using Mac but the source is for Windows?

Errors:

`gfortran hs071.f90 -o vfi.out -fbounds-check -O2`
`Undefined symbols for architecture x86_64:`
`  "_ipaddintoption_", referenced from:`
  `    _MAIN__ in cculABQh.o`
`  "_ipaddnumoption_", referenced from:`
 `     _MAIN__ in cculABQh.o`
`  "_ipaddstroption_", referenced from:`
`      _MAIN__ in cculABQh.o`
`  "_ipcreate_", referenced from:`
 `     _MAIN__ in cculABQh.o`
`  "_ipfree_", referenced from:`
`      _MAIN__ in cculABQh.o`
`  "_ipopenoutputfile_", referenced from:`
 `     _MAIN__ in cculABQh.o`
 ` "_ipsolve_", referenced from:`
`      _MAIN__ in cculABQh.o`
`ld: symbol(s) not found for architecture x86_64`
`collect2: error: ld returned 1 exit status`

**Comment by svigerske** [comment]
There is no interface specifically for Fortran 90, but I assume that the [Fortran 77 interface](https://coin-or.github.io/Ipopt/INTERFACES.html#INTERFACE_FORTRAN) can be used from Fortran 90, too.

The hs071.f example is for any compiler that can handle at least Fortran 77. In the output you send it seems that you forgot to link against the Ipopt library.
After you installed Ipopt, make sure the path to ipopt.pc (installed in `$prefix/lib/pkgconfig`) is part of the PKG_CONFIG_PATH and use `pkg-config --libs ipopt` to get the flags required to link against Ipopt. Additionally, you probably need `-lstdc++`, too. Or have a look at the Makefiles of examples that come with Ipopt.

**Comment by zz273** [comment]
Hi Stefan @svigerske, thank you for your advice. Now I understand that I should try to link to IPOPT. I am using gfortran, so I don't really understand the command `pkg-config --libs ipopt`. Could you please give me more details? (Sorry that I am very new to these...)

I also want to use the following command to link ipopt, but I don't know whether it makes sense or not. Could you please help me with it? Thank you very much!

`gfortran hs071.f90 -o hs071.out -L /usr/local/lib -lipopt`

**Comment by svigerske** [comment]
> Hi Stefan @svigerske, thank you for your advice. Now I understand that I should try to link to IPOPT. I am using gfortran, so I don't really understand the command `pkg-config --libs ipopt`. Could you please give me more details? (Sorry that I am very new to these...)

Ipopt installs a [pkg-config](https://people.freedesktop.org/~dbn/pkg-config-guide.html) file `$prefix/lib/pkgconfig/ipopt.pc`, which includes information on how to builds (compile and link) against the Ipopt libraries.  `pkg-config --libs ipopt` is the command that tells you the linker flags, which you add to your gfortran call.

> I also want to use the following command to link ipopt, but I don't know whether it makes sense or not. Could you please help me with it? Thank you very much!
> 
> `gfortran hs071.f90 -o hs071.out -L /usr/local/lib -lipopt`

Yes, that could work.

**Comment by zz273** [comment]
Hi Stefan @svigerske, thank you for the reply.

I tried `gfortran hs071.f90 -o hs071.out -L /usr/local/lib -lipopt -g -Wall -fcheck=all` and received some wanings:

```
hs071.f90:198:41:

  198 | subroutine EV_F(N, X, NEW_X, F, IDAT, DAT, IERR)
      |                                         1
Warning: Unused dummy argument 'dat' at (1) [-Wunused-dummy-argument]
hs071.f90:198:36:

  198 | subroutine EV_F(N, X, NEW_X, F, IDAT, DAT, IERR)
      |                                    1
Warning: Unused dummy argument 'idat' at (1) [-Wunused-dummy-argument]
hs071.f90:198:27:

  198 | subroutine EV_F(N, X, NEW_X, F, IDAT, DAT, IERR)
      |                           1
Warning: Unused dummy argument 'new_x' at (1) [-Wunused-dummy-argument]
hs071.f90:216:49:

  216 | subroutine EV_GRAD_F(N, X, NEW_X, GRAD, IDAT, DAT, IERR)
      |                                                 1
Warning: Unused dummy argument 'dat' at (1) [-Wunused-dummy-argument]
hs071.f90:216:44:

  216 | subroutine EV_GRAD_F(N, X, NEW_X, GRAD, IDAT, DAT, IERR)
      |                                            1
Warning: Unused dummy argument 'idat' at (1) [-Wunused-dummy-argument]
hs071.f90:216:32:

  216 | subroutine EV_GRAD_F(N, X, NEW_X, GRAD, IDAT, DAT, IERR)
      |                                1
Warning: Unused dummy argument 'new_x' at (1) [-Wunused-dummy-argument]
hs071.f90:237:39:

  237 | subroutine EV_G(N, X, NEW_X, M, G, IDAT, DAT, IERR)
      |                                       1
Warning: Unused dummy argument 'idat' at (1) [-Wunused-dummy-argument]
hs071.f90:237:27:

  237 | subroutine EV_G(N, X, NEW_X, M, G, IDAT, DAT, IERR)
      |                           1
Warning: Unused dummy argument 'new_x' at (1) [-Wunused-dummy-argument]
hs071.f90:256:70:

  256 | subroutine EV_JAC_G(TASK, N, X, NEW_X, M, NZ, ACON, AVAR, A, IDAT, DAT, IERR)
      |                                                                      1
Warning: Unused dummy argument 'dat' at (1) [-Wunused-dummy-argument]
hs071.f90:256:65:

  256 | subroutine EV_JAC_G(TASK, N, X, NEW_X, M, NZ, ACON, AVAR, A, IDAT, DAT, IERR)
      |                                                                 1
Warning: Unused dummy argument 'idat' at (1) [-Wunused-dummy-argument]
hs071.f90:256:40:

  256 | subroutine EV_JAC_G(TASK, N, X, NEW_X, M, NZ, ACON, AVAR, A, IDAT, DAT, IERR)
      |                                        1
Warning: Unused dummy argument 'm' at (1) [-Wunused-dummy-argument]
hs071.f90:256:37:

  256 | subroutine EV_JAC_G(TASK, N, X, NEW_X, M, NZ, ACON, AVAR, A, IDAT, DAT, IERR)
      |                                     1
Warning: Unused dummy argument 'new_x' at (1) [-Wunused-dummy-argument]
hs071.f90:296:97:

  296 | subroutine EV_HESS(TASK, N, X, NEW_X, OBJFACT, M, LAM, NEW_LAM, NNZH, IRNH, ICNH, HESS, IDAT, DAT, IERR)
      |                                                                                                 1
Warning: Unused dummy argument 'dat' at (1) [-Wunused-dummy-argument]
hs071.f90:296:92:

  296 | subroutine EV_HESS(TASK, N, X, NEW_X, OBJFACT, M, LAM, NEW_LAM, NNZH, IRNH, ICNH, HESS, IDAT, DAT, IERR)
      |                                                                                            1
Warning: Unused dummy argument 'idat' at (1) [-Wunused-dummy-argument]
hs071.f90:296:62:

  296 | subroutine EV_HESS(TASK, N, X, NEW_X, OBJFACT, M, LAM, NEW_LAM, NNZH, IRNH, ICNH, HESS, IDAT, DAT, IERR)
      |                                                              1
Warning: Unused dummy argument 'new_lam' at (1) [-Wunused-dummy-argument]
hs071.f90:296:36:

  296 | subroutine EV_HESS(TASK, N, X, NEW_X, OBJFACT, M, LAM, NEW_LAM, NNZH, IRNH, ICNH, HESS, IDAT, DAT, IERR)
      |                                    1
Warning: Unused dummy argument 'new_x' at (1) [-Wunused-dummy-argument]

```

When I execute by `./hs071.out`, I received errors as follows:
```
$ ./hs071.out

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0x10a03af3d
#1  0x10a03a34d
#2  0x7fff5fd2db5c
#3  0x109e1ae78
#4  0x109dfea86
#5  0x109dff9e6
Segmentation fault: 11

```

I do not understand what is going wrong here. Could you please help me with it? Thanks a lot!

**Comment by svigerske** [comment]
The warnings seem harmless.

One special thing about the Fortran interface is that the code is different on 32 vs 64 platforms: https://github.com/coin-or/Ipopt/blob/master/examples/hs071_f/hs071_f.f.in#L69

The hs071.f90 that I pulled from https://www.apmonitor.com/download/ipopt_lib.zip has
```
  !
  !  Place for storing the Ipopt Problem Handle
  !
  !  for 32 bit platforms
  integer IPROBLEM
  integer IPCREATE
```
Does that fit to the Ipopt library that you are using, i.e., is that a 32-bit library? If that's 64-bit, then this may need to be
```
  integer*8 IPROBLEM
  integer*8 IPCREATE
```
However, I don't really know Fortran much.

**Comment by zz273** [comment]
Thank you so much for the correction! It works!
