### ISSUE TITLE
How is HSL solver chosen?

### ISSUE THREAD

**Issue by djwenren** [coin-or/Ipopt#363]
Hello!

First thanks for making this fantastic optimization tool. I have a question regarding how Ipopt chooses the HSL linear solver it uses. I build Ipopt using the installation instructions at https://coin-or.github.io/Ipopt/INSTALL.html. I have the full HSL package. This can be confirmed by the build log as copied in the end. However, when I run applications compiled against Ipopt, which is compiled against the full HSL package, it always says "ma27" is used, as following:
```
This is Ipopt version 3.13.1, running with linear solver ma27.
```
Is this the expected behavior? I would have expected that better solvers would be used since they are available. Or there is something wrong with my configuration. Thanks!

```
checking for MC19... yes                                                                                           
checking for MA27... yes                                                                                           
checking for MA28... yes                                                                                           
checking for MA57... yes                                                                                           
checking for MA77... yes                                                                                           
checking for MA86... yes                                                                                           
checking for MA97... yes                                                                                           
checking for deps90.f90... yes                                                                                     
checking for function dsyev_ in -lmkl_core -lmkl_intel_lp64 -lmkl_sequential -lm ... no                            
checking for function dsyev in -lmkl_core -lmkl_intel_lp64 -lmkl_sequential -lm ... no                             
checking for function DSYEV_ in -lmkl_core -lmkl_intel_lp64 -lmkl_sequential -lm ... no                            
checking for function DSYEV in -lmkl_core -lmkl_intel_lp64 -lmkl_sequential -lm ... no                             
checking for lapack.pc and blas.pc... yes                                                                          
checking for function dsyev_ in -L/usr/lib/x86_64-linux-gnu/atlas -llapack ... yes                                 
checking for package Metis... no                                                                                   
checking for gfortran option to support OpenMP... -fopenmp                                                         
checking that generated files are newer than configure... done                                                     
configure: creating ./config.status                                                                                
config.status: creating Makefile                                                                                   
config.status: creating coinhsl.pc                                                                                 
config.status: creating config.h                                                                                   
config.status: creating CoinHslConfig.h                                                                            
config.status: executing depfiles commands                                                                         
config.status: executing libtool commands                                                                          
configure: Configuration of ThirdPartyHSL successful                                                               
make  all-am                                                                                                       
make[1]: Entering directory '/path/to/ThirdParty-HSL'                                         
  F77      coinhsl/common/deps.lo                                                                                  
  F77      coinhsl/mc19/mc19d.lo                                                                                   
  F77      coinhsl/ma27/ma27d.lo                                                                                   
  F77      coinhsl/ma28/ma28d.lo                                                                                   
  F77      coinhsl/ma57/ma57d.lo                                                                                   
  FC       coinhsl/common/deps90.lo                                                                                
  FC       coinhsl/hsl_ma77/hsl_ma77d.lo                                                                           
  FC       coinhsl/hsl_ma77/C/hsl_ma77d_ciface.lo                                                                  
  FC       coinhsl/hsl_ma86/hsl_ma86d.lo
  FC       coinhsl/hsl_ma86/C/hsl_ma86d_ciface.lo
  FC       coinhsl/hsl_ma97/hsl_ma97d.lo
  FC       coinhsl/hsl_ma97/C/hsl_ma97d_ciface.lo
  CC       metis_dummy.lo
  F77LD    libcoinhsl.la
```

**Comment by svigerske** [comment]
The default is currently still to use MA27. It's impossible to say that one solver will always be better than another one and MA27 can actually outperform MA57 or others on some smaller NLPs. 
Changing the default is something on the todo list, though.
You can use option [linear_solver](https://coin-or.github.io/Ipopt/OPTIONS.html#OPT_Linear_Solver) to select a different solver.

**Comment by djwenren** [comment]
Thanks. That's the option I was looking for.

**Comment by chemrgineer** [comment]
> The default is currently still to use MA27. It's impossible to say that one solver will always be better than another one and MA27 can actually outperform MA57 or others on some smaller NLPs. Changing the default is something on the todo list, though. You can use option [linear_solver](https://coin-or.github.io/Ipopt/OPTIONS.html#OPT_Linear_Solver) to select a different solver.

Hi, I'm seaching how to change default IPOPT linear solver for compiling other solver such as SCIP 7. Because SCIP 7 dont have option to select ipopt linear solver. Sorry for replying old issue. Thanks

**Comment by svigerske** [comment]
You would need to change Ipopt code for this.
The decision on the default is done in IpAlgBuilder:
https://github.com/coin-or/Ipopt/blob/stable/3.14/src/Algorithm/IpAlgBuilder.cpp#L205-L253

For SCIP 7, if you use it via its C/C++ API, then function `SCIPsetModifiedDefaultSettingsIpopt()` could be useful:
https://www.scipopt.org/doc-7.0.3/html/group__NLPIS.php#gaf626a99a6be56ab52994fe11e6ac440f
Or you can use option `heuristics/subnlp/nlpoptfile` to specify the name of an Ipopt options file, which will be used for the majority of the NLP solves in SCIP.

With SCIP 8, this function and option were removed, though. Instead, there are options `nlpi/ipopt/optfile` and `nlpi/ipopt/linear_solver`.

**Comment by chemrgineer** [comment]
> You would need to change Ipopt code for this. The decision on the default is done in IpAlgBuilder: https://github.com/coin-or/Ipopt/blob/stable/3.14/src/Algorithm/IpAlgBuilder.cpp#L205-L253
> 
> For SCIP 7, if you use it via its C/C++ API, then function `SCIPsetModifiedDefaultSettingsIpopt()` could be useful: https://www.scipopt.org/doc-7.0.3/html/group__NLPIS.php#gaf626a99a6be56ab52994fe11e6ac440f Or you can use option `heuristics/subnlp/nlpoptfile` to specify the name of an Ipopt options file, which will be used for the majority of the NLP solves in SCIP.
> 
> With SCIP 8, this function and option were removed, though. Instead, there are options `nlpi/ipopt/optfile` and `nlpi/ipopt/linear_solver`.

This answer helped me so much. I looked SCIP 7 settings but I could not found. At the begining, I saw this option on SCIP 8 but this version not supported by pyomo yet. Thank you for your fast answer.
