### ISSUE TITLE
Configuring IPOPT and HSL with libFLAME

### ISSUE THREAD

**Issue by dphowsmon** [coin-or/Ipopt#364]
I am trying to configure IPOPT and HSL to use libFLAME/Blis for LAPACK and BLAS operations on a Linux machine with AMD processors. I've installed Blis and libFLAME using the following code:

```
git clone https://github.com/amd/blis
cd blis
./configure -t openmp --enable-threading=openmp amd64
make
make check
sudo make install
cd ../
git clone https://github.com/amd/libflame
cd libflame
./configure --enable-multithreading=openmp --enable-lapack2flame
make
sudo make install
```
This installs libraries "libblis-mt.a", "libflame.a" and "liblapacke.a" in /usr/local/lib/

I then obtained the academic version of the HSL subroutines and followed the instructions (https://coin-or.github.io/Ipopt/INSTALL.html) with

```
cd Ipopt/ThirdParty-HSL
./configure --with-lapack-lflags="-L/usr/local/lib/" --with-lapack-cflags="-I/usr/local/include/"
```

However, I get the error: "configure: error: Could not find dsyev in Lapack"

Has anyone gotten IPOPT and HSL to work with libFLAME and Blis?

**Comment by svigerske** [comment]
`--with-lapack-lflags` should be all link-flags. Maybe `--with-lapack-lflags="-L/usr/local/lib/ -llapacke"` ?

**Comment by dphowsmon** [comment]
I tried that or with `--with-lapack-lflags="-L/usr/local/lib/ -llapacke -llibflame"` but it still can't find dsyev in Lapack

**Comment by svigerske** [comment]
And what does config.log says why it failed to link? Maybe some dependencies on your Lapack libs are missing. `-fopenmp` ?

**Comment by dphowsmon** [comment]
OK, after recompiling libFLAME with `--enable-dynamic-build` and configuring HSL with:
`./configure CXXFLAGS=-openmp FCFLAGS=-fopenmp --with-lapack-lflags="-L/usr/local/lib -lflame -lblis-mt -lm" --with-lapack-cflags="-I/usr/local/include/" --with-metis="-L/usr/local/lib -lcoinmetis"`
I got this to work.
