### ISSUE TITLE
problem with CSSLIBS variable in mingw

### ISSUE THREAD

**Issue by Timbersaw-wangzw** [coin-or/Ipopt#365]
I have read the document about how to change the CXXLIBS variable in Linux. I tried to imitate it in Windows.but failed. here is my code  ./configure CXX=g++ CC=gcc F77=gfortran CXXLIBS='-L/usr/lib/gcc/x86_64-w64-mingw32/9.2.0/-lstdc++'  
can you tell me how to write this code?

**Comment by svigerske** [comment]
Put a space in front of `-lstdc++`.
