### ISSUE TITLE
problem with CXXLIBS variable in mingw

### ISSUE THREAD

**Issue by Timbersaw-wangzw** [coin-or/Ipopt#366]
Sorry to bother you again.I asked this problem before but your solution didn't work. I don't have the folder usr/lib/gcc-lib/ which is mentioned in the document. I found a similar path which is var\lib\pacman\local\mingw-w64-i686-gcc-libs-9.2.0. There are 'desc' 'files' 'mtree' in the folder.However it did't work. So what is the true path? what are the specific files th the true folder?and what's the true code?Thanks a lot!

**Comment by svigerske** [comment]
You might want the path to some libstdc++ file, probably `libstdc++.lib`.

I cannot say whether you actually need to overwrite CXXLIBS and what it should be, as I cannot look into your machine and don't know how you build Ipopt or what you try to achieve at all.

**Comment by Timbersaw-wangzw** [comment]
My machine is window x64 and using mingw x64 to compile. my install procedure is followed by the document step by step. And&nbsp;I want to build IPOPT in C++ and generate .lib files. but it generates the .a files instead.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Stefan Vigerske"<notifications@github.com&gt;; 
发送时间: 2020年2月25日(星期二) 晚上8:44
收件人: "coin-or/Ipopt"<Ipopt@noreply.github.com&gt;; 
抄送: "王子玮-两机"<515708372@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [coin-or/Ipopt] problem with CXXLIBS variable in mingw (#366)




You might want the path to some libstdc++ file, probably libstdc++.lib.
 
I cannot say whether you actually need to overwrite CXXLIBS and what it should be, as I cannot look into your machine and don't know how you build Ipopt or what you try to achieve at all.

**Comment by svigerske** [comment]
And you are sure you use a current Ipopt version (3.13.x) ?

**Comment by Timbersaw-wangzw** [comment]
My version is 3.12.1.Is there a difference?

**Comment by svigerske** [comment]
Yes: https://coin-or.github.io/Ipopt/CHANGELOG.html

One maybe change is an update to the build system. The documentation on https://coin-or.github.io/Ipopt is for Ipopt 3.13.
