### ISSUE TITLE
Error when building Ipopt with coinbrew

### ISSUE THREAD

**Issue by kibaekkim** [coin-or/Ipopt#375]
It seems `metis.h` is missing.

```
##################################################
### Building ThirdParty/Mumps 2.1
##################################################

/homes/kibaekkim/software/Ipopt/ThirdParty/Mumps/metis_adapter.c:6:10: fatal error: metis.h: No such file or directory
    6 | #include "metis.h"
      |          ^~~~~~~~~
compilation terminated.
make[1]: *** [metis_adapter.lo] Error 1
make: *** [all] Error 2

Build failed, see error output above
```

**Comment by kibaekkim** [comment]
Thanks @svigerske for the quick response! That works for compiling mumps. Now I got this error from building ipopt:
```
##################################################
### Building Ipopt master
##################################################

javac: invalid flag: -h
Usage: javac <options> <source files>
use -help for a list of possible options
make[1]: *** [org_coinor_Ipopt.h] Error 2
make: *** [all-recursive] Error 1

Build failed, see error output above
```

**Comment by svigerske** [comment]
How old is your java compiler? What does
```
javac -version
```
say?

**Comment by kibaekkim** [comment]
It's `javac 1.7.0_201`.

**Comment by svigerske** [comment]
I think that's out-of-support nowadays.
javac from JDK >= 1.8 should support -h.

You can workaround with `--disable-java`, as you've probably read [in the documentation](https://coin-or.github.io/Ipopt/INSTALL.html#CONFIGURE_FLAGS). If you need the Ipopt Java interface, then I would strongly advice to update your Java installation.

Maybe I'll add some check in configure some day.
