### ISSUE TITLE
Precompiled binaries

### ISSUE THREAD

**Issue by dpo** [coin-or/Ipopt#377]
Hi all,

I wanted to mention that a flurry of new precompiled binaries are made available as part of the Yggdrasil effort (related to Julia, but those binaries can technically be used without Julia).

Here is the "formula" that builds IPOPT for a variety of platforms: https://github.com/JuliaPackaging/Yggdrasil/blob/master/I/Ipopt/build_tarballs.jl

Here are the binary releases: https://github.com/JuliaBinaryWrappers/Ipopt_jll.jl/releases/tag/Ipopt-v3.13.2%2B0

The IPOPT README points to JuliaOpt for binaries but as far as I can tell, they are outdated.

I'll take the opportunity to ask whether anyone here has any guidance on how to build IPOPT for Windows using MinGW and Intel's MKL. Linking with the MKL has been particularly contrary. Here's my pull request in case anyone can chime in: https://github.com/JuliaPackaging/Yggdrasil/pull/1031

If we can get that to build, then those binaries will be available as well.

Cheers!

**Comment by svigerske** [comment]
OK, we can update the link in the readme.

configure should pick up MKL libraries automatically, if found in `$LIB`, but it is looking for the sequential version (https://github.com/coin-or/Ipopt/blob/master/configure#L22521).

There is one precompiled DLL of Ipopt with MKL for Windows at https://github.com/coin-or/Ipopt/releases/download/releases%2F3.13.2/Ipopt-3.13.2-win64-msvs2019-md.zip Maybe you can make some use of that?
