### ISSUE TITLE
install-sh: Permission denied

### ISSUE THREAD

**Issue by LyuJZ** [coin-or/Ipopt#383]
# when I run 'suo make install', I got some errors as this:
/bin/bash /Ipopt/install-sh -c -m 644 config_ipopt.h /usr/local/include/coin-or/IpoptConfig.h
/bin/bash: /Ipopt/install-sh: Permission denied
Makefile:745: recipe for target 'install-exec-local' failed
make[2]: *** [install-exec-local] Error 126
make[2]: Leaving directory '/Ipopt/src/Common'
Makefile:616: recipe for target 'install-am' failed
make[1]: *** [install-am] Error 2
make[1]: Leaving directory '/Ipopt/src/Common'
Makefile:623: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1

**Comment by svigerske** [comment]
Looks like execute permissions are missing on `install-sh`.

The [file in the git repo](https://github.com/coin-or/Ipopt/blob/master/install-sh) has the executable flag set and so it should be in the tarball.
If it got lost somehow, then maybe try putting it back:
```
chmod +x /Ipopt/install-sh
```
