### ISSUE TITLE
Problem with string coding passing options from c++17 compiled software

### ISSUE THREAD

**Issue by mottelet** [coin-or/Ipopt#384]
Hi, I am currently porting the old Scilab Iptop interface. The actual version of Scilab (6.1) is compiled with c++17 standard I don't know if this is the source of the problem: there seems to be a problem with string handling when passing options. In my test program I have the following piece of code:

    ipopt_app->Options()->SetStringValue("hessian_approximation", "limited-memory");

which gives the following error:

Tried to set Option: .??Tried to set Option: ??

Do you have an idea ?  I use Ipopt 3.13.2 version, compiled from source on OSX Mojave with gcc/g++/gfortran 8.3 (same set of compilers for Scilab 6.1) and CXXFLAGS=-std=c++17.

Thanks for your help.

**Comment by svigerske** [comment]
Not really. A wild guess is that GCCs `-stdlib` option or `_GLIBCXX_DEBUG` define were not used consistently.

Maybe post the exact compiler call that was used when Ipopt was compiled (in particular IpOptionsList.cpp, run make with `V=1`) and the calls used to compile and link your code that works with Ipopt.

**Comment by mottelet** [comment]
> Not really. A wild guess is that GCCs `-stdlib` option or `_GLIBCXX_DEBUG` define were not used consistently.
> 
> Maybe post the exact compiler call that was used when Ipopt was compiled (in particular IpOptionsList.cpp, run make with `V=1`) and the calls used to compile and link your code that works with Ipopt.

I have no problem with previous version of Scilab 6.0.2 OSX (compiled with clang since c++17 was not needed at this time). Now we need c++17 for Sciab 6.1. 

The compilation of IpOptionsList.cpp is done like this:

`libtool: compile:  g++ -DHAVE_CONFIG_H -I. -DIPOPTLIB_BUILD -std=c++17 -MT IpOptionsList.lo -MD -MP -MF .deps/IpOptionsList.Tpo -c IpOptionsList.cpp  -fno-common -DPIC -o IpOptionsList.o`

Scilab is compiled with:

```
Options used to compile and link:
  prefix ......... = /usr/local
  localedir ...... = ${datarootdir}/locale
  VERSION ........ = 6
  CC ............. = gcc-fsf-8 -arch x86_64
  CFLAGS ......... = -g -O2
  SCI_CFLAGS ..... = -DNDEBUG -g1 -O2 -fno-stack-protector
  DEFS ........... = -DHAVE_CONFIG_H
  LD ............. = /usr/bin/ld
  LDFLAGS ........ = -L/sw/lib/gcc8/lib/ -L/sw//lib/
  SCI_LDFLAGS .... = 
  LIBS ........... = -ldl -lcurses -lstdc++fs 
  CXX ............ = g++-fsf-8 -arch x86_64 -std=c++17
  CXXFLAGS ....... = 
  SCI_CXXFLAGS ... = -DNDEBUG -g1 -O2 -fno-stack-protector
  F77 ............ = gfortran-fsf-8
  FFLAGS ......... = 
  SCI_FFLAGS ..... = -DNDEBUG -g1 -O2
  F77_LDFLAGS .... = 
  FLIBS...... .... =  -L/sw/lib/gcc8/lib/ -L/sw//lib/ -L/sw/lib/gcc8/lib/gcc/x86_64-apple-darwin18.6.0/8.3.0 -L/sw/lib/gcc8/lib/gcc/x86_64-apple-darwin18.6.0/8.3.0/../../.. -lcurses -lstdc++fs -lgfortran -lquadmath -lm
  TERMCAP_LIB .... = no
```

and the the interface with Ipopt is built with:

 ```
  Output: Options used to compile and link:
   Output:   CC               =  gcc -arch x86_64 
   Output:   CFLAGS           =   -D__SCILAB_TOOLBOX__ -std=c++17 -I/Users/mottelet/scilab/DEV/sci-ipopt-6.1/sci_gateway/cpp/../../thirdparty/Darwin/ipopt/include/coin -I/sw/include 
   Output:   CPP              = gcc -E
   Output:   CPPFLAGS         =   -I/sw/include 
   Output:   PCFLAGS          = 
   Output:   DEFS             = -DPACKAGE_NAME=\"scilab\" -DPACKAGE_TARNAME=\"scilab\" -DPACKAGE_VERSION=\"0\" -DPACKAGE_STRING=\"scilab\ 0\" -DPACKAGE_BUGREPORT=\"http://bugzilla.scilab.org/\" -DPACKAGE_URL=\"\" -DPACKAGE=\"scilab\" -DVERSION=\"0\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\"
   Output:   LD               = /usr/bin/ld
   Output:   LDFLAGS          =   -L/sw/lib/ 
   Output:   LIBS             = 
   Output:   CXX              =  g++ -arch x86_64 
   Output:   CXXFLAGS         =  -D__SCILAB_TOOLBOX__ -std=c++17 -I/Users/mottelet/scilab/DEV/sci-ipopt-6.1/sci_gateway/cpp/../../thirdparty/Darwin/ipopt/include/coin
   Output:   F77              = gfortran
   Output:   FFLAGS           = -g -O2
   Output:   FLIBS            =  -L/sw/lib/gcc8/lib/gcc/x86_64-apple-darwin18.6.0/8.3.0 -L/sw/lib/gcc8/lib/gcc/x86_64-apple-darwin18.6.0/8.3.0/../../.. -lgfortran -lquadmath -lm
   Output:   FC               = gfortran
   Output:   FFLAGS           = -g -O2
   Output:   FCLIBS           =  -L/sw/lib/gcc8/lib/gcc/x86_64-apple-darwin18.6.0/8.3.0 -L/sw/lib/gcc8/lib/gcc/x86_64-apple-darwin18.6.0/8.3.0/../../.. -lgfortran -lquadmath -lm
```

**Comment by svigerske** [comment]
And you are sure that the Ipopt headers were installed in `/Users/mottelet/scilab/DEV/sci-ipopt-6.1/sci_gateway/cpp/../../thirdparty/Darwin/ipopt/include/coin` and not `/Users/mottelet/scilab/DEV/sci-ipopt-6.1/sci_gateway/cpp/../../thirdparty/Darwin/ipopt/include/coin-or`?

**Comment by mottelet** [comment]
Thank you for the hit (I used 3.11.7 before). I restarted from scratch and built with coinbrew and now everything work, but I have a last question: can coinbrew install METIS in addition of MUMPS ?

**Comment by svigerske** [comment]
No, coinbrew only installs dependencies that use the COIN-OR buildsystem.
