### ISSUE TITLE
/get.Metis   ：failed：Connection refused

### ISSUE THREAD

**Issue by sxxa-qlp** [coin-or/Ipopt#386]
**Thank you for your contribution!**
according to **How to install Ipopt on x86 environment  file**,
`_Step by step --->$ ./get.Metis  ---->_
Running script for downloading the source code for the METIS
 
Downloading the source code from glaros.dtc.umn.edu...
--2020-07-18 10:54:12--  http://glaros.dtc.umn.edu/gkhome/fetch/sw/metis/OLD/metis-4.0.3.tar.gz
正在解析主机 glaros.dtc.umn.edu (glaros.dtc.umn.edu)... 160.94.40.33
正在连接 glaros.dtc.umn.edu (glaros.dtc.umn.edu)|160.94.40.33|:80... 失败：拒绝连接。`

I don't know does the host  glaros.dtc.umn.edu (glaros.dtc.umn.edu)... 160.94.40.33 works?  
Looking forward to your reply.

**Comment by svigerske** [comment]
There are probably just offline temporarily. You can get the tarball also from http://coin-or-tools.github.io/ThirdParty-Metis/metis-4.0.3.tar.gz

**Comment by tkralphs** [comment]
Shouldn't the script revert to downloading from COIN-OR automatically if the download from umn.edu fails? I thought that was the reason we posted a backup tarball.

**Comment by svigerske** [comment]
Yes, kind of. The latest release would first try GitHub and then go to the umn.edu page: https://github.com/coin-or-tools/ThirdParty-Metis/blob/releases/1.3.9/get.Metis

But they seem to use some old release.

**Comment by tkralphs** [comment]
By "they," you mean @sxxa-qlp? So I guess for posterity, the solution is just to use a later version of `get.Metis`.

**Comment by svigerske** [comment]
Yes, those who created the issue.
I don't ask people anymore why they use outdated versions.
