### ISSUE TITLE
fatal error: mumps_mpi.h: No such file or directory

### ISSUE THREAD

**Issue by sxxa-qlp** [coin-or/Ipopt#387]
**Thanks for your reply！**
I download and untar the package in '/Metis' folder , ran `../configure` command  successfully,
When I ran `make -j4 ` command , it occurs 

`../../../../../Ipopt/src/Algorithm/LinearSolvers/IpMumpsSolverInterface.cpp:20:23: fatal error: mumps_mpi.h: No such file or directory
compilation terminated.
Makefile:569: recipe for target 'IpMumpsSolverInterface.lo' failed
`

**Comment by svigerske** [comment]
Maybe something went wrong in ThirdParty-Mumps. The `get.Mumps` script should have replaced mpi.h by mumps_mpi.h and applied some patches to the Mumps source:
```
patch -p0 < mumps.patch
patch -p0 < mumps_mpi.patch
mv MUMPS/libseq/mpi.h MUMPS/libseq/mumps_mpi.h
```
