### ISSUE TITLE
change sparsity structure during optimization

### ISSUE THREAD

**Issue by Janos95** [coin-or/Ipopt#388]
Is it possible to change the sparsity structure of the hessian during optimization? I could not find anything in the docs related to this issue. In my optimization problem the hessian is usually very dense (supported along a path on a triangle mesh) but any entry in the hessian could potentially be nonzero.

**Comment by svigerske** [comment]
No, Ipopt allocates its datastructures according to the initially specified Hessian structure and assumes that this will not change during the optimization process.

**Comment by Janos95** [comment]
I see. How deep is this assumption entangled with the architecture of ipopt? Is this repository accepting contributions?

**Comment by svigerske** [comment]
I cannot say for sure how deep (I'm not a main author of Ipopt code). Ipopt assumes that it can just copy over the new values for the Hessian into its internal datastructures without having to adapt to new nonzero patterns. But if its the Hessian only, maybe not everything would need to be changed.
Contributions are always welcomed.
