### ISSUE TITLE
ipopt crash in deploy matlab code

### ISSUE THREAD

**Issue by P705** [coin-or/Ipopt#390]
Hi
I have a code that uses ipopt mex for optimization. I deploy this code to use on .net.
But mex file does not run and the .net program crash without any error. I use matlab 2015b for deploying the code and vs 2015 for .net program.
how can handle this crashing in the dll?

**Comment by svigerske** [comment]
We don't do anything with mex or .net here.
If you use the MEX interface from https://github.com/ebertolazzi/mexIPOPT, then you might want to check there.
If you use the C# interface from https://github.com/cureos/csipopt, then you might want to check there.
In both cases, they would need much more information, preferably a way to reproduce the problem.
