### ISSUE TITLE
Error building Ipopt on macOS Catalina

### ISSUE THREAD

**Issue by Kvmontan** [coin-or/Ipopt#392]
I am following the documentation on https://coin-or.github.io/Ipopt/INSTALL.html

I have tried both compiling and installing Ipopt, and using CoinBrew. Both options give the same error. I am able to configure the Ipopt but when building the code using "make" I obtain the following:

clang: error: unsupported option '-fopenmp'
make[2]: *** [libipopt.la] Error 1
make[1]: *** [all] Error 2
make: *** [all-recursive] Error 1

I have attached the terminal when using the first option of compiling and installing Ipopt. What should I do? I already completed all the steps (getting HSL, and when using coinbrew, getting Mumps).

Thank you in advance,

Karen Montano

**Comment by svigerske** [comment]
I don't see anything attached, but suspect that ThirdParty-HSL detected that OpenMP via `-fopenmp` is available when using the Fortran compiler, then this flag is passed on as linker flag, but is not understood by your C/C++ compiler.

I'm not sure how well mixing GNU Fortran with clang will work, so you may want to use GNU compilers for everything.

Otherwise, try adding `--disable-openmp` to the CoinBrew call.

**Comment by Kvmontan** [comment]
[terminal_info.txt](https://github.com/coin-or/Ipopt/files/5104280/terminal_info.txt)

**Comment by svigerske** [comment]
And `gcc` and `g++` are the GCC from `/usr/local/Cellar/gcc/10.2.0/`, or are these aliases for clang?

**Comment by Kvmontan** [comment]
In Apple’s version of GCC, both cc and gcc are actually symbolic links to the llvm-gcc compiler. Similarly, c++ and g++ are links to llvm-g++. I already have them installed:

(base) kvmontan@Karens-MBP ~ % gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 11.0.3 (clang-1103.0.32.62)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
(base) kvmontan@Karens-MBP ~ % whereis gcc
/usr/bin/gcc
(base) kvmontan@Karens-MBP ~ % whereis make
/usr/bin/make
(base) kvmontan@Karens-MBP ~ % 

but I am having problem about how to use them during the configure step.

**Comment by Kvmontan** [comment]
I tried using GNUmake instead of make and I am having the same error:

clang: error: unsupported option '-fopenmp'
gnumake[2]: *** [libipopt.la] Error 1
gnumake[1]: *** [all] Error 2
gnumake: *** [all-recursive] Error 1
(base) kvmontan@Karens-MBP build %

**Comment by svigerske** [comment]
As said, try to either use the GNU compilers (instead of clang) or disable the use of OpenMP.
