### ISSUE TITLE
Error in restoration phase

### ISSUE THREAD

**Issue by debottam123** [coin-or/Ipopt#394]
Whenever I try to run a code using ipopt solver in matlab through yalmip I face an issue - "Restoration phase is called at point that is almost feasible" . Following this issue is a number of range e-13 to e-14..How to solve this issue and get optimal solutions?do I need to modify any options in the solver?

**Comment by svigerske** [comment]
This issue can come up when Ipopt fails to find an improving step at the current iterate.
As described in Section 2.3 of [the implementation paper](http://www.optimization-online.org/DB_HTML/2004/03/836.html), one fallback is to start the feasibility restoration phase. However, if the current iterate is already primal feasible, then there is no feasibility to restore - that's what the message tries to say. So there are no more fallbacks and Ipopt aborts.

It is difficult to say why this issue would come up. The documentation says
> This indicates that the restoration phase failed to find a feasible point that was acceptable to the filter line search for the original problem. This could happen if the problem is highly degenerate, does not satisfy the constraint qualification, or if your NLP code provides incorrect derivative information.

So you might want to check your problem formulation, including scaling, and ensure that first- and second-order derivatives are correct (I don't know how that is done in yalmip).
