### ISSUE TITLE
make test fails for examples/hs071_cpp

### ISSUE THREAD

**Issue by renjiefly** [coin-or/Ipopt#395]
Hi, I am using the latest Ipopt 3.13.3 on Ubuntu 18.04 and followed the install instruction from [https://coin-or.github.io/Ipopt/INSTALL.html](url). Everything went well (install dependencies like HSL and MUMPS using ThirdParty-HSL and ThirdParty-Mumps, etc. BTW, I am using HSL Archive so ma57 is not included) until I ran
 `make test` in my `$IPOPTDIR`. The error message is like this:

>... 
make[1]: Leaving directory '/home/renjie/codes/Ipopt'
cd test; make test
make[1]: Entering directory '/home/renjie/codes/Ipopt/test'
  CXXLD    hs071_cpp
../src/Interfaces/.libs/libipopt.so: undefined reference to `ma57ed_'
../src/Interfaces/.libs/libipopt.so: undefined reference to `ma57cd_'
../src/Interfaces/.libs/libipopt.so: undefined reference to `ma57ad_'
../src/Interfaces/.libs/libipopt.so: undefined reference to `ma57id_'
../src/Interfaces/.libs/libipopt.so: undefined reference to `ma57bd_'
collect2: error: ld returned 1 exit status
Makefile:488: recipe for target 'hs071_cpp' failed
make[1]: *** [hs071_cpp] Error 1
make[1]: Leaving directory '/home/renjie/codes/Ipopt/test'
Makefile:852: recipe for target 'unitTest' failed
make: *** [unitTest] Error 2

The thing confuses me is that the default linear-solver is ma27, why the compiler would try to find 'ma57xx' when compiling the example. Here is my [config.log](https://github.com/coin-or/Ipopt/files/5116780/config.log). Would be grateful if anyone can help.

**Comment by svigerske** [comment]
I have some idea what might be the problem.
Try using `--disable-linear-solver-loader` for Ipopt's configure to work around that.

**Comment by renjiefly** [comment]
> I have some idea what might be the problem.
> Try using `--disable-linear-solver-loader` for Ipopt's configure to work around that.

@svigerske Thanks for your extremetely quick reply! The `--disable-linear-solver-loader` option indeed solves the problem. So what do you think the problem is?

**Comment by svigerske** [comment]
The MA57 interface assumes that the MA57 functions will be named with underscore (e.g., ma57ed_), because that's how the other HSL functions in your HSL lib are named, but the linear solver loader defines the MA57 functions without underscore (e.g., ma57ed). Only if no HSL is around at all, then the MA57 interface will use the same name convention as the linear solver loader. And if the linear solver loader is disabled and MA57 is not available, then the MA57 interface doesn't get build at all (which is what you get now).

**Comment by renjiefly** [comment]
> The MA57 interface assumes that the MA57 functions will be named with underscore (e.g., ma57ed_), because that's how the other HSL functions in your HSL lib are named, but the linear solver loader defines the MA57 functions without underscore (e.g., ma57ed). Only if no HSL is around at all, then the MA57 interface will use the same name convention as the linear solver loader. And if the linear solver loader is disabled and MA57 is not available, then the MA57 interface doesn't get build at all (which is what you get now).

So is this some potential bug regarding the linear solver loader? I'm afraind someone else would run into the same problem if they also use HSL Archive.

**Comment by svigerske** [comment]
yes, that's something that should be fixed; that's why the issue is still open :)
