### ISSUE TITLE
Installation in Nvidia Pegasus

### ISSUE THREAD

**Issue by vimalrajayyappan** [coin-or/Ipopt#399]
Dear Team.

Thanks a lot for this awesome Library. I would like to know it's compatibility in ARM based processor like Nvidia Pegasus.
Since Ipopt be using MKL which is proprietary to Intel.

Thanks. 😊

**Comment by svigerske** [comment]
Ipopt doesn't have to use MKL, it needs _some_ implementation of BLAS and LAPACK.

So, in general, it should work on ARM CPUs as well, but this hasn't been tested for a while and so there could be problems.
