### ISSUE TITLE
What if I don't use box constraint but put it into function constraint?

### ISSUE THREAD

**Issue by renjiefly** [coin-or/Ipopt#400]
Say I have a 2-dimension problem with the constraint 1 <= x0 <= 2 and 3 <= x0+x1 <= 4. The usual way to implement the constraints following the guide is to impose 1 <= x0 < = 2 as a box constraint and impose 3 <= x0+x1 <= 4 as a function constraint by:
in `get_nlp_info`
```
... 
n = 2;
m = 1; 
...
```
in `get_bounds_info`
```
... 
x_l[0] = 1; 
x_u[0] = 2; 
x_l[1] = -2e19; 
x_u[1] = 2e19; 
g_l[0] = 3; 
g_u[0] = 4; 
...
```
in `eval_g`
```
... 
g[0] = x[0] + x[1]; 
...
```
Instead, we can also impose the two constraints all as function constraints by:
in `get_nlp_info`
```
...
n = 2;
m = 2;
...
```
in `get_bounds_info`
```
...
x_l[0] = -2e19;
x_u[0] = 2e19;
x_l[1] = -2e19;
x_u[1] = 2e19;
g_l[0] = 1;
g_u[0] = 2;
g_l[1] = 3;
g_u[1] = 4;
...
```
in `eval_g`
```
...
g[0] = x[0];
g[1] = x[0] + x[1];
...
```
What will be the difference between the two approaches? Thanks.

**Comment by svigerske** [comment]
Variable bounds are always satisfied by all iterates (apart from the small relaxation of bounds that can happen, see option bound_relax_factor), but constraints may be violated.
It is usually better do specify variable bounds as bounds, in particular if some functions cannot be evaluated or differentiated outside the box.

**Comment by renjiefly** [comment]
@svigerske Hi, Stefan, thanks for your answer. Can I interprete your answer like this:
1) variable bounds should always be satified in all iterates, so the user-provided starting point must satifiy the variable bounds as well
2) the final solution must satisfy the variable bounds but may violate the constraints.
3) in terms of computational efficiency and solution accuracy, there is no difference to impose a box constraint as a variable bound or a constraint if the problem is feasible.
Look forward to your reply. Thanks.

**Comment by svigerske** [comment]
1. yes
2. yes; but if Ipopt stops with a feasible point, then constraints should also be satisfied (w.r.t. tolerances)
3. in general, box constraints are computationally more efficient

**Comment by renjiefly** [comment]
> 1. yes
> 2. yes; but if Ipopt stops with a feasible point, then constraints should also be satisfied (w.r.t. tolerances)
> 3. in general, box constraints are computationally more efficient

@svigerske Thank you Stefan!
