### ISSUE TITLE
/dev/stdout output despite journal used

### ISSUE THREAD

**Issue by mottelet** [coin-or/Ipopt#401]
Hello,

I use a journal which redirects Ipopt (3.13.2) output to the Scilab console (see class below)
 
     ScilabJournal::ScilabJournal (EJournalLevel default_level) : Journal("scilab", default_level) { }
     void ScilabJournal::PrintImpl (EJournalCategory category, EJournalLevel level, const char* str) 
     {
       sciprint((char *)str);
     }
     void ScilabJournal::PrintfImpl (EJournalCategory category, EJournalLevel level, const char* pformat, va_list ap) 
     {
      const int maxStrLen = 1024;
      char      s[maxStrLen];
      if (vsnprintf(s,maxStrLen,pformat,ap) >= maxStrLen)
       throw ScilabException("String buffer it too short for all the characters to be printed to Scilab console");
      sciprint(s);
     }

then add it in my gateway like this:

    SmartPtr<Journal> console = new ScilabJournal((EJournalLevel)iPrintLevel);
    ipopt_app->Jnlst()->AddJournal(console);

Regardless the chosen print level, I still have Ipopt output on /dev/stdout (in addition to the Scliab output). How can I fix this ?

Thanks for help

**Comment by svigerske** [comment]
You should pass `false` to the [IpoptApplication constructor](https://coin-or.github.io/Ipopt/classIpopt_1_1IpoptApplication.html#a9eb44ee6ce920890170f63317ffacabf). That will omit the original console journal.

**Comment by mottelet** [comment]
Thanks !
