### ISSUE TITLE
Force feasible iterates

### ISSUE THREAD

**Issue by mottelet** [coin-or/Ipopt#404]
Maybe the question is dumb, but is it possible to force feasible iterates ? In many applications, f(x) just can't be evaluated when x is not feasible.

**Comment by svigerske** [comment]
No, Ipopt reduces infeasibility and improves objective function value simultaneously and only variable bounds are satisfied by all iterates.

Option "start_with_resto" (https://coin-or.github.io/Ipopt/OPTIONS.html#OPT_Restoration_Phase) may be useful to make Ipopt focus on reducing only infeasibility in the beginning.
