### ISSUE TITLE
Getting overall NLP error in intermediate callback

### ISSUE THREAD

**Issue by mottelet** [coin-or/Ipopt#405]
Is there a way to get the overall NLP error in intermediate callback, or at least a simple way to compute it by using the accessible quantities ?

**Comment by svigerske** [comment]
You can get a lot from the `IpoptCalculatedQuantities` object that is passed to the intermediate callback: https://coin-or.github.io/Ipopt/classIpopt_1_1IpoptCalculatedQuantities.html, including `curr_nlp_error()`.

**Comment by mottelet** [comment]
Oh I see. Thanks a lot.
