### ISSUE TITLE
Ipopt with Pardiso on Mac

### ISSUE THREAD

**Issue by ryanstoner1** [coin-or/Ipopt#406]
Hi All,

I was trying to install Ipopt with the 6.0.0 version of Pardiso using `./configure --with-pardiso="$HOME/pardiso/libpardiso.dylib"` similarly to #341 . The configuration is successful. However, `make` fails with the error:
```
Undefined symbols for architecture x86_64:
  "_pardiso_", referenced from:
      Ipopt::PardisoSolverInterface::~PardisoSolverInterface() in liblinsolvers.a(IpPardisoSolverInterface.o)
      Ipopt::PardisoSolverInterface::InitializeImpl(Ipopt::OptionsList const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in liblinsolvers.a(IpPardisoSolverInterface.o)
      Ipopt::PardisoSolverInterface::Factorization(int const*, int const*, bool, int) in liblinsolvers.a(IpPardisoSolverInterface.o)
      Ipopt::PardisoSolverInterface::Solve(int const*, int const*, int, double*) in liblinsolvers.a(IpPardisoSolverInterface.o)
  "_pardisoinit_", referenced from:
      Ipopt::PardisoSolverInterface::InitializeImpl(Ipopt::OptionsList const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in liblinsolvers.a(IpPardisoSolverInterface.o)
ld: symbol(s) not found for architecture x86_64
```

There's an array of other errors (see config.log attached bellow) . . . for example, it seems that sometimes header files are not being seen. gfortran seems to be being called from gcc, but g++ is from clang/llvm. Not sure if those would conflict.

I double checked that libpardiso.dylib is in the given path.

[config.log](https://github.com/coin-or/Ipopt/files/5294457/config.log)

**Comment by svigerske** [comment]
Somehow the Pardiso interface looks for `_pardiso_` instead of `pardiso_`.
I don't really understand why that would happen. In the interface, we have
```c
extern "C" {
...
   void IPOPT_PARDISO_FUNC(pardiso, PARDISO)(
      void**        PT,
      const ipfint* MAXFCT,
      const ipfint* MNUM,
      const ipfint* MTYPE,
      const ipfint* PHASE,
      const ipfint* N,
      const double* A,
      const ipfint* IA,
      const ipfint* JA,
      const ipfint* PERM,
      const ipfint* NRHS,
      ipfint*       IPARM,
      const ipfint* MSGLVL,
      double*       B,
      double*       X,
      ipfint*       ERROR,
      double*       DPARM
   );
...
}
```
and from your config.log, I see
```c
#define IPOPT_PARDISO_FUNC(name,NAME) name ## _
#define IPOPT_PARDISO_FUNC_(name,NAME) name ## _
```
So nothing that adds an underscore before the function name.   
Maybe that is due to mixing GCC with clang. You want to avoid such a conflict and use GCC for all languages.

configure tests capability of your system, including availability of some header files. It is ok if some of these checks fail.

**Comment by ryanstoner1** [comment]
Great, that helped. I added flags for the individual compilers. Running `make test` was giving errors about not seeing libmkl in `make test`, so adding that path was also needed for `make` to run without errors. So I was running:

`../configure CXX=g++-8 CC=gcc-8 FC=gfortran-8 F77=gfortran-8 --with-pardiso="$HOME/pardiso/libpardiso.dylib" LDFLAGS="-Wl,-rpath,$MKLROOT/../compiler/lib -Wl,-rpath,$MKLROOT/lib"`

 Although `make` in this scenario succeeds I'm running into a bit of unusual behavior because `make test` was [causing segfaults](https://gist.github.com/ryanstoner1/5f9ff1d139ea4c0a20df93f55de7f393). Adding the flag `--enable-debug`, i.e. `./configure CXX=g++-8 CC=gcc-8 FC=gfortran-8 F77=gfortran-8 --enable-debug --with-pardiso="$HOME/pardiso/libpardiso.dylib" LDFLAGS="-Wl,-rpath,$MKLROOT/../compiler/lib -Wl,-rpath,$MKLROOT/lib"`, for some reason causes all tests to pass with the exception of the AMPL solver executable ([here](https://gist.github.com/ryanstoner1/c8ee016d626d2fad0f707928d4abb471)).

Attaching the logs again for the semi-successful (debug) case and unsuccessful (no-debug) cases, respectively. 
[config.log](https://github.com/coin-or/Ipopt/files/5303832/config.log)

[config_nodebug.log](https://github.com/coin-or/Ipopt/files/5303983/config_nodebug.log)

**Comment by svigerske** [comment]
So now you add MKL into the mix as well. Can you try without that first. Ipopt's configure should then pickup the Accelerate framework for LAPACK.

A potential problem with MKL could be that it also brings a version of Pardiso. It uses the same function name, but different arguments (https://list.coin-or.org/pipermail/ipopt/2020-August/004772.html). configure concluded in your case that Ipopt will use Pardiso from www.pardiso-project.org, but I'm not sure how to be sure what the linker will choose.

**Comment by svigerske** [comment]
Closing as no reply.
