### ISSUE TITLE
Requirement guide for faster computation/ increasing the frequency of solver

### ISSUE THREAD

**Issue by vimalrajayyappan** [coin-or/Ipopt#407]
Hi Team,

Im requesting you to know what will be the desired requirement of hardware for accelerating the process. 

I'm using 8 CORE Intel - i5 system at clock cycle of 1.6GHZ
And 16Gigs of RAM. 
IPOPT is solving at 2Hz

Im adding 8 constraints
And around 10 types of cost 
Running at 40 iterations Per cycle.

Kindly guide me through what should I do to increase the frequency! Thanks a lot

**Comment by svigerske** [comment]
Sorry, that goes beyond my expertise.

Ipopt is rather meant for large-scale optimization. It may not a good choice to solve really tiny problems really fast.
