### ISSUE TITLE
laodLib error

### ISSUE THREAD

**Issue by m-khansari** [coin-or/Ipopt#408]
Hello 
I am using the precompile IPOPT libraries and when I want to change my solver from "mumps" to "ma57" I get this error:

![image](https://user-images.githubusercontent.com/39255756/95342981-db40c780-08c4-11eb-9d55-05338463a74b.png)

I have built the libhsl.dll library and I have also add its directory to system PATH, but I still get this error....

any Idea on how to fix it ?

**Comment by svigerske** [comment]
It's strange that there are two dots in the name (`libhsl..dll`). I don't see how this could happen.

Just to confirm, "the precompile IPOPT libraries" are the one from https://github.com/coin-or/Ipopt/releases/tag/releases%2F3.13.2 ?

**Comment by m-khansari** [comment]
No I am using: https://github.com/cureos/csipopt
my code in C#...

**Comment by svigerske** [comment]
And their README points to http://www.coin-or.org/download/binary/Ipopt/Ipopt-3.11.0-Win32-Win64-dll.7z. I don't even remember who build that 7 years ago, but if that is the one you use, then it looks like it has been build in a way that the code that loads DLLs at runtime doesn't work.

**Comment by m-khansari** [comment]
I will try to build it using the link you provided!!!
Thanks!!!

**Comment by m-khansari** [comment]
How should I make the C# dll with the files you provided?
Can you help me with that ?

**Comment by svigerske** [comment]
No, I don't know C#. Maybe the csipopt developers know how to adjust their interface, if they are still around.

**Comment by m-khansari** [comment]
Thank you very much

**Comment by m-khansari** [comment]
I've used the the dlls in the link you provided, but I still can not use the "ma" linear silvers(ma27, ma57, ma77,...) and get the same error....
Have you ever used these linear solvers?

**Comment by svigerske** [comment]
Yes, but I just build it into the Ipopt lib.
Looks like the DLL-loading function is disabled in the DLL from the release page. I have an idea what went wrong and will need to fix that.

**Comment by m-khansari** [comment]
![image](https://user-images.githubusercontent.com/39255756/95654034-0d8f3680-0b0a-11eb-8f78-99ec9504ac1c.png)



I've found this file: "config.site" in  "IPOPT_PATH/Buidltools/share"  and it says somethings about my issue, but I really do not understand it... I thought it may be useful for you...

**Comment by svigerske** [comment]
Can you try whether it works better if you replace the ipopt-3.dll with this one: https://cloud.gams.com/s/Rrtd7kgjibcedJa ?
