### ISSUE TITLE
Hessian sparsity pattern

### ISSUE THREAD

**Issue by mottelet** [coin-or/Ipopt#412]
What happens when user gives the pattern of Hessian including (i,j) terms and symmetrical terms (j,i), which is often easier when the pattern and later on non-zero terms are taken from a higher level object (e.g. Scilab sparse matrix) ? Do we end up with a Hessian with all out-of-diagonal terms multiplied by 2 (because of summing convention of the triplet format used by IPOpt) ?

S.

**Comment by svigerske** [comment]
As far as I looked, that would be the case. The indices and values that are passed in with eval_h are more-or-less straightforward stored into a SymTMatrix and [it's documentation](https://coin-or.github.io/Ipopt/classIpopt_1_1SymTMatrix.html#details) also says that duplicate elements are added.

**Comment by mottelet** [comment]
> As far as I looked, that would be the case. The indices and values that are passed in with eval_h are more-or-less straightforward stored into a SymTMatrix and [it's documentation](https://coin-or.github.io/Ipopt/classIpopt_1_1SymTMatrix.html#details) also says that duplicate elements are added.

OK thanks.
