### ISSUE TITLE
Request: SPRAL support?

### ISSUE THREAD

**Issue by karldw** [coin-or/Ipopt#413]
Hello,

I'm guessing you've seen (or been a coauthor on) this comparison of various linear solvers in Ipopt: https://arxiv.org/pdf/1909.08104.pdf The paper notes "Prior to this study, SPRAL was not available within Ipopt. This is surprising due to its stability-preserving features and heterogeneous parallelization capabilities." Ultimately, the paper concludes that SPRAL is the best free solver for difficult problems. I'd add that it would be valuable to have another freely-licensed solver beyond MUMPS.

In the current Ipopt release, 3.13.2, [SPRAL](https://github.com/ralna/spral) remains unavailable (which makes sense! I'm sure it's a bunch of work to add a solver). Would it be possible to add SPRAL support to Ipopt?

Thanks!

**Comment by svigerske** [comment]
I saw it and agree that it would be nice if they were to contribute their interface.

**Comment by traversaro** [comment]
I wrote to one author of the paper some months ago ( @tasseff ) and he pointed me to their forks of SPRAL and IPOPT: 
* https://github.com/lanl-ansi/SPRAL (instructions: https://github.com/lanl-ansi/spral/blob/master/COMPILE.md)
* https://github.com/lanl-ansi/Ipopt (instructions: https://github.com/lanl-ansi/Ipopt/blob/master/COMPILE.md)

**Comment by tasseff** [comment]
@svigerske, it'd be great to merge our contributions with the master repository. I'll begin a pull request using our fork, and you can direct me as to what still needs cleaning up.

**Comment by traversaro** [comment]
> 
> 
> @svigerske, it'd be great to merge our contributions with the master repository. I'll begin a pull request using our fork, and you can direct me as to what still needs cleaning up.

Hi @tasseff , thanks a lot! To be honest after my mail we never tested your SPRAL+IPOPT, but having it merged upstream would definitely simplify testing. The changes in SPRAL are strictly necessary or the interface can be used also with the upstream SPRAL? If the changes are necessary, could it make sense to propose the changes to make this work even in SPRAL?

**Comment by tasseff** [comment]
@traversaro, that's a great thought. The changes in SPRAL in our fork are indeed necessary. (One of them fixes a critical bug in a function call that solves the linear system.) I'll submit a pull request to the upstream SPRAL repository sometime tonight.

**Comment by karldw** [comment]
#446 completes this request, so I'm closing this issue. Thank you all!
