### ISSUE TITLE
Display of obj_hess in second order derivative test

### ISSUE THREAD

**Issue by mottelet** [coin-or/Ipopt#415]
Hello,

Why does the display of the Hessian check considers all terms and not the sole lower triangle ? For example for 4 variables one could expect only the following 10 terms (or the symmetric ones)
 
              obj_hess[    0,    0] =  2.8151607991294161e+00 v  ~  2.8151607711635052e+00  [ 9.934e-09]
              obj_hess[    1,    0] = -4.7502676126296106e-01 v  ~ -4.7502676728251408e-01  [ 6.020e-09]
              obj_hess[    2,    0] =  2.2617976159588160e+00 v  ~  2.2617975583418679e+00  [ 2.547e-08]
              obj_hess[    3,    0] =  2.1433509342965989e-03 v  ~  2.1433541526825048e-03  [ 3.218e-09]
              obj_hess[    1,    1] =  4.3544211655989144e-02 v  ~  4.3544211050030993e-02  [ 6.060e-10]
              obj_hess[    2,    1] = -2.1216565492972572e-01 v  ~ -2.1216564486148073e-01  [ 1.007e-08]
              obj_hess[    3,    1] = -3.0964421396289009e-03 v  ~ -3.0964422680027251e-03  [ 1.284e-10]
              obj_hess[    2,    2] = -6.3540863114133006e-01 v  ~ -6.3540868656571237e-01  [ 5.542e-08]
              obj_hess[    3,    2] =  5.7317217072838017e-02 v  ~  5.7317219733412979e-02  [ 2.661e-09]
              obj_hess[    3,    3] = -1.6059103092274786e-03 v  ~ -1.6059101001734569e-03  [ 2.091e-10]

**Comment by svigerske** [comment]
I have no idea. Maybe Andreas remembers, but the code is like this for at least 13 years.

You could get differences if the gradients are somehow awkward, i.e., the finite-difference Hessian approximation used for the check is not symmetric. But https://github.com/coin-or/Ipopt/blob/master/src/Interfaces/IpTNLPAdapter.cpp#L3108 looks like it doesn't matter when the users Hessian is lower-, upper-, or none-triangular.

**Comment by mottelet** [comment]
Yeah, you are right, it could hide an eventual problem in the gradient computation.
