### ISSUE TITLE
Problem in finalize_solution() with return status == 11

### ISSUE THREAD

**Issue by mottelet** [coin-or/Ipopt#417]
Hello, 

I have a case where in ::finalize_solution() with return status == 11 (non convergence due to an incorrect constraint jacobian),   a crash (bad access) occurs when trying to access 

    ipopt_app->Statistics()->TotalCPUTime() 

where ipopt_app is my  SmartPtr<IpoptApplication> (saved in a user field).  I know I should directly use the fields of the provided  

    IpoptData* ip_data, IpoptCalculatedQuantities* ip_cq 

but some quantities are missing, typically the total cpu time. How should I proceed ?

**Comment by svigerske** [comment]
Probably `ipopt_app->Statistics()` is NULL?
That is something you could check.

It's unfortunate if statistics are missing in some unlucky cases. That should probably be fixed, but maybe you can just skip over something in your code if ipopt_app->Statistics() is NULL in the meanwhile.

**Comment by mottelet** [comment]
That's what I tried but I got a 

IpoptTNLP.cpp:193:34: error: could not convert ‘Ipopt::IpoptApplication::Statistics()’ from ‘Ipopt::SmartPtr<Ipopt::SolveStatistics>’ to ‘bool’
         if (ipopt_app->Statistics())

**Comment by svigerske** [comment]
try `IsValid(ipopt_app->Statistics())`

**Comment by mottelet** [comment]
OK thanks.

**Comment by svigerske** [comment]
With Ipopt 3.14, you should now get solve statistics also if all variables were fixed, or in general anytime when the solve status is above -10.
