### ISSUE TITLE
Ipopt Install Error: "ASL_jll" not found

### ISSUE THREAD

**Issue by Obtuya7** [coin-or/Ipopt#420]
Attempting to install Ipopt triggers the following error.

```julia
(prac.9.2020) pkg> add Ipopt
  Resolving package versions...
ERROR: KeyError: key "ASL_jll" not found
```
I have a fresh install of Julia 1.5.2 and I've tried VS Code and the REPL. I've only had this issue with Ipopt.jl.

The add request leaves a pkg entry without a version after failure. I've tried to remove and re-add but that doesn't solve the issue.

![image](https://user-images.githubusercontent.com/59591159/97762536-3c804300-1adf-11eb-8826-e6e01d25be47.png)

**Comment by svigerske** [comment]
I have no idea what that key is. Probably this issue should go to https://github.com/jump-dev/Ipopt.jl.

**Comment by Obtuya7** [comment]
Reposting this issue to 'jump-dev/ipopt.jl' per the recommendation of @svigerske
