### ISSUE TITLE
tiny_step_tol

### ISSUE THREAD

**Issue by mottelet** [coin-or/Ipopt#423]
Hi, when disappeared "tiny_step_tol" option in Ipopt ? I don't see the equivalent in current version.

**Comment by svigerske** [comment]
The option did not disappear: https://github.com/coin-or/Ipopt/blob/master/src/Algorithm/IpBacktrackingLineSearch.cpp#L106

It just isn't shown in the documentation. @andrea5w hand-picked a list of options that he wanted to show up in the docu: https://github.com/coin-or/Ipopt/blob/master/src/Interfaces/IpIpoptApplication.cpp#L227
