### ISSUE TITLE
Hessian estimation in Ipopt

### ISSUE THREAD

**Issue by mottelet** [coin-or/Ipopt#425]
Does there exists thirparty developments about estimation of sparse Hessian using graph coloring techniques that have been applied to Ipopt ?

**Comment by svigerske** [comment]
I believe that CppAD's sparse hessian uses some graph coloring techniques to reduce the number of Hessian*vector evaluations and that this is also used in CppAD's Ipopt interface:
- https://github.com/coin-or/CppAD/blob/master/cppad_ipopt/src/cppad_ipopt_nlp.cpp#L934
- https://coin-or.github.io/CppAD/doc/sparse_hes.htm

I haven't checked, but would assume that this also holds for ADOL-C, which also features some [examples on how to use it with Ipopt](https://github.com/coin-or/ADOL-C/tree/master/ADOL-C/examples/additional_examples/ipopt).
