### ISSUE TITLE
Problems installing IPOPT

### ISSUE THREAD

**Issue by LeoHenrik** [coin-or/Ipopt#427]
can someone share ipopt files already installed? 
that files are:
1-bin
2-include
3-lib
4-share
I want to use IPOPT in a model in PYOMO but i have some problement trying to install it, but the last ipopt version i have some share me that files.

**Comment by svigerske** [comment]
Looks like noone who read this issue had some files to share. There are a number of binary distributions of Ipopt [mentioned in the README](https://github.com/coin-or/Ipopt#precompiled-binaries). I'm not sure, but for Pyomo you may need only the Ipopt exectuable that can read AMPL .nl files.
