### ISSUE TITLE
How to measure Total CPU secs more finely

### ISSUE THREAD

**Issue by fukao-m** [coin-or/Ipopt#429]
In my NLP, 'Total CPU secs in NLP function evaluations' equals to 0.000. Is there any way to measure the time more finely?

**Comment by svigerske** [comment]
You could change the output formatter at

https://github.com/coin-or/Ipopt/blob/411e52d8fbe614354b450de17dd0180c01147a75/src/Interfaces/IpIpoptApplication.cpp#L998-L999

from `%10.3f` to something like `%g` to get more digits.

**Comment by fukao-m** [comment]
Many thanks
