### ISSUE TITLE
Set Ipopt::IpoptApplication option, program crash!!

### ISSUE THREAD

**Issue by JackRen88** [coin-or/Ipopt#431]
Hello,everyone!
When i run the following code:
`  Ipopt::SmartPtr<Ipopt::IpoptApplication> app = IpoptApplicationFactory();

  app->Options()->SetStringValue("hessian_approximation", "limited-memory");
  app->Options()->SetIntegerValue("print_level", 1);
  app->Options()->SetIntegerValue("max_iter", config_.spiral().max_iteration());
  app->Options()->SetIntegerValue("acceptable_iter",
                                  config_.spiral().opt_acceptable_iteration());
  app->Options()->SetNumericValue("tol", config_.spiral().opt_tol());
  app->Options()->SetNumericValue("acceptable_tol",
                                  config_.spiral().opt_acceptable_tol());`
program crash.By debuging,I find that setting Ipopt::IpoptApplication option,program crash

**Comment by svigerske** [comment]
Setting options works for me and this code looks ok.
Please debug a bit more and figure out why it crashes for you.

**Comment by svigerske** [comment]
I tried this C++ program:
```cpp
#include "IpIpoptApplication.hpp"

int main()
{
   Ipopt::SmartPtr<Ipopt::IpoptApplication> app = IpoptApplicationFactory();

   app->Options()->SetStringValue("hessian_approximation", "limited-memory");
   app->Options()->SetIntegerValue("print_level", 1);
   app->Options()->SetIntegerValue("max_iter", 100);
   app->Options()->SetIntegerValue("acceptable_iter", 10);
   app->Options()->SetNumericValue("tol", 1e-7);
   app->Options()->SetNumericValue("acceptable_tol", 1e-5);
   
   return 0;
}
```
and compiled and run via
```
g++ 431.cpp -I /path/to/ipopt-install/include/coin-or/ -L /path/to/ipopt-install/lib/ -lipopt -Wl,-rpath,/path/to/ipopt-install/lib/ && valgrind --leak-check=full --show-reachable=yes ./a.out
```
but got no error.
