### ISSUE TITLE
Use Ipopt for feasibility only

### ISSUE THREAD

**Issue by mottelet** [coin-or/Ipopt#433]
I was wondering about the performances of Ipopt for solving square systems of equations. For example in Scilab one cannot take into account sparsity of the Jacobian when solving F(x)=0, whereas Ipopt deals sparsity out of the box. Would it be a good idea ?

**Comment by svigerske** [comment]
I don't really know. I presume the algorithm in Ipopt will boil down to solve a system of equations via Newton's method. The linear equation system that needs to be solved for this will be done in sparse form.

**Comment by svigerske** [comment]
The second paragraph on https://list.coin-or.org/pipermail/ipopt/2020-December/004801.html is probably relevant here, and its by someone who is actually using Ipopt for large-scale optimization.

**Comment by mottelet** [comment]
ok thanks
