### ISSUE TITLE
Provided package HSL is not working or does not contain MA27

### ISSUE THREAD

**Issue by kashifzr** [coin-or/Ipopt#434]
<pre>./configure
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking whether make supports the include directive... yes (GNU style)
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking for gfortran... gfortran
checking whether we are using the GNU Fortran 77 compiler... yes
checking whether gfortran accepts -g... yes
checking how to get verbose linking output from gfortran... -v
checking for Fortran 77 libraries of gfortran...  -L/usr/lib/gcc/x86_64-linux-gnu/7 -L/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/7/../../../../lib -L/lib/x86_64-linux-gnu -L/lib/../lib -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/7/../../.. -lgfortran -lm -lquadmath
checking for dummy main to link with Fortran 77 libraries... none
checking for Fortran 77 name-mangling scheme... lower case, underscore, no extra underscore
checking whether gfortran understands -c and -o together... yes
checking for gfortran... gfortran
checking whether we are using the GNU Fortran compiler... yes
checking whether gfortran accepts -g... yes
checking whether gfortran understands -c and -o together... yes
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mt... mt
checking if mt is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking the archiver (ar) interface... ar
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
checking for gfortran option to produce PIC... -fPIC
checking if gfortran PIC flag -fPIC works... yes
checking if gfortran static flag -static works... yes
checking if gfortran supports -c -o file.o... yes
checking if gfortran supports -c -o file.o... (cached) yes
checking whether the gfortran linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
checking for gfortran option to produce PIC... -fPIC
checking if gfortran PIC flag -fPIC works... yes
checking if gfortran static flag -static works... yes
checking if gfortran supports -c -o file.o... yes
checking if gfortran supports -c -o file.o... (cached) yes
checking whether the gfortran linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
configure: libtool version info: -version-number 2:2:0
checking for pkgconf... no
checking for pkg-config... pkg-config
checking pkg-config is at least version 0.16.0... yes: 0.29.1
configure: pkg-config path is &quot;/usr/local/lib/pkgconfig:/opt/ros/melodic/lib/pkgconfig&quot;
checking for MC19... no
checking for MA27... no
checking for MA28... no
checking for MA57... no
checking for MA77... no
checking for MA86... no
checking for MA97... no
checking for MC19S... no
checking for MA27S... no
checking for MA57S... no
checking for C interface to MC68... no
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating coinhsl.pc
config.status: creating config.h
config.status: config.h is unchanged
config.status: creating CoinHslConfig.h
config.status: CoinHslConfig.h is unchanged
config.status: executing depfiles commands
config.status: executing libtool commands
configure: Configuration of CoinHSL successful
</pre>

After running ThirdParty HSL i am facing issue to that HSL is working or does not contain MA27, following some guide to change the file MA27d.f to MA27ad.f does not work, where I try to run make command after ./configure then make command failed because of changing the name of file MA27d.f so how i to resolve this issue 

<pre>checking for package HSL... yes
checking HSL name mangling scheme... unknown
configure: WARNING: Unsupported or unknown name-mangling scheme: unknown
configure: error: Provided package HSL is not working or does not contain MA27.
</pre>

**Comment by svigerske** [comment]
The configure output for ThirdParty-HSL looks as if it couldn't find any of the HSL packages, including MA27. configure looks for `coinhsl/ma27/ma27d.f`within the ThirdParty-HSL source directory. So everything in lower case.

I don't know why "some guide" suggests to use `MA27ad.f`. Seems wrong, too.

**Comment by kashifzr** [comment]
Hi 
<pre><font color="#8AE234"><b>abc@abc</b></font>:<font color="#729FCF"><b>~/DWL_wspace/ThirdParty-HSL</b></font>$ ls
<font color="#8AE234"><b>ar-lib</b></font>                    <font color="#8AE234"><b>config.guess</b></font>   <font color="#8AE234"><b>depcomp</b></font>        Makefile.in
<font color="#729FCF"><b>coinhsl</b></font>                   config.h       <font color="#8AE234"><b>install-sh</b></font>     metis_adapter.c
CoinHslConfig.h           config.h.in    libcoinhsl.la  metis_adapter.lo
CoinHslConfig.h.in        config.log     <font color="#8AE234"><b>libtool</b></font>        <font color="#8AE234"><b>missing</b></font>
coinhsl.pc                <font color="#8AE234"><b>config.status</b></font>  LICENSE        README.md
coinhsl.pc.in             <font color="#8AE234"><b>config.sub</b></font>     <font color="#8AE234"><b>ltmain.sh</b></font>      stamp-h1
<font color="#8AE234"><b>compile</b></font>                   <font color="#8AE234"><b>configure</b></font>      Makefile       stamp-h2
config_coinhsl_default.h  configure.ac   Makefile.am
<font color="#8AE234"><b>abc@abc</b></font>:<font color="#729FCF"><b>~/DWL_wspace/ThirdParty-HSL</b></font>$ cd coinhsl
<font color="#8AE234"><b>abc@abc</b></font>:<font color="#729FCF"><b>~/DWL_wspace/ThirdParty-HSL/coinhsl</b></font>$ ls
ChangeLog  <font color="#729FCF"><b>include</b></font>  <font color="#729FCF"><b>lib</b></font>  LICENCE  <font color="#729FCF"><b>ma27</b></font>  README
<font color="#8AE234"><b>abc@abc</b></font>:<font color="#729FCF"><b>~/DWL_wspace/ThirdParty-HSL/coinhsl</b></font>$ cd ma27
<font color="#8AE234"><b>abc@abc</b></font>:<font color="#729FCF"><b>~/DWL_wspace/ThirdParty-HSL/coinhsl/ma27</b></font>$ ls
acinclude.m4  configure.ac  <font color="#8AE234"><b>install-sh</b></font>  Makefile.am  README
aclocal.m4    <font color="#729FCF"><b>doc</b></font>           LICENCE     Makefile.in  <font color="#729FCF"><b>src</b></font>
<font color="#8AE234"><b>configure</b></font>     <font color="#729FCF"><b>example</b></font>       <font color="#729FCF"><b>m4</b></font>          <font color="#8AE234"><b>missing</b></font>
<font color="#8AE234"><b>abc@abc</b></font>:<font color="#729FCF"><b>~/DWL_wspace/ThirdParty-HSL/coinhsl/ma27</b></font>$ cd src
<font color="#8AE234"><b>abc@abc</b></font>:<font color="#729FCF"><b>~/DWL_wspace/ThirdParty-HSL/coinhsl/ma27/src</b></font>$ ls
<font color="#8AE234"><b>ma27d.f</b></font>  <font color="#8AE234"><b>ma27s.f</b></font>  Makefile.am  Makefile.in
<font color="#8AE234"><b>abc@abc</b></font>:<font color="#729FCF"><b>~/DWL_wspace/ThirdParty-HSL/coinhsl/ma27/src</b></font>$ 
</pre>

I am sending the directories and their contents so, is what I need or something because In my case ThirdPartyHSL is still not able to find ma27 which i try using different options

**Comment by svigerske** [comment]
`configure` looks for `coinhsl/ma27/ma27d.f`, but you have `coinhsl/ma27/src/ma27d.f`

It is often easiest to get the HSL package that is specialized for use in Ipopt: http://www.hsl.rl.ac.uk/ipopt/

**Comment by kashifzr** [comment]
HI
Svigerske 
Thanks for your help. Now its not make issue when download HSL package through official web

**Comment by JPelda** [comment]
Sry for asking again. I have the same problem:

configure: WARNING: Unsupported or unknown name-mangling scheme: unknown
configure: error: Provided package HSL is not working or does not contain MA27.

 I have gotten coinhsl-2019-05.21.tar.gz from official webside. After
1. tar
2. ./configure 
3. make
4. make install

into the folder /coinbrew/ThirdParty/HSL
I have also /coinbrew/ThirdParty/HSL/ma27 and /coinbrew/ThirdParty/HSL/ma27/ma27d.f
I also tried /coinbrew/ThirdParty/HSL/coinhsl/ma27 and /coinbrew/ThirdParty/HSL/coinhsl/ma27/ma27d.f

Additionally, I followed the issue coinbrew skips HSL #28. Still no success in getting ipopt running through coinbrew with HSL.
I also get the message skipping ThirdParty/HSL.

Any help on that? Here is the debug file:

[coinbrew.txt](https://github.com/coin-or/Ipopt/files/6404556/coinbrew.txt)

**Comment by svigerske** [comment]
Looks like there is some problem with your checkout of ThirdParty-HSL:
```
+ /home/user/coinbrew/ThirdParty/HSL/configure --disable-dependency-tracking --disable-option-checking --prefix=/home/user/coinbrew/~/Ipopt --with-coin-instdir=/home/user/coinbrew/~/Ipopt
./coinbrew: line 1156: /home/user/coinbrew/ThirdParty/HSL/configure: No such file or directory
```
Somehow `configure` seems to have disappeared, but other files, e.g., `ThirdParty/HSL/coinhsl/common/deps.f`, are there.

**Comment by JPelda** [comment]
Thank you for your fast answer!
Also with "configure" provided there is still something missing. 

Maybe it could help if kashifzr would have said which version of hsl he downloaded. Here is the message I always get:

[checking build system type... x86_64-pc-linux-gnu.txt](https://github.com/coin-or/Ipopt/files/6405471/checking.build.system.type.x86_64-pc-linux-gnu.txt)

**Comment by takafusui** [comment]
Dear all,

it looks like a known issue, but I also have the same installation problem.
I want to install Ipopt on a university cluster. I clone Ipopt as well as the third-party libraries from git following the installation guide [here](https://coin-or.github.io/Ipopt/INSTALL.html).

First I configure the HSL library and it works:
...
```shell
checking for MC19... yes
checking for MA27... yes
checking for MA28... yes
checking for MA57... yes
checking for MA77... yes
checking for MA86... yes
checking for MA97... yes
checking for MC19S... yes
checking for MA27S... yes
checking for MA28S... yes
checking for MA57S... yes
checking for MA77S... yes
checking for MA86S... yes
checking for MA97S... yes
```
...

then I configure Ipopt from `Ipopt/build`, I got the following error message:
```shell
checking for package HSL... yes
checking for function ma27ad_ in -L/dummy_path/my_usr/lib -lcoinhsl    ... no
checking for function ma27ad in -L/dummy_path/my_usr/lib -lcoinhsl    ... no
checking for function MA27AD_ in -L/dummy_path/my_usr/lib -lcoinhsl    ... no
checking for function MA27AD in -L/dummy_path/my_usr/lib -lcoinhsl    ... no
checking for function ma27ad__ in -L/dummy_path/my_usr/lib -lcoinhsl    ... no
checking for function ma27ad_ in -L/dummy_path/my_usr/lib -lcoinhsl    ... no
checking for function MA27AD__ in -L/dummy_path/my_usr/lib -lcoinhsl    ... no
checking for function MA27AD_ in -L/dummy_path/my_usr/lib -lcoinhsl    ... no
configure: error: Provided package HSL is not working or does not contain MA27.
```
but I have `libcoinhsl` under
```bash
[trutzusu@login build]$ cd ../../my_usr/lib/
[trutzusu@login lib]$ ls | grep coin
libcoinasl.la
libcoinasl.so
libcoinasl.so.2
libcoinasl.so.2.0.0
libcoinhsl.la
libcoinhsl.so
libcoinhsl.so.2
libcoinhsl.so.2.2.0
libcoinmumps.la
libcoinmumps.so
libcoinmumps.so.3
libcoinmumps.so.3.0.1
```
Interestingly enough, I can compile Ipopt correctly using the same git repo on my laptop.

I appreciate any help. Thank you very much in advance.

**Comment by svigerske** [comment]
Have a look into the config.log generated by Ipopt's configure to see why all checks for MA27AD failed. At least one of them should have succeeded.

**Comment by takafusui** [comment]
Thank you for your prompt answer. `config.log` says
```shell
[trutzusu@login build]$ cat config.log | grep MA27AD
configure:24545: checking for function MA27AD_ in -L/dummy_path/my_usr/lib -lcoinhsl    
conftest.c:(.text.startup+0x7): undefined reference to `MA27AD_'
| char MA27AD_ ();
| return MA27AD_ ();
configure:24545: checking for function MA27AD in -L/dummy_path/my_usr/lib -lcoinhsl    
conftest.c:(.text.startup+0x7): undefined reference to `MA27AD'
| char MA27AD ();
| return MA27AD ();
configure:24545: checking for function MA27AD__ in -L/dummy_path/my_usr/lib -lcoinhsl    
conftest.c:(.text.startup+0x7): undefined reference to `MA27AD__'
| char MA27AD__ ();
| return MA27AD__ ();
configure:24545: checking for function MA27AD_ in -L/dummy_path/my_usr/lib -lcoinhsl    
conftest.c:(.text.startup+0x7): undefined reference to `MA27AD_'
| char MA27AD_ ();
| return MA27AD_ ();
```
It looks like `MA27AD` is not well defined there.

When I check one section, it says
```shell
configure:24545: checking for function MA27AD_ in -L/dummy_path/my_usr/lib -lcoinhsl    
configure:24570: /dcsrsoft/spack/hetre/v1.2/spack/opt/spack/linux-rhel8-zen/gcc-8.3.1/gcc-9.3.0-nwqdwvso3jf3fgygezygmtty6hvydale/bin/gcc -o conftest -O2 -DNDEBUG    conftest.c -L/dummy_path/my_usr/lib -lcoinhsl     >&5
/tmp/ccdboNPr.o: In function `main':
conftest.c:(.text.startup+0x7): undefined reference to `MA27AD_'
/dummy_path/my_usr/lib/libcoinhsl.so: undefined reference to `dtrmm_'
/dummy_path/my_usr/lib/libcoinhsl.so: undefined reference to `snrm2_'
/dummy_path/my_usr/lib/libcoinhsl.so: undefined reference to `dswap_'
/dummy_path/my_usr/lib/libcoinhsl.so: undefined reference to `dgemm_'
/dummy_path/my_usr/lib/libcoinhsl.so: undefined reference to `dtpsv_'
/dummy_path/my_usr/lib/libcoinhsl.so: undefined reference to `sswap_'
/dummy_path/my_usr/lib/libcoinhsl.so: undefined reference to `daxpy_'
/dummy_path/my_usr/lib/libcoinhsl.so: undefined reference to `stpsv_'
/dummy_path/my_usr/lib/libcoinhsl.so: undefined reference to `dtpmv_'
/dummy_path/my_usr/lib/libcoinhsl.so: undefined reference to `saxpy_'
/dummy_path/my_usr/lib/libcoinhsl.so: undefined reference to `dnrm2_'
/dummy_path/my_usr/lib/libcoinhsl.so: undefined reference to `dtrsv_'
/dummy_path/my_usr/lib/libcoinhsl.so: undefined reference to `dcopy_'
/dummy_path/my_usr/lib/libcoinhsl.so: undefined reference to `strmm_'
/dummy_path/my_usr/lib/libcoinhsl.so: undefined reference to `isamax_'
/dummy_path/my_usr/lib/libcoinhsl.so: undefined reference to `strsv_'
/dummy_path/my_usr/lib/libcoinhsl.so: undefined reference to `sgemm_'
/dummy_path/my_usr/lib/libcoinhsl.so: undefined reference to `scopy_'
/dummy_path/my_usr/lib/libcoinhsl.so: undefined reference to `dsyrk_'
/dummy_path/my_usr/lib/libcoinhsl.so: undefined reference to `spotrf_'
/dummy_path/my_usr/lib/libcoinhsl.so: undefined reference to `dtrsm_'
/dummy_path/my_usr/lib/libcoinhsl.so: undefined reference to `idamax_'
/dummy_path/my_usr/lib/libcoinhsl.so: undefined reference to `dpotrf_'
/dummy_path/my_usr/lib/libcoinhsl.so: undefined reference to `strmv_'
/dummy_path/my_usr/lib/libcoinhsl.so: undefined reference to `dtrmv_'
/dummy_path/my_usr/lib/libcoinhsl.so: undefined reference to `dgemv_'
/dummy_path/my_usr/lib/libcoinhsl.so: undefined reference to `sgemv_'
/dummy_path/my_usr/lib/libcoinhsl.so: undefined reference to `stpmv_'
/dummy_path/my_usr/lib/libcoinhsl.so: undefined reference to `strsm_'
/dummy_path/my_usr/lib/libcoinhsl.so: undefined reference to `ssyrk_'
```
Do you find an error?

Thank you.

P.S.
I confirmed that I can compile Ipopt correctly with HSL on my laptop. My naive guess is about a version incompatibility in gcc, but I use gcc 9.3.0 on Ubuntu 20.04. gcc on the university cluster is also 9.3.0 (Spack GCC).

**Comment by svigerske** [comment]
You might want to grep also for ma27 (lower case).

All other unresolved references are for Lapack. The lapack lib should be a dependency of the coinhsl lib, but if that didn't work, then you will have to specify it explictly. Something like `--with-hsl-lib="-L/dummy_path/my_usr/lib -lcoinhsl -llapack"`

**Comment by takafusui** [comment]
Yes it looks like `ma27ad_` is there...

```shell
[trutzusu@login build]$ cat config.log | grep ma27
configure:24545: checking for function ma27ad_ in -L/dummy_path/my_usr/lib -lcoinhsl    
| char ma27ad_ ();
| return ma27ad_ ();
configure:24545: checking for function ma27ad in -L/dummy_path/my_usr/lib -lcoinhsl    
conftest.c:(.text.startup+0x7): undefined reference to `ma27ad'
| char ma27ad ();
| return ma27ad ();
configure:24545: checking for function ma27ad__ in -L/dummy_path/my_usr/lib -lcoinhsl    
conftest.c:(.text.startup+0x7): undefined reference to `ma27ad__'
| char ma27ad__ ();
| return ma27ad__ ();
configure:24545: checking for function ma27ad_ in -L/dummy_path/my_usr/lib -lcoinhsl    
| char ma27ad_ ();
| return ma27ad_ ();
```

**Comment by svigerske** [comment]
And still it concludes that it could not find `ma27ad_`.

Instead of just grepping for single lines, could you please open the file, move the cursor to the part where `ma27ad_` is checked for, and read everything that follows...

**Comment by takafusui** [comment]
Thank you. I attach the `ma27ad_` related part here:
```bash
configure:24545: checking for function ma27ad_ in -L/dummy_path/my_usr/lib -lcoinhsl    
configure:24570: /dcsrsoft/spack/hetre/v1.2/spack/opt/spack/linux-rhel8-zen/gcc-8.3.1/gcc-9.3.0-nwqdwvso3jf3fgygezygmtty6hvydale/bin/gcc -o conftest -O2 -DNDEBUG    conftest.c -L/dummy_path/my_usr/lib -lcoinhsl     >&5
/dummy_path/my_usr/lib/libcoinhsl.so: undefined reference to `dtrmm_'
/dummy_path/my_usr/lib/libcoinhsl.so: undefined reference to `snrm2_'
/dummy_path/my_usr/lib/libcoinhsl.so: undefined reference to `dswap_'
/dummy_path/my_usr/lib/libcoinhsl.so: undefined reference to `dgemm_'
/dummy_path/my_usr/lib/libcoinhsl.so: undefined reference to `dtpsv_'
/dummy_path/my_usr/lib/libcoinhsl.so: undefined reference to `sswap_'
/dummy_path/my_usr/lib/libcoinhsl.so: undefined reference to `daxpy_'
/dummy_path/my_usr/lib/libcoinhsl.so: undefined reference to `stpsv_'
/dummy_path/my_usr/lib/libcoinhsl.so: undefined reference to `dtpmv_'
/dummy_path/my_usr/lib/libcoinhsl.so: undefined reference to `saxpy_'
/dummy_path/my_usr/lib/libcoinhsl.so: undefined reference to `dnrm2_'
/dummy_path/my_usr/lib/libcoinhsl.so: undefined reference to `dtrsv_'
/dummy_path/my_usr/lib/libcoinhsl.so: undefined reference to `dcopy_'
/dummy_path/my_usr/lib/libcoinhsl.so: undefined reference to `strmm_'
/dummy_path/my_usr/lib/libcoinhsl.so: undefined reference to `isamax_'
/dummy_path/my_usr/lib/libcoinhsl.so: undefined reference to `strsv_'
/dummy_path/my_usr/lib/libcoinhsl.so: undefined reference to `sgemm_'
/dummy_path/my_usr/lib/libcoinhsl.so: undefined reference to `scopy_'
/dummy_path/my_usr/lib/libcoinhsl.so: undefined reference to `dsyrk_'
/dummy_path/my_usr/lib/libcoinhsl.so: undefined reference to `spotrf_'
/dummy_path/my_usr/lib/libcoinhsl.so: undefined reference to `dtrsm_'
/dummy_path/my_usr/lib/libcoinhsl.so: undefined reference to `idamax_'
/dummy_path/my_usr/lib/libcoinhsl.so: undefined reference to `dpotrf_'
/dummy_path/my_usr/lib/libcoinhsl.so: undefined reference to `strmv_'
/dummy_path/my_usr/lib/libcoinhsl.so: undefined reference to `dtrmv_'
/dummy_path/my_usr/lib/libcoinhsl.so: undefined reference to `dgemv_'
/dummy_path/my_usr/lib/libcoinhsl.so: undefined reference to `sgemv_'
/dummy_path/my_usr/lib/libcoinhsl.so: undefined reference to `stpmv_'
/dummy_path/my_usr/lib/libcoinhsl.so: undefined reference to `strsm_'
/dummy_path/my_usr/lib/libcoinhsl.so: undefined reference to `ssyrk_'
collect2: error: ld returned 1 exit status
configure:24570: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "Ipopt"
| #define PACKAGE_TARNAME "ipopt"
| #define PACKAGE_VERSION "3.14.5"
| #define PACKAGE_STRING "Ipopt 3.14.5"
| #define PACKAGE_BUGREPORT "https://github.com/coin-or/Ipopt/issues/new"
| #define PACKAGE_URL "https://github.com/coin-or/Ipopt"
| #define IPOPT_VERSION "3.14.5"
| #define IPOPT_VERSION_MAJOR 3
| #define IPOPT_VERSION_MINOR 14
| #define IPOPT_VERSION_RELEASE 5
| #define F77_FUNC(name,NAME) name ## _
| #define F77_FUNC_(name,NAME) name ## _
| #define HAVE_STDIO_H 1
| #define HAVE_STDLIB_H 1
| #define HAVE_STRING_H 1
| #define HAVE_INTTYPES_H 1
| #define HAVE_STDINT_H 1
| #define HAVE_STRINGS_H 1
| #define HAVE_SYS_STAT_H 1
| #define HAVE_SYS_TYPES_H 1
| #define HAVE_UNISTD_H 1
| #define STDC_HEADERS 1
| #define HAVE_DLFCN_H 1
| #define LT_OBJDIR ".libs/"
| #define IPOPT_VERBOSITY 0
| #define IPOPT_CHECKLEVEL 0
| #define IPOPT_HAS_LAPACK 1
| #define IPOPT_LAPACK_FUNC(name,NAME) name ## _
| #define IPOPT_LAPACK_FUNC_(name,NAME) name ## _
| #define IPOPT_HAS_ASL 1
| #define IPOPT_HAS_MUMPS 1
| #define IPOPT_MPIINIT 1
| #define IPOPT_HAS_HSL 1
| #define HSLLIB_EXPORT 
| /* end confdefs.h.  */
| 
| /* Override any GCC internal prototype to avoid an error.
|    Use char because int might match the return type of a GCC
|    builtin and then its argument prototype would still apply.  */
| char ma27ad_ ();
| #ifdef F77_DUMMY_MAIN
| 
| #  ifdef __cplusplus
|      extern "C"
| #  endif
|    int F77_DUMMY_MAIN() { return 1; }
| 
| #endif
| int
| main (void)
| {
| return ma27ad_ ();
|   ;
|   return 0;
| }
configure:24579: result: no
```
Please let me know if you need more information... Thank you again.

**Comment by svigerske** [comment]
It is missing Lapack. Normally that should be linked into coinhsl, but looks like that hasn't happen for some reason. Try adding `-llapack` (or whatever it is on your system) to `--with-hsl-lib` (if you use that) or `LDFLAGS`.

**Comment by takafusui** [comment]
Thank you. After setting up the correct flag, I can compile Ipopt on a university cluster correctly.

**Comment by dhr999** [comment]
Hi I am trying to install Ipopt on windows using MSYS2. I am getting the same error. I got the package from HSL and I compiled it. I made sure the path for ma27 is correct. But I still get this error. I have attached the config.log for Thirdparty-HSL.

[config.log](https://github.com/coin-or/Ipopt/files/8859830/config.log)

**Comment by svigerske** [comment]
The config.log from ThirdParty-HSL looks fine. configure concluded that all the HSL sources are available, and also Lapack and Metis are found:
```
HSL_LFLAGS_NOPC='-lmetis  -llapack -lblas   -LC:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.3.0 -LC:/msys64/mingw64/bin/../lib/gcc -LC:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.3.0/../../../../x86_64-w64-mingw32/lib/../lib -LC:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.3.0/../../../../lib -LC:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.3.0/../../../../x86_64-w64-mingw32/lib -LC:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.3.0/../../.. -lgfortran -lmingw32 -lmoldname -lmingwex -lmsvcrt -lkernel32 -lquadmath -lm -lpthread -ladvapi32 -lshell32 -luser32 -fopenmp'

#define COINHSL_HAS_MC19 1
#define COINHSL_HAS_MA27 1
#define COINHSL_HAS_MA28 1
#define COINHSL_HAS_MA57 1
#define COINHSL_HAS_MA77 1
#define COINHSL_HAS_MA86 1
#define COINHSL_HAS_MA97 1
#define COINHSL_HAS_MC19S 1
#define COINHSL_HAS_MA27S 1
#define COINHSL_HAS_MA28S 1
#define COINHSL_HAS_MA57S 1
#define COINHSL_HAS_MA77S 1
#define COINHSL_HAS_MA86S 1
#define COINHSL_HAS_MA97S 1
#define COINHSL_HAS_MC68 1
#define COINHSL_HAS_LAPACK 1
#define COINHSL_LAPACK_FUNC(name,NAME) name ## _
#define COINHSL_LAPACK_FUNC_(name,NAME) name ## _
#define COINHSL_HAS_METIS 1
```
You will need to look into the config.log for Ipopt to get more details on what the issue is there.

**Comment by LaszloHars** [comment]
I spent several days struggling with the missing ma27ad reference. In my case, under WSL (Ubuntu 20.04) the installation contained 2 packages: OpenBlas and HSL. (I could not make MUMPS work.) They can be installed, after `git clone...`:
```
cd ~/OpenBLAS
./configure
make
sudo make PREFIX=/usr/local/ install
```
and
```
cd ~/ThirdParty-HSL/coinhsl
./configure --with-lapack-lflags="-lopenblas"
make
sudo make PREFIX=/usr/local/ install
```
For Ipopt itself I did:
```
mkdir ~/Ipopt
cd ~/Ipopt
git clone https://github.com/coin-or/Ipopt.git
mkdir ~/Ipopt/build
cd ~/Ipopt/build
```
Now, the tricky `configure` part.
The problem with the missing ma27ad occurs earlier than they are reported: when the libraries are checked. The `config.log` file shows a bunch of `undefined reference` errors:
```
/usr/bin/ld: /usr/local/lib/libcoinhsl.so: undefined reference to `dlsym'
/usr/bin/ld: /usr/local/lib/libcoinhsl.so: undefined reference to `isamax_'
/usr/bin/ld: /usr/local/lib/libcoinhsl.so: undefined reference to `idamax_'
/usr/bin/ld: /usr/local/lib/libcoinhsl.so: undefined reference to `dlopen'
```
Because of these errors, the libraries are not loaded, and so the ma27ad reference is not found. All we have to do is to specify the libraries in the correct order, where HSL can find the undefined references. The `config` command should look like this:
```
~/Ipopt/configure --with-lapack-lflags="-lopenblas" --with-hsl-lflags="-lcoinhsl -lopenblas -ldl"
```
Then `make` worked for me. Some of the tests invoked by `make test` worked. Ipopt is in business.
