### ISSUE TITLE
Returning objective value to main (c++)

### ISSUE THREAD

**Issue by Leersmaekers** [coin-or/Ipopt#438]
Dear,

I'm using Ipopt in c++, by using the following lines:
`SmartPtr<LapSim_NLP> mynlp = new LapSim_NLP(); `
`SmartPtr<IpoptApplication> app = IpoptApplicationFactory();`
`status = app->OptimizeTNLP(mynlp);`

The output is written to the console by means of the following (standard) function: `void LapSim_NLP::finalize_solution`

However, I don't need the objective value to be written to the screen, but I actually need it in the remainder of my code. What is the cleanest way of returning the obj_value?

Kind regards,
Laurent Keersmaekers

**Comment by svigerske** [comment]
If its just the objective value, then calling `app->Statistics()->FinalObjective()` should do (https://coin-or.github.io/Ipopt/classIpopt_1_1SolveStatistics.html#ad917ef3a3a792da9371d51837ad70978).

**Comment by Leersmaekers** [comment]
I added the line after the problem has been solved. However, I get the following error:

Error	C2039	'FinalObjective': is not a member of 'Ipopt::SmartPtr<Ipopt::SolveStatistics>'	Optimizer	...\LapSim_main.cpp

**Comment by Leersmaekers** [comment]
I solved the problem. I wasn't aware I needed to include the header file "<IpSolveStatistics.hpp>".

Thanks for your time!
Laurent Keersmaekers
