### ISSUE TITLE
New Configure Args

### ISSUE THREAD

**Issue by ashermancinelli** [coin-or/Ipopt#443]
I'm developing the spack package for Ipopt ([see spack PR here](https://github.com/spack/spack/pull/21592)), and the current spack package uses tarballs from the coin-or website instead of git. I've updated the spack package to allow disabling of MUMPS solver, since that package is sometimes problematic in spack. We would like to add support for installation via git to use newer versions of Ipopt, however it seems that your configure script has changed.

Please see [the Ipopt package in my fork of spack linked here](https://github.com/ashermancinelli/spack/blob/ipopt-update-versions/var/spack/repos/builtin/packages/ipopt/package.py). LAPACK and BLAS args are currently set like so:

```python
        args = [
            # other args...
            "--with-blas-incdir=%s" % blas_dir.include,
            "--with-blas-lib=%s" % blas_lib,
            "--with-lapack-incdir=%s" % lapack_dir.include,
            "--with-lapack-lib=%s" % lapack_lib
        ]
```

This however fails when using newest ipopt:

```console
configure: WARNING: unrecognized options: --with-blas-incdir, --with-blas-lib, --with-lapack-incdir, --with-lapack-lib, --with-hsl-lib, --with-hsl-incdir, --with-metis-lib, --with-metis-incdir
...
checking for lapack.pc and blas.pc... no
checking for function dsyev_ in -llapack -lblas ... no
checking for function dsyev in -llapack -lblas ... no
checking for function DSYEV_ in -llapack -lblas ... no
checking for function DSYEV in -llapack -lblas ... no
configure: error: Required package LAPACK not found.
```

Please advise how we should use the new configure script.

CC @pelesh @haampie

**Comment by tkralphs** [comment]
Yes, the newest Ipopt uses the newest version of our [BuildTools](https://github.com/coin-or-tools/BuildTools), which has changed in some significant ways from the previous version. However, I think `configure --help` should tell you everything you need to know.

**Comment by ashermancinelli** [comment]
What is the earliest version of Ipopt in which the build system was updated?

**Comment by tkralphs** [comment]
3.13 is the only version using the new build system.

**Comment by svigerske** [comment]
Yep. The [release notes / changelog](https://github.com/coin-or/Ipopt/blob/master/ChangeLog#L53) explain rather detailed the consequences that updating the buildsystem had on Ipopt.
