### ISSUE TITLE
Introducing slack variable at specific constraints

### ISSUE THREAD

**Issue by baryn** [coin-or/Ipopt#463]
Hi,
I have been using Ipopt for several c++ projects now (mainly for Model Predictive Control) it's great thanks.
Now, I would like to add slack variables to specific constraints. It appears that in my case I cannot guarantee the initial point (vector) will be feasible therefore I was wondering about the use of slack variables that I would minimize as one would do with SQP methods for instance (that allow infeasible initial points). I am aware that Ipopt requires the initial point to be feasible and that several options exist for modifying this initial point like bound_frac, bound_push or slack_bound_frac and slack_bound_push. Do they act only on the initial point or also over the optimization iterations ? My fear is that I don't want the restoration phase to be triggered and to modify the entire initial point vector as soon as a single element of it is out of the bounds. But rather to allow slight violations.

More precisely, in the context of a MPC problem, I have equality constraints that describe my (nonlinear) model over a prediction horizon N and among other constraints I have (linear) velocity constraints that I would like to relax. In my case, velocity measurements are used to initialize the current state and they cannot be guaranteed to lie inside my bounds (e.g., because of measurement noise present) and this triggers local infeasibility in Ipopt. What would be the best way for authorizing bounds violations only for these velocity constraints and not for the model equality constraints ?
I feel I am missing something ^^

Thanks for the hints !

**Comment by svigerske** [comment]
bound_frac, bound_push or slack_bound_frac and slack_bound_push should only act on the initial point. They move the initial point within the bounds and from then on, Ipopt only computed iterates that stay within bounds (or at bounds).

If you want to allow some variable to be outside bounds, then it may be sufficient to specify the bounds as inequalities (as part of g^L <= g(x) <= g^U) instead.

**Comment by baryn** [comment]
Thanks for the answer, I appreciate. 
I managed to improve the overall convergence by playing on those options. Not sure about what values to choose though.

> If you want to allow some variable to be outside bounds, then it may be sufficient to specify the bounds as inequalities (as part of g^L <= g(x) <= g^U) instead.

Actually my velocity constraints are already part of g(x). Do you mean having variable bounds ? Now, I guess I can introduce slack variables myself such that we have g(x) - lambda <= g^U and g(x) + lambda <= g^L, with lambda >= 0 and fix the initial point infeasibility thanks to the Ipopt options.

Cheers

**Comment by svigerske** [comment]
> Thanks for the answer, I appreciate.
> I managed to improve the overall convergence by playing on those options. Not sure about what values to choose though.
> 
> > If you want to allow some variable to be outside bounds, then it may be sufficient to specify the bounds as inequalities (as part of g^L <= g(x) <= g^U) instead.
> 
> Actually my velocity constraints are already part of g(x). Do you mean having variable bounds ? Now, I guess I can introduce slack variables myself such that we have g(x) - lambda <= g^U and g(x) + lambda <= g^L, with lambda >= 0 and fix the initial point infeasibility thanks to the Ipopt options.

I meant variable bounds. I thought you wanted to allow Ipopt to violate for some iterations.

If you want to allow violation of some constraints beyond the feasibility tolerance in the solution that Ipopt ends with, then doing the slack-approach that you mention should be ok. One then uses the objective coefficient of the slack variables to specify how much to penalize violation of these constraints.

**Comment by baryn** [comment]
Hi,

> I meant variable bounds. I thought you wanted to allow Ipopt to violate for some iterations.

Yes exactly.

> If you want to allow violation of some constraints beyond the feasibility tolerance in the solution that Ipopt ends with, then doing the slack-approach that you mention should be ok. One then uses the objective coefficient of the slack variables to specify how much to penalize violation of these constraints.

I will try that thanks.
