### ISSUE TITLE
exit code：-1073740940 (0xC0000374)

### ISSUE THREAD

**Issue by Jtstorm-git** [coin-or/Ipopt#465]
Some problem occurred, when I was running my program on Pycharm.  The fllowing is the description of the issue:
"This is Ipopt version 3.13.4, running with linear solver mumps.
NOTE: Other linear solvers might be more efficient (see Ipopt documentation).
Process finished with exit code -1073740940 (0xC0000374)"
 hoping for an answer! thanks.

**Comment by svigerske** [comment]
I don't know how to answer that. It looks like something has been crashing, but the exit code doesn't tell me anything.
Google points to https://stackoverflow.com/questions/61935980/process-finished-with-exit-code-1073740940-0xc0000374
