### ISSUE TITLE
Compiling IPOPT on Windows with Intel Fortran + MKL + Visual Studio

### ISSUE THREAD

**Issue by jacobwilliams** [coin-or/Ipopt#472]
I'm having basically the same problem as this person: https://stackoverflow.com/questions/65605175/compiling-ipopt-with-cygwin-and-intel-parallel-studio

Except I'm using msys2 rather than cygwin. I'm trying to compile the 3.14 tag.

Is there somebody who has successfully done this and what configure options did they use? It seems the documentation is not complete for this use case. I'll continue to try various options and report back if i get anything to work. (note: I have successfully compiled with Intel + MKL on Mac, but not Windows...yet).

**Comment by svigerske** [comment]
I use the flags
```
--enable-msvc --disable-sipopt --with-lapack="/c/PROGRA~2/INTELS~1/COMPIL~2/windows/mkl/lib/INTEL6~1/mkl_intel_lp64.lib /c/PROGRA~2/INTELS~1/COMPIL~2/windows/mkl/lib/INTEL6~1/mkl_sequential.lib /c/PROGRA~2/INTELS~1/COMPIL~2/windows/mkl/lib/INTEL6~1/mkl_core.lib"
```
to build the md-libs that are attached to the releases, e.g., https://github.com/coin-or/Ipopt/releases/download/releases%2F3.14.beta1/Ipopt-3.14.beta1-win64-msvs2019-md.zip   
So using dos-style shortpaths without spaces to avoid problems with spaces in paths.

The `--disable-sipopt` is probably not necessary.

**Comment by svigerske** [comment]
PS: There is also an automatic check for MKL, so normally `--enable-msvc` should be sufficient.
I think I used extra flags because I wanted a Ipopt DLL that doesn't depend on MKL DLLs, but has the static MKL libs included.

**Comment by jacobwilliams** [comment]
For the record, in my case, I was activating the wrong VC.

For the 64 bit versions of everything, this is working for me:

```bat
set MSYS2_PATH_TYPE=inherit

call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Auxiliary\Build\vcvars64.bat"
call "C:\Program Files (x86)\IntelSWTools\compilers_and_libraries_2019\windows\mkl\bin\mklvars.bat" intel64

C:\msys64\msys2.exe
```

Then something like this works for configure:

```
../configure --enable-msvc --disable-sipopt --disable-java --disable-shared
```

**Comment by jacobwilliams** [comment]
Although I do get this warning when building the tests:

```
ipo: warning #11087: C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\lib\x64\libcpmt.lib: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' does not match value 'MD_DynamicRelease' in C:\Users\username\Desktop\IPOPT_Compiling_tests\Ipopt\build\test\../src/.libs/ipopt.lib.
```

I'm trying to build a totally static lib. Maybe I'm getting shared libs in there somewhere?

**Comment by jacobwilliams** [comment]
When I remove `--disable-shared` i get the DLL and the tests seem to link fine.

**Comment by svigerske** [comment]
> Although I do get this warning when building the tests:
> 
> ```
> ipo: warning #11087: C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\lib\x64\libcpmt.lib: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' does not match value 'MD_DynamicRelease' in C:\Users\username\Desktop\IPOPT_Compiling_tests\Ipopt\build\test\../src/.libs/ipopt.lib.
> ```

I can reproduce this warning when the hs071_f test executable is build (but not for the hs071_c or hs071_cpp):
```
/path/to/Ipopt/compile /path/to/Ipopt/compile ifort -I../../test/../src/Interfaces -nologo -fpp -O2 -MD  -c -o hs071_f.obj `cygpath -w 'hs071_f.f'`
/bin/sh ../libtool  --tag=F77   --mode=link /path/to/Ipopt/compile /path/to/Ipopt/compile ifort -I../../test/../src/Interfaces -nologo -fpp -O2 -MD    -o hs071_f.exe hs071_f.obj ../src/libipopt.la
libtool: link: /path/to/Ipopt/compile /path/to/Ipopt/compile ifort -I../../test/../src/Interfaces -nologo -fpp -O2 -MD -o hs071_f.exe hs071_f.obj  ../src/.libs/ipopt.lib /c/PROGRA~2/INTELS~1/COMPIL~2/windows/mkl/lib/INTEL6~1/mkl_intel_lp64.lib /c/PROGRA~2/INTELS~1/COMPIL~2/windows/mkl/lib/INTEL6~1/mkl_sequential.lib /c/PROGRA~2/INTELS~1/COMPIL~2/windows/mkl/lib/INTEL6~1/mkl_core.lib
compile: ifort -I../../test/../src/Interfaces -nologo -fpp -O2 -MD -Fehs071_f.exe hs071_f.obj ../src/.libs/ipopt.lib C:/PROGRA~2/INTELS~1/COMPIL~2/windows/mkl/lib/INTEL6~1/mkl_intel_lp64.lib C:/PROGRA~2/INTELS~1/COMPIL~2/windows/mkl/lib/INTEL6~1/mkl_sequential.lib C:/PROGRA~2/INTELS~1/COMPIL~2/windows/mkl/lib/INTEL6~1/mkl_core.lib
ipo: warning #11087: C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.24.28314\lib\x64\libcpmt.lib: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' does not match value 'MD_DynamicRelease' in C:\msys64\home\distrib\stefan\Ipopt\build-static2\test\../src/.libs/ipopt.lib.
```
It looks like one of the Fortran runtime libraries (ifconsol.lib) brings in this dependency on libcmt:
```
$ dumpbin.exe -directives ifconsol.lib
Microsoft (R) COFF/PE Dumper Version 14.24.28324.1
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file ifconsol.lib

File Type: LIBRARY

   Linker Directives
   -----------------
   -defaultlib:libcpmt
```
I guess getting a `-nodefaultlib:libcpmt` into the linker flags would work around these warnings, but the proper fix would be if ifort would come with a MD-variant of `ifconsol.lib` (e.g., a `ifconsolmd.lib` with directive `-defaultlib:libcpmd`) and use that when ifort is called with -MD. They seem to manage that for `libifcore` vs `libifcoremd`.

> I'm trying to build a totally static lib. Maybe I'm getting shared libs in there somewhere?

`--disable-shared` only says that Ipopt should be build as a static lib, but doesn't say much about what dependencies to choose. `configure` will already look for the static version of MKL for your convenience, but, for example, using the dynamic version of the MSVC runtime library will remain to be the default. To avoid that, you would need to change the compiler flags, e.g., use `ADD_CFLAGS=-MT ADD_FCFLAGS=-MT ADD_CXXFLAGS=-MT`
