### ISSUE TITLE
Spral performance in Ipopt 3.14

### ISSUE THREAD

**Issue by mottelet** [coin-or/Ipopt#473]
Hi,

I tested the spral solver for a 46340 variables quadratic program (using hessian_constant="yes")  and I had roughly the same performances as when using MUMPS. I am a bit disapointed. Did I miss something ? 

S.

**Comment by svigerske** [comment]
https://arxiv.org/abs/1909.08104, which the doc for Ipopt 3.14 also links to, has some benchmarks of Ipopt with MUMPS vs Ipopt with SPRAL (and other linear solvers). I don't think that the conclusion was that SPRAL would always be preferable over MUMPS.

**Comment by mottelet** [comment]
> https://arxiv.org/abs/1909.08104, which the doc for Ipopt 3.14 also links to, has some benchmarks of Ipopt with MUMPS vs Ipopt with SPRAL (and other linear solvers). I don't think that the conclusion was that SPRAL would always be preferable over MUMPS.

After reading the paper I had the feeling that SPRAL performance was quite close to PARDISO, which explains my deception...

**Comment by svigerske** [comment]
You tested ONE instance!
