### ISSUE TITLE
Stop at each iteration

### ISSUE THREAD

**Issue by thanhndv212** [coin-or/Ipopt#477]
Hi team, 
I'd like to ask if it is possible to stop the solver at each iteration to run a function, then continue?
Thanks in advance!

Regards,
Thanh N.

**Comment by svigerske** [comment]
You can implement the intermediate_callback (https://coin-or.github.io/Ipopt/INTERFACES.html#INTERFACE_CPP_ADDITIONAL) with the C++, C, and Fortran interfaces. For the Java interface, this is available with Ipopt 3.14 (currently beta). The R interface doesn't seem to offer this. For the AMPL interface, there is no such functionality either.

**Comment by thanhndv212** [comment]
Thanks! I got it.
