### ISSUE TITLE
Suppress copyright message

### ISSUE THREAD

**Issue by mottelet** [coin-or/Ipopt#485]
I am trying to suppress copyright message and tried
~~~~
    ipopt_app->Options()->SetStringValue("sb","false");
    ipopt_app->Options()->SetStringValue("sb","no");
~~~~
without any success. What value should I give to "sb" ?

**Comment by svigerske** [comment]
`yes` should do it.

**Comment by svigerske** [comment]
I believe `sb` might stand for "skip banner".

**Comment by mottelet** [comment]
OK thanks.
