### ISSUE TITLE
Integrating a simulator with IPOPT

### ISSUE THREAD

**Issue by dinesh286** [coin-or/Ipopt#493]
I have a trajectroy simulator written in matlab.  I want to couple with IPOPT.  Number of design variables will be approximately 100, with equality and inequality constraints.  I have installed ipopt in matlab using mex installer.  Is there any in-build method in IPOPT to compute gradient and jacobian, if so kindly tell me the options and link to the existing problems solved using IPOPT

**Comment by svigerske** [comment]
There is an option [`jacobian_approximation`](https://coin-or.github.io/Ipopt/OPTIONS.html#OPT_jacobian_approximation), but performance may be very bad. Usually, one provides at least first-order derivatives to Ipopt.

**Comment by dinesh286** [comment]
if i use gradient and Jacobian computation using the simulator, it will take very long time to converge. Because i am using around 100 design variables.  Is there any better methods to compute jacobian and gradient to reduce run time.  Software like psopt and pymao uses ipopt solvers but not asking for gradient and jacobian separately.  Kindly share your experiences regarding this

**Comment by svigerske** [comment]
If you cannot provide first derivatives, then using a solver that doesn't rely on them may be the way to go. Something in the direction of derivative-free or black-box optimization.
