### ISSUE TITLE
problem building on macOS via coinbrew

### ISSUE THREAD

**Issue by rdzman** [coin-or/Ipopt#505]
I was successfully using the following to build Ipopt on macOS runners for GitHub Actions.
```
git clone https://github.com/coin-or/coinbrew
cd coinbrew
./coinbrew fetch Ipopt --no-prompt
./coinbrew build Ipopt --prefix=$HOME/install --test --no-prompt
./coinbrew install Ipopt
```

However, recently, it has begun failing with the following error.
```
##################################################
### Building ThirdParty/Mumps 3.0.0 
##################################################

ld: library not found for -lmetis

collect2: error: ld returned 1 exit status
Build failed, see error output above
make[1]: *** [libcoinmumps.la] Error 1

make: *** [all] Error 2
```

So I added a `brew install metis` before everything, but I still get the same result. Any ideas how to fix this?

FWIW, I also noticed it seems to be downloading MUMPS 5.4.0, even though it says 3.0.0.
```
##################################################
### Fetching ThirdParty/Mumps releases/3.0.0 
##################################################

 
Running script for downloading the source code for MUMPS
--2021-08-11 19:32:56--  http://coin-or-tools.github.io/ThirdParty-Mumps/MUMPS_5.4.0.tar.gz
```

**Comment by svigerske** [comment]
I think there is a problem with the check for Metis being done with the C compiler, but the linking being done with the Fortran compiler. When the Metis lib is found when checking via the C compiler, that does not say for sure that it will also be found when linking is done with the Fortran compiler, especially when compilers from different families are used, e.g., clang and gfortran.

In the travis builds for Ipopt on macOS, we specify the flags to find Metis explicitly:
https://github.com/coin-or/Ipopt/blob/a8b1a623c2417082bbc36db83bdf4331d09765e9/.travis.yml#L147

**Comment by svigerske** [comment]
Regarding the version number, ThirdParty/Mumps is a buildsystem for MUMPS and this buildsystem is at version 3.0.0.
And ThirdParty/Mumps 3.0.0 is for building MUMPS 5.4.0.

**Comment by rdzman** [comment]
Thanks, Stefan! That was exactly what I needed. Got it working again by defining those flags, inserting the following 3 lines before the `coinbrew` commands.

```
export METIS_VER=`ls /usr/local/Cellar/metis`
export with_metis_cflags=-I/usr/local/Cellar/metis/${METIS_VER}/include
export with_metis_lflags="-L/usr/local/Cellar/metis/${METIS_VER}/lib -lmetis"
```
