### ISSUE TITLE
libipopt-3.dll  does not work

### ISSUE THREAD

**Issue by maxwangatgit** [coin-or/Ipopt#508]
i follow the instruction and build ipopt with mingw32。 When build finished ，make test worked  fine。
after make install , i make the cpp example,and run the exe, it report  
`error while loading shared libraries: ?: cannot open shared object file: No such file or directory`
i have put all the dll needed in the same folder,but it still doesn't work. is any one face the same question?

```
$ ./hs071_cpp.exe
D:/software/msys2-base-x86_64-20210725/msys64/home/Max/Ipopt/build_release/examples/hs071_cpp/hs071_cpp.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory
```

**Comment by svigerske** [comment]
That usually means that some DLL is still not found.
[Dependency Walker](https://www.dependencywalker.com/) is usually helpful to find these, if `dumpbin` isn't sufficient.

**Comment by maxwangatgit** [comment]
> That usually means that some DLL is still not found.
> [Dependency Walker](https://www.dependencywalker.com/) is usually helpful to find these, if `dumpbin` isn't sufficient.


i am sure there is something wrong with this dll . Actually, i have build ipopt successfully once. so when i replace the new libipopt-3.dll with the dll worked successfully , the example worked fine. i just cannot create the same workable dll.

**Comment by maxwangatgit** [comment]
The library I successfully compiled will depend on libhsl.so. So i rename the libcoinhsl-2.dll to libhsl.so. But the new ipopt.dll will look for libcoinhsl-2.dll. This is the reason i failed.
