### ISSUE TITLE
Misattributed timings (UpdateHessian and CheckConvergence)

### ISSUE THREAD

**Issue by oliwiermelon** [coin-or/Ipopt#509]
I use _Ipopt 3.14.2_ via [_Ifopt_](https://github.com/ethz-adrl/ifopt) for trajectory optimization. I use _Ipopt_'s in-built _L-BFGS_ method to approximate the Hessian of Lagrangian (`hessian approximation limited-memory`).

When solving a problem, the reported timing statistics (`print_level 5`) indicate that `CheckConvergence` is responsible for the majority of the computation time:
```
OverallAlgorithm....................:      2.776 (sys:      0.004 wall:      1.055)
 PrintProblemStatistics.............:      0.000 (sys:      0.000 wall:      0.000)
 InitializeIterates.................:      0.407 (sys:      0.000 wall:      0.203)
 UpdateHessian......................:      0.000 (sys:      0.000 wall:      0.001)
 OutputIteration....................:      0.000 (sys:      0.000 wall:      0.000)
 UpdateBarrierParameter.............:      0.473 (sys:      0.000 wall:      0.109)
 ComputeSearchDirection.............:      0.106 (sys:      0.000 wall:      0.019)
 ComputeAcceptableTrialPoint........:      0.089 (sys:      0.000 wall:      0.024)
 AcceptTrialPoint...................:      0.002 (sys:      0.000 wall:      0.000)
 CheckConvergence...................:      1.695 (sys:      0.004 wall:      0.699)
```
If the following line is disabled:
https://github.com/coin-or/Ipopt/blob/a8b1a623c2417082bbc36db83bdf4331d09765e9/src/Algorithm/IpIpoptAlg.cpp#L408

Then this duration is attributed to `UpdateHessian` instead:
```
OverallAlgorithm....................:      2.739 (sys:      0.020 wall:      1.059)
 PrintProblemStatistics.............:      0.000 (sys:      0.000 wall:      0.000)
 InitializeIterates.................:      0.404 (sys:      0.008 wall:      0.210)
 UpdateHessian......................:      1.586 (sys:      0.000 wall:      0.650)
 OutputIteration....................:      0.001 (sys:      0.004 wall:      0.001)
 UpdateBarrierParameter.............:      0.428 (sys:      0.008 wall:      0.100)
 ComputeSearchDirection.............:      0.063 (sys:      0.000 wall:      0.015)
 ComputeAcceptableTrialPoint........:      0.098 (sys:      0.000 wall:      0.020)
 AcceptTrialPoint...................:      0.000 (sys:      0.000 wall:      0.000)
 CheckConvergence...................:      0.158 (sys:      0.000 wall:      0.062)
```

In attempt to locate the code responsible for this misattribution, I observed that the evaluation of (at least) the following (or similar) chunks of code:
https://github.com/coin-or/Ipopt/blob/a8b1a623c2417082bbc36db83bdf4331d09765e9/src/Algorithm/IpIpoptCalculatedQuantities.cpp#L1386-L1388
will cause the timing to be attributed to `CheckConvergence`.

Could you please explain this behaviour and its cause, and suggest how to correctly determine the time needed for the approximation of the Hessian?

**Comment by svigerske** [comment]
With the pointer to `curr_jac_c()` you were already at the right track.
In the normal code, the Jacobian is evaluated in the convergence check, e.g.,
```
#0  Ipopt::TNLPAdapter::Eval_jac_c (this=0x555555909980, x=..., jac_c=...) at ../../src/Interfaces/IpTNLPAdapter.cpp:1762
#1  0x00007ffff6c0418d in Ipopt::OrigIpoptNLP::jac_c (this=0x555555928fb0, x=...) at ../../src/Algorithm/IpOrigIpoptNLP.cpp:662
#2  0x00007ffff6ace91b in Ipopt::IpoptCalculatedQuantities::curr_jac_c (this=0x55555592d7a0) at ../../src/Algorithm/IpIpoptCalculatedQuantities.cpp:1242
#3  0x00007ffff6ad23be in Ipopt::IpoptCalculatedQuantities::curr_jac_cT_times_vec (this=0x55555592d7a0, vec=...)
    at ../../src/Algorithm/IpIpoptCalculatedQuantities.cpp:1387
#4  0x00007ffff6ad1794 in Ipopt::IpoptCalculatedQuantities::curr_jac_cT_times_curr_y_c (this=0x55555592d7a0)
    at ../../src/Algorithm/IpIpoptCalculatedQuantities.cpp:1349
#5  0x00007ffff6ae4631 in Ipopt::IpoptCalculatedQuantities::curr_grad_lag_x (this=0x55555592d7a0) at ../../src/Algorithm/IpIpoptCalculatedQuantities.cpp:2019
#6  0x00007ffff6af5628 in Ipopt::IpoptCalculatedQuantities::curr_dual_infeasibility (this=0x55555592d7a0, NormType=Ipopt::NORM_MAX)
    at ../../src/Algorithm/IpIpoptCalculatedQuantities.cpp:2686
#7  0x00007ffff6bd7214 in Ipopt::OptimalityErrorConvergenceCheck::CheckConvergence (this=0x5555558ed1a0, call_intermediate_callback=true)
    at ../../src/Algorithm/IpOptErrorConvCheck.cpp:181
```
But since Ipopt uses a caching mechanism to avoid recomputation of quantities that it has computed before, this Jacobian is then **reused** when updating the Hessian approximation.

If you disable the convergence check, then the Jacobian is evaluated in the Hessian approximation (`UpdateHessian()` is the first step in the while loop in `IpoptAlgorithm::Optimize()`, while `CheckConvergence()` is the last), e.g.,
```
#0  Ipopt::TNLPAdapter::Eval_jac_c (this=0x55555590a1a0, x=..., jac_c=...) at ../../src/Interfaces/IpTNLPAdapter.cpp:1762
#1  0x00007ffff6c03fa5 in Ipopt::OrigIpoptNLP::jac_c (this=0x5555559297d0, x=...) at ../../src/Algorithm/IpOrigIpoptNLP.cpp:662
#2  0x00007ffff6ace733 in Ipopt::IpoptCalculatedQuantities::curr_jac_c (this=0x55555592dfc0) at ../../src/Algorithm/IpIpoptCalculatedQuantities.cpp:1242
#3  0x00007ffff6b52ce7 in Ipopt::LimMemQuasiNewtonUpdater::UpdateHessian (this=0x55555592e860) at ../../src/Algorithm/IpLimMemQuasiNewtonUpdater.cpp:219
#4  0x00007ffff6a79449 in Ipopt::IpoptAlgorithm::UpdateHessian (this=0x55555592fc10) at ../../src/Algorithm/IpIpoptAlg.cpp:580
#5  0x00007ffff6a6e9fa in Ipopt::IpoptAlgorithm::Optimize (this=0x55555592fc10, isResto=false) at ../../src/Algorithm/IpIpoptAlg.cpp:349
```
The time measurement is simply measuring the complete time spend in `UpdateHessian()` and `CheckConvergence()`, so the Jacobian eval time is accounted to whatever step requires the Jacobian first.

Now I don't know what actually the correct "time needed for the approximation of the Hessian" is. If the Jacobian has to be evaluated anyway, do you want to add this to the time for the Hessian approximation? If not, then you already get the correct time. If you do, then maybe add the time spend for Jacobian evaluations, though I'm not sure that there are no evaluation of the Jacobian at points that are then not used to update the Hessian approximation, e.g., trial points that are rejected.

**Comment by oliwiermelon** [comment]
Thank you for your prompt and detailed reply. 

The impact of caching on attribution of computation times to specific methods makes sense. It also makes _Timing Statistics_ less meaningful than I naively assumed. 

I now realise that, in the case of my problem, the overhead of the approximation method is negligible in comparison to the evaluation of the Jacobians (which needs to happen regardless of the method being used).
