### ISSUE TITLE
"jar" not found

### ISSUE THREAD

**Issue by andrea5w** [coin-or/Ipopt#510]
Hello!!!

I am running configure on my (standard) Ubuntu machine, and when I run configure, the scripts stops with the following error:

checking for gcj... no
checking for guavac... no
checking for jikes... no
checking for javac... javac
checking if javac works... yes
checking if javac supports -h... yes
checking for javac... /usr/bin/javac
checking symlink for /usr/bin/javac... /etc/alternatives/javac
checking symlink for /etc/alternatives/javac... /usr/lib/jvm/jdk-14.0.2/bin/javac
checking jni headers... /usr/lib/jvm/jdk-14.0.2/include
checking for jar... no
configure: error: no acceptable jar program found in $PATH

The error goes away when I install a package like "default-jdk".

I suggest to adjust the configure script so that it does not terminate with an error message if "jar" is not found; this can be annoying if one wants to install Ipopt but does not need the java interface.

**Comment by svigerske** [comment]
I even have comment on that in configure.ac:

https://github.com/coin-or/Ipopt/blob/bae155b51f127a5b89f1eae8eadc6ac40d43785f/configure.ac#L413-L422

So if passing `--disable-java` is not a viable option, we can look into adding more flexibility. Unfortunately, that would mean to not use the AX_PROG_JAR macro. (PS: ok, that macro has very little own logic anyway)

**Comment by andrea5w** [comment]
Great! Then let’s disable Java by default. I’m sure I’m not the only one who runs into this issue, and probably more people have issues than people using Java. If someone wants to use Java they already know they are doing something special and can expect to pay more attention. And even after I installed jar the test failed which would be concerning for a simple user.

**Comment by svigerske** [comment]
But I have already changed configure to only give a warning and disable the build of the java interface if `jar` is not around, see the commit that closed this issue. So now, the Java interface isn't build anymore if there is no `javac` or no `jar` and the test is skipped if there is no `java`.
