### ISSUE TITLE
Optimize the interior point problem with a given number of iterations

### ISSUE THREAD

**Issue by junzengx14** [coin-or/Ipopt#513]
As far as I know, we can specific `max_iter` for solving the problem, but I'm wondering if we can optimize the problem with a given number of iterations? Or are there alternative ways of doing this?

Thank so much for all developers!

**Comment by svigerske** [comment]
If `max_iter` is set, then Ipopt will stop when it reached that number of iterations, unless it stopped for other reasons before. These other reasons are usually convergence to a local optimum, numerical problems, or reaching a timelimit.

In each iteration, Ipopt looks for an improving direction and tries to make a step in this direction. If there is no improving direction, then that means to be in a local optimum. Thus, there is no way for Ipopt to proceed with further iterations after it has found a local optimum.

**Comment by junzengx14** [comment]
Thank you so much for your reply!

> If `max_iter` is set, then Ipopt will stop when it reached that number of iterations, unless it stopped for other reasons before. These other reasons are usually convergence to a local optimum, numerical problems, or reaching a timelimit.
> 
> In each iteration, Ipopt looks for an improving direction and tries to make a step in this direction. If there is no improving direction, then that means to be in a local optimum. Thus, there is no way for Ipopt to proceed with further iterations after it has found a local optimum.
