### ISSUE TITLE
Windows releases

### ISSUE THREAD

**Issue by eike-fokken** [coin-or/Ipopt#517]
I try to link to the Windows releases:

```cmake

add_library(my_ipopt SHARED IMPORTED GLOBAL)

set_property(TARGET my_ipopt PROPERTY
             IMPORTED_LOCATION "C:/Users/Eike/Desktop/Ipopt-3.14.3-win64-msvs2019-md/bin/ipopt-3.dll")
set_property(TARGET my_ipopt PROPERTY
             IMPORTED_IMPLIB "C:/Users/Eike/Desktop/Ipopt-3.14.3-win64-msvs2019-md/lib/ipopt.dll.lib")

target_include_directories(my_ipopt INTERFACE "${IPOPT_DIRECTORY}/include/coin-or")
```

Using the my_ipopt target later on as a linked library in `target_link_libraries.
Configuring and building works, but when I execute my code, I get the error:
```sh
 error while loading shared libraries: api-ms-win-crt-locale-l1-1-0.dll: cannot open shared object file: No such file or directory
```
I just tried with a fully updated MSVC but the problem persists. Is that something on your end or mine?

Also, as I was really struggling to get it all to work, could you supply a CMakeLists.txt for linking to the windows libraries?

**Comment by eike-fokken** [comment]
Oh, I just found the libraries under bin. Will try with that.

**Comment by eike-fokken** [comment]
I just highjacked my own issue to pose a different one as the first one was only due to me not knowing enough about cmake under windows. But the missing dll above is something I have no idea how to fix, therefore: Please help!

**Comment by eike-fokken** [comment]
Hm, some update. After supplying each and every c runtime library (crt) present on my system, the final error message, I can not fix is this one:

```sh
 error while loading shared libraries: ?: cannot open shared object file: No such file or directory
```

My CMakeLists.txt now looks like this:

```cmake
include(FetchContent)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
set(CPACK_PROJECT_NAME ${PROJECT_NAME})
set(CPACK_PROJECT_VERSION ${PROJECT_VERSION})

set(CMAKE_EXPORT_COMPILE_COMMANDS on)

include_directories(${CMAKE_SOURCE_DIR})



add_library(my_ipopt SHARED IMPORTED GLOBAL)

set_property(TARGET my_ipopt PROPERTY
             IMPORTED_LOCATION "${CMAKE_SOURCE_DIR}/ipopt-3.dll")
set_property(TARGET my_ipopt PROPERTY
             IMPORTED_IMPLIB "${CMAKE_SOURCE_DIR}/ipopt.dll.lib")

target_include_directories(my_ipopt INTERFACE "${IPOPT_DIRECTORY}/include/coin-or")

FetchContent_Declare(
  googletest
  GIT_REPOSITORY https://github.com/google/googletest.git
  GIT_TAG        703bd9caab50b139428cea1aaff9974ebee5742e # release-1.10.0
)

FetchContent_MakeAvailable(googletest)

add_subdirectory(test)
enable_testing()

```

I configured with

```sh
cmake -S . -B build -DIPOPT_DIRECTORY=C:/Users/Eike/Desktop/Ipopt-3.14.3-win64-msvs2019-md
```

and built with

```sh
cmake --build build -C Release
```

In the CMake source directory all crts are located, as well as ipopt-3.dll and ipopt.dll.lib.

When I run a binary produced by linking my executable with the my_ipopt target, the error at the top occurs. If anyone has some pointers for me, I'd be really glad.

Best

**Comment by svigerske** [comment]
The `bin/` dir that has `ipopt-3.dll` and other DLLs should be in `PATH` when executing your application.

`dumpbin /dependents my_ipopt` should give you a list of DLL dependencies of your application. Make sure that they can be found when running your executable. Alternatively, [Dependency Walker](https://www.dependencywalker.com/) is a nice tool to inspect dependencies, too.

I hoped that I packed at least all Intel runtime dependencies, but maybe some MSVC 2019 runtime libs are still required (https://aka.ms/vs/16/release/vc_redist.x64.exe).

**Comment by eike-fokken** [comment]
Thanks, I'll try that.
But right now I opted against supplying a windows installation. Should I close the issue for now or leave it open?

**Comment by svigerske** [comment]
I wouldn't know what there is to do for me (I don't have a CMakeLists.txt), so closing.
