### ISSUE TITLE
MSVC solution for IPOPT

### ISSUE THREAD

**Issue by jbensabat** [coin-or/Ipopt#518]
Hello 
I am trying to build IPOPT under MSVC 2019. 
I wonder if there is a MSVC workspace available or a  CMAKE build 
thanks 
jac

**Comment by eike-fokken** [comment]
I second this and would prefer a cmake file, as then it can be worked into a crossplatform cmake setup.

**Comment by svigerske** [comment]
> Hello I am trying to build IPOPT under MSVC 2019. I wonder if there is a MSVC workspace available or a CMAKE build thanks jac

No, not here.
See also #507.
