### ISSUE TITLE
IPOPT Pre-Compiled Binaries for Windows

### ISSUE THREAD

**Issue by timhockswender** [coin-or/Ipopt#523]
I downloaded them but where is the appropriate location to put them?
I an trying to run KIPET which starts ok but requires ipopt (e.g. for example 2)
Any advice appreciated.
Tim

**Comment by svigerske** [comment]
I guess putting them somewhere so that the bin subdir is in PATH will be helpful for applications that needs to find the exe or dll. You may want to check with KIPET support on where they expect Ipopt to be installed.

**Comment by timhockswender** [comment]
Thanks for the quick reply. Since my note, I read more about pyomo and saw I can simply use conda to install the solvers. Their instructions are not quite right but the first kipet example, which uses ipopt, works ok. Other issues such as file names, I’ll take up with them.
