### ISSUE TITLE
Can't select IntelMKL Pardiso using Ipopt Option.

### ISSUE THREAD

**Issue by TheCynosure** [coin-or/Ipopt#527]
I am using Ipopt 3.14.4 on Ubuntu 18.04.

I have compiled Ipopt using the instructions here: https://coin-or.github.io/Ipopt/INSTALL.html#EXTERNALCODE_LINALG

I am using IntelMKL libraries as my "Solver" and I am using just about the same command you specify in the documentation (with a different lib directory): 
```
./configure --with-lapack-lflags="-L${MKLROOT}/lib/intel64 -Wl,--no-as-needed -lmkl_intel_lp64 -lmkl_sequential -lmkl_core -lm"
```

Ipopt compiles fine and I see this in the configure output:
```
checking for mkl_get_version_string... yes
checking whether user-supplied Pardiso library "" works... yes
```
`make test` also passes fine (but obviously doesn't run HSL or ASL tests).

But, when I go to set the `linear_solver` option through the IpoptApplication options I get the following error:
```
Setting: "pardisomkl" is not a valid setting for Option: linear_solver. Check the option documentation.

### linear_solver (String) ###
Category: Linear Solver
Description: Linear solver used for step computations.
Valid Settings:
	ma27 (use the Harwell routine MA27)
	ma57 (use the Harwell routine MA57)
	ma77 (use the Harwell routine HSL_MA77)
	ma86 (use the Harwell routine HSL_MA86)
	ma97 (use the Harwell routine HSL_MA97)
	pardiso (use the Pardiso package)
	wsmp (use WSMP package)
	mumps (use MUMPS package)
	custom (use custom linear solver)
Default: "pardiso"
```

According to the documentation pardisomkl is a valid setting in Ipopt 3.14 (see Install guide above).

Here is my tiny main.cc program to reproduce this bug:
```
#include <IpIpoptApplication.hpp>

int main() {
  auto app = IpoptApplicationFactory();
  app->Options()->SetStringValue("linear_solver", "pardisomkl");
}
```

And here is the command to compile it:
```
g++ main.cc -o main -Llib -lipopt -Iinclude/coin/ -lmkl_intel_lp64 -lmkl_sequential -lmkl_core -lblas
```
Then:
```
LD_LIBRARY_PATH=/lib ./main
```

I am also using an un-optimized version of BLAS, if that helps. Any help would be greatly appreciated. I see from the code that the error message is generated based on what solvers are available in Ipopt so I am wondering why it is not detecting pardiso mkl.

**Comment by svigerske** [comment]
I don't think that you have Ipopt 3.14.

The "checking whether user-supplied Pardiso library" check has been removed since 3.14.0 and the description of option value `pardiso` changed to "use the Pardiso package from pardiso-project.org" (https://coin-or.github.io/Ipopt/OPTIONS.html#OPT_linear_solver).

**Comment by TheCynosure** [comment]
I pulled the project down on Friday (October 22nd), from the 3.14.4 tag I believe, I am fairly positive it is 3.14 because I am on the stable/3.14 branch and the file `src/Common/config_ipopt_default.h` contains this line:
```
 /* Version number of project */
 #define IPOPT_VERSION "3.14.4"
```

**Comment by svigerske** [comment]
That sounds right, but the output you provide initially doesn't match 3.14.4, but 3.13 or earlier.
For example, there is no match for "user-supplied Pardiso library" in https://github.com/coin-or/Ipopt/blob/releases/3.14.4/configure.

I don't know how to help further.

**Comment by TheCynosure** [comment]
Commenting for others that stumble across this, although doubt anyone will have the same problem.

Turns out I had two Ipopt's nested within the same folder. The base folder was Ipopt 3.13 and a subfolder was Ipopt 3.14.4. No idea how I got to that configuration as I pulled down 3.14, but either way 3.13 somehow was okay with that Ipopt folder being there and it made for a weird build.
