### ISSUE TITLE
Running OptiToolbox on Matlab for Linux

### ISSUE THREAD

**Issue by bharswami** [coin-or/Ipopt#531]
I am using [Optitoolbox](https://www.inverseproblem.co.nz/OPTI/) for Matlab for Windows although its development has ceased. 
I now need to know how we can run OptiToolbox for Matlab for Linux systems. Alternatively, what are the other IPOPT solvers available for Matlab in Linux?

Regards
Bharath

**Comment by svigerske** [comment]
There are several mentions of Matlab interfaces to Ipopt in the docu: https://coin-or.github.io/Ipopt/#HOWTOUSE

**Comment by bharswami** [comment]
Hi Stefan
Thanks for your mail. From the list you sent, I am actually using
OptiToolbox (which has IPOPT) for Windows and the mex files for that is for
windows. Do you know of a way to get it installed in Linux Matlab?
Bharath

**Comment by svigerske** [comment]
No.
