### ISSUE TITLE
Using parallel computing

### ISSUE THREAD

**Issue by bharswami** [coin-or/Ipopt#533]
Hi,
What options need to be set for IPOPT to use multiple processors for computation (Parallel) - if available?

**Comment by svigerske** [comment]
Ipopt itself does not have any parallelization enabled, but the linear solvers and the linear algebra (LAPACK) packages that are used by Ipopt often offer some multithreading capabilities. See the options for HSL solvers, Pardiso, Spral, and Mumps for the linear solvers.

**Comment by bharswami** [comment]
Thanks Stefan.
