### ISSUE TITLE
running a ipopt instance on a GPU thread

### ISSUE THREAD

**Issue by patrickocal** [coin-or/Ipopt#536]
Hi folks,

we are looking to run a nonlinear optimisation _at different points on a large grid_. As a consequence, we want to run the optimisation in parallel on a gpu. As a canonical example, for each gridpoint in the nonlinear optimization problem, we would run a thread in the gpu that calls upon ipopt to solve that problem. Moreover, in order to fully benefit from working on the gpu, we want to set up the problem so that we can call functions such as "eval_f" locally (on the gpu). 

Is this just a matter of using the __device_ keyword to define the relevant functions on the gpu?

PS. I have arrived here having asked the following:
 https://github.com/mechmotum/cyipopt/issues/142

**Comment by path-doc** [comment]
Okay, so I have found the following:
2019 paper (Wachter et al)
https://arxiv.org/pdf/1909.08104.pdf
cuSolver (Nvidia's GPU-enabled linear solver):
https://docs.nvidia.com/cuda/cusolver/index.html

August 2021 paper:
https://arxiv.org/pdf/2106.13909.pdf

I now see that it's the solver that needs to be gpu enabled.

Thinking it might be better to expose a single problem to the gpu, but with all of the grid points included as constraints. Block-diagonal with each gridpoint generating a block of the bigger optimization problem.

Does this sound like the right way to go?
