### ISSUE TITLE
building IPOPT with MSVC INTEL and MSYS

### ISSUE THREAD

**Issue by jbensabat** [coin-or/Ipopt#545]
Hello 
I am trying to build IPOPT according to the above using MSYS 
I am following the guide but I bounce at the following line 

call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat"

call is not command recognized by bash
please help
best

jac

**Comment by svigerske** [comment]
If you refer to the commands
```
set MSYS2_PATH_TYPE=inherit
call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat"
C:\msys64\msys2.exe
exit 0
```
from https://coin-or.github.io/Ipopt/INSTALL.html#SYSTEMPACKAGES_MSYS, then these are meant to be called from a Windows terminal (cmd.exe). The line `C:\msys64\msys2.exe` will then start bash.
