### ISSUE TITLE
How to cross-compile Ipopt to arm linux

### ISSUE THREAD

**Issue by YGD159** [coin-or/Ipopt#548]
I want to cross-compile Ipopt to arm linux，please tell me how to cross-compile.
Any suggestions are greatly appreciated.

**Comment by svigerske** [comment]
You might want to try whether the general instructions for cross-compilation with autotools work: https://www.gnu.org/software/automake/manual/html_node/Cross_002dCompilation.html

As far as I know, compiling Ipopt for Linux on ARM64 should work (https://app.travis-ci.com/github/coin-or/Ipopt/jobs/535428295), but I never tried cross-compiling.
