### ISSUE TITLE
Can not find MA27 when compile Ipopt

### ISSUE THREAD

**Issue by reflector-li** [coin-or/Ipopt#569]
hello! I want to use ipopt on windows and have installed msys2 with mingw64.  I followed the instructions on the page, And the HSL package can be compiled successfully. But when I compile the Ipopt with the default configuration, the error appears like this:
![image](https://user-images.githubusercontent.com/51152320/160571846-a46e6664-47db-4cff-93f0-2bc6ae70d333.png)
it reminds that HSL package does not contain ma27, but I can find ma27 in this package. I searched some problem like this, and somebody said the file name should be changed to `ma27ad.f` from `ma27d.f`. The details are presented [here](https://stackoverflow.com/questions/58305144/trying-to-compile-hsl-to-get-ipopt) ，but it does not work for me. Did anyone meet same problem like this? I hope you can help me！thank you!

**Comment by svigerske** [comment]
You shouldn't have to rename files.
1. Get ThirdParty-HSL from https://github.com/coin-or-tools/ThirdParty-HSL/ and follow its [installation steps](https://github.com/coin-or-tools/ThirdParty-HSL/#installation-steps).
2. When running configure in ThirdParty-HSL, the output should show whether the source for MA27 has been found.
3. Build and install in ThirdParty-HSL (make, make install).
4. Configure Ipopt, using the same `--prefix` as for `ThirdParty-HSL`.

To check why Ipopt cannot find MA27 in the HSL library, have a look into the config.log created by Ipopt configure. Towards the ends there should be details on why the checks for `ma27ad_` and its variants have failed. It is normal that some of them fail, but at least one of them should succeed (if MA27 is indeed part of the coinhsl library).

**Comment by reflector-li** [comment]
> 
Thanks for your reply!
I have checked the config.log of compiling HSL, and the ma27 is found here. Actually, there are no error when compiling HSL.
![image](https://user-images.githubusercontent.com/51152320/160599518-d50ebf20-72f5-4d6a-8638-7b7cd99e4934.png)
Then I checked the log file of ipopt config process, The error was reported as below:
![image](https://user-images.githubusercontent.com/51152320/160599806-36f8972e-c31a-43d0-a82a-f639c5d35941.png)
It can not find `-lcoinhsl` . However, I don't understand what `-lcoinhsl` refers to, And I guass it is the path of library because I found the file `coinhsl.pc` in
> C:\msys64\usr\lib\pkgconfig\coinhsl.pc

Its contents are:

```text
prefix=/usr
#prefix=${pcfiledir}/../..
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include/coin-or/hsl

Name: HSL
Description: Harwell Subroutines Library
URL: https://github.com/coin-or-tools/ThirdParty-HSL
Version: 2.2.1
Cflags: -I${includedir}
Libs: -L${libdir} -lcoinhsl
Requires.private: 
#Libs: -L${libdir} -lcoinhsl -llapack -lblas   -LC:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0 -LC:/msys64/mingw64/bin/../lib/gcc -LC:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/lib/../lib -LC:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../lib -LC:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/lib -LC:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../.. -lgfortran -lmingw32 -lmoldname -lmingwex -lmsvcrt -lkernel32 -lquadmath -lm -lpthread -ladvapi32 -lshell32 -luser32
#Requires: 
```
How can I check the validity of `-lcoinhsl` ?

**Comment by svigerske** [comment]
`-lcoinhsl` refers to `libcoinhsl.a`, `libcoinhsl.so`, or `libcoinhsl.lib`. The `make install` in ThirdParty-HSL should have installed these into `/usr/lib`.

`coinhsl.pc` tells Ipopt how to link against Ipopt. To process coinhsl.pc, the configure of Ipopt calls `pkg-config -libs coinhsl`. This should print what is in the `Libs:` line of coinhsl.pc, i.e., `-L${libdir} -lcoinhsl`, but with `${libdir}` replaced by the value of variable `libdir`. If you follow the logic of the file, you see that `libdir=-L/usr/lib`.   
But from the config.log snippet, it seems that `-L/usr/lib` is lost somewhere. The pkg-config docu at https://people.freedesktop.org/~dbn/pkg-config-guide.html mentions that pkg-config may decide to drop `-L/usr/lib` because `/usr/lib` is a system standard library path. It is indeed strange that gcc wouldn't pick up a coinhsl lib that has been placed in `/usr/lib`.    
One way to work around this could be to specify `LDFLAGS=-L/usr/lib` as extra argument to Ipopt's configure.

**Comment by reflector-li** [comment]
> `-lcoinhsl` refers to `libcoinhsl.a`, `libcoinhsl.so`, or `libcoinhsl.lib`. The `make install` in ThirdParty-HSL should have installed these into `/usr/lib`.
> 
> `coinhsl.pc` tells Ipopt how to link against Ipopt. To process coinhsl.pc, the configure of Ipopt calls `pkg-config -libs coinhsl`. This should print what is in the `Libs:` line of coinhsl.pc, i.e., `-L${libdir} -lcoinhsl`, but with `${libdir}` replaced by the value of variable `libdir`. If you follow the logic of the file, you see that `libdir=-L/usr/lib`. But from the config.log snippet, it seems that `-L/usr/lib` is lost somewhere. The pkg-config docu at https://people.freedesktop.org/~dbn/pkg-config-guide.html mentions that pkg-config may decide to drop `-L/usr/lib` because `/usr/lib` is a system standard library path. It is indeed strange that gcc wouldn't pick up a coinhsl lib that has been placed in `/usr/lib`. One way to work around this could be to specify `LDFLAGS=-L/usr/lib` as extra argument to Ipopt's configure.

It works! Thank you very much! 
The strange thing is that I have installed MSYS2/MINGW64，but the system path `$PATH` doesn't include the path where gcc locates in. So everytime I want to compile these projects, I need to add the compiler path manually with
```shell
PATH=$PATH:/mingw64/bin
```
I don't know if that's why the compiler couldn't find the path `/usr/lib`.

**Comment by svigerske** [comment]
On my system, there were two icons, one for MinGW and one for MSys2, the former having GCC in the path.
