### ISSUE TITLE
MA86 Symbolic Factorization Timing

### ISSUE THREAD

**Issue by danieloliveira56** [coin-or/Ipopt#571]
I'm finding the reported Symbolic Factorization time a bit misleading for ma86.

What do you think about starting the timer before calling `mc68_order()`?

https://github.com/coin-or/Ipopt/blob/303929d1d4103554d91ae6bbf299fd3f4a6a237a/src/Algorithm/LinearSolvers/IpMa86SolverInterface.cpp#L261-L290

**Comment by svigerske** [comment]
Yes, make sense to me. Will also be consistent with the MA77 interface then. Good catch. I'll change it.
