### ISSUE TITLE
How to install Ipopt 3.12+ for Scip?

### ISSUE THREAD

**Issue by ChenZhenY** [coin-or/Ipopt#581]
Hello,
I am trying to compile Scip suite 8.0.0 which requires 3.12+ ipopt. But Scip is using cmake to build the program. I downloaded the 3.12+ ipopt code and compile and I don't have the .cmake files required by `find_package(ipopt)` in Scip cmake because ipopt uses makefiles to build and install.
Alternatively, if I install libipopt-dev via sudo apt-get, cmake can find the .cmake files, but the problem is that the latest version of ipopt I can get is 3.11.9. I wonder how to install 3.12+ ipopt using apt-get or build it in a way that we can have these .cmake files? 
Thanks in advance!

Msg from Scip cmake:
Could not find a package configuration file provided by "Ipopt" with any of
the following names:
IpoptConfig.cmake
ipopt-config.cmake
Add the installation prefix of "Ipopt" to CMAKE_PREFIX_PATH or set
"Ipopt_DIR" to a directory containing one of the above files. If "Ipopt"
provides a separate development package or SDK, be sure it has been
installed.

**Comment by svigerske** [comment]
That is odd. SCIP's cmake system brings a cmake module to check for Ipopt: https://github.com/scipopt/scip/blob/v80-bugfix/cmake/Modules/FindIPOPT.cmake It shouldn't look for a `.cmake` file from Ipopt. Instead, it processes the (buildsystem-independent) `ipopt.pc` that is installed by Ipopt. Maybe @fschloesser has some idea why you would get this message. The exact cmake command you executed and a full log would probably be helpful.

There is also a simple makefile system to build SCIP, you won't have to use cmake: https://scipopt.org/doc/html/md_INSTALL.php#MAKE

**Comment by fschloesser** [comment]
@svigerske is right, SCIP does not search for an ipopt cmake file. It tries to find the installation via package config or looks for the dependency file. Best is to use an ipopt version >= 3.13 and then just pass the installation directory to the cmake call for scip in the fashion `cmake .. -DIPOPT_DIR=/path/to/ipopt/installation`
