### ISSUE TITLE
Running Ipopt with LLVM's libc++ Fails

### ISSUE THREAD

**Issue by explocion** [coin-or/Ipopt#583]
I'm recently involved in a GPU project using CUDA, where clang is used as a cross compiler. To compile NVIDIA's thrust library, I used libc++ instead of libstdc++ as standard library due to some GNU style and LLVM style macro attribute issues. Although Ipopt compiles, it generates a runtime error as following:
```
libc++abi: terminating with uncaught exception of type std::length_error: basic_string::_M_create
```
I also tested my code with GNU libstdc++ and it works just fine. Perhaps libstdc++ should be listed as dependency in documentation.

**Comment by svigerske** [comment]
There is nothing in Ipopt that assumes GCC's implementation of the C++ standard library. It is supposed to work also with the one from clang and I believe I have seen it doing so. Of course, you will also have to use the headers from libc++ when compiling Ipopt, e.g., by compiling with clang. If that is the case, it would be good to debug what causes this exception.

**Comment by explocion** [comment]
Oh, I might linked that to a shared library of ipopt which is compiled using g++
