### ISSUE TITLE
Provide visibility to mumps_c

### ISSUE THREAD

**Issue by juanmanzanero** [coin-or/Ipopt#584]
Hello!

I am using **ipopt** to run optimal control problems (it is an open source project, [fastest-lap](https://github.com/juanmanzanero/fastest-lap)) and I explicitly use **mumps** (the function mumps_c) to solve the sensitivity analysis. In linux, since I compile everything myself, I can use the mumps library compiled by myself and that I am linking ipopt with. 

However, I want to provide a windows precompiled version of my software, for which I am using your precompiled ipopt libraries. Now I face the problem that I do not have mumps_c available, I guess it was maked as visibility hidden when linking ipopt. Can I ask you to provide public visibility to mumps_c? 

(For example, a nice approach would be to create a function ipopt_mumps_c which can have visibility public, that simply calls mumps_c (which can stay hidden))

I would appreciate this a lot, since if I install my own mumps version, I will never be sure that it is exactly the same as in ipopt.

Thank you in advance!!! And thank you for providing such a powerful tool.

Juan

**Comment by svigerske** [comment]
Adding a `ipopt_mumps_c()` sounds possible. Another option would be to build the Mumps lib as DLL (instead of a static lib that gets included into the Ipopt DLL) and to distribute also the corresponding Mumps LIB file. `mumps_c()` would be marked for DLL export then and you could link against the Mumps LIB file.

**Comment by juanmanzanero** [comment]
Thank you Stefan for the very quick answer. Both answers sound very good to me!

**Comment by svigerske** [comment]
The binaries attached to the [3.14.7 release](https://github.com/coin-or/Ipopt/releases/tag/releases%2F3.14.7) have MUMPS build as separate DLL and corresponding LIB and headers are redistributed.

**Comment by juanmanzanero** [comment]
Thank you very much Stefan!
