### ISSUE TITLE
IPOPT: disable "Problem has too few degrees of freedom"

### ISSUE THREAD

**Issue by cvanaret** [coin-or/Ipopt#585]
Dear all,

I'm writing a paper in which I compare [my own NLP solver](https://github.com/cvanaret/Uno) against state-of-the-art solvers on a subset of CUTEst problems.
On two problems (argauss and lewispol), IPOPT terminates with the error message "Problem has too few degrees of freedom", because there are more constraints than variables. Fair enough, either the problem is infeasible or some constraints are redundant.
However it's important that NLP methods be able to quickly detect (local) infeasibility. Therefore I'd like to run IPOPT anyway to monitor the number of iterations/evaluations until termination. Is it possible to disable this somehow?
Best,

Charlie

**Comment by svigerske** [comment]
As far as I know, there is no option to just "run Ipopt anyway". My general understanding is that the Ipopt datastructures are not setup in a way that they can handle overdetermined systems of equations.

If there are sufficiently many fixed variables, then Ipopt will already try automatically whether it can "activate" more degrees of freedom by relaxing the bounds on the fixed vars:
https://github.com/coin-or/Ipopt/blob/5e3f0bcdd07ebaeb34b743c4ac9058c03bc239cc/src/Interfaces/IpTNLPAdapter.cpp#L619-L629

If that isn't possible, then the only other option I am aware of is to try some experimental feature where Ipopt tries to detect redundant constraints and removes them: https://coin-or.github.io/Ipopt/OPTIONS.html#OPT_dependency_detector

**Comment by cvanaret** [comment]
Thank you @svigerske , I'll look into it!
