### ISSUE TITLE
Microsoft C++ exception: std::bad_alloc at memory location

### ISSUE THREAD

**Issue by Timbersaw-wangzw** [coin-or/Ipopt#586]
A `Microsoft C++ exception: std::bad_alloc at memory location` error occurred with running hs071_cpp example. The error codes are shown below
![image](https://user-images.githubusercontent.com/57893826/176857780-e4eea8e2-86dc-4825-901c-12080b012528.png)
### configuration
1. visual studio 2019
2. Ipopt-3.14.7-win64-msvs2019-md

**Comment by svigerske** [comment]
Would be good if you can debug this a bit. Try first whether it is also reproducible with the `-mdd` libs when you compile the example in a debug configuration (`-MDd`), too.

**Comment by Timbersaw-wangzw** [comment]
> Would be good if you can debug this a bit. Try first whether it is also reproducible with the `-mdd` libs when you compile the example in a debug configuration (`-MDd`), too.

Thank you! It works
