### ISSUE TITLE
How to compile Ipopt using LLVM? LLVM does not support Fortran compiler. 

### ISSUE THREAD

**Issue by zhumingpassional** [coin-or/Ipopt#591]
Ipopt needs HSL, which uses Fortran compiler. However, LLVM does not support Fortran compiler. 
How to solve this problem? Could you please give any suggestions? 

Thank you very much.

**Comment by svigerske** [comment]
Get a Fortran compiler and use that for the HSL codes. Maybe mixing GCC's gfortran or Intels's ifort with LLVM's clang will work. Just try it out.

Or, obviously, switch to GCC or Intel compilers for the C/C++ code as well.
