### ISSUE TITLE
Obtain point with least primal constraint violation when optimization fails

### ISSUE THREAD

**Issue by DanielDoehring** [coin-or/Ipopt#595]
Is there any way to retrieve the point with least primal constraint violation / infeasibility when, for instance, the iteration maximum is reached? Or is this up to the user to store candidates e.g. through the `intermediate_callback` function (using the `C++` interface)?

**Comment by svigerske** [comment]
There is no option for this in Ipopt itself, sorry. You'll have to implement this with the intermediate callback. Ipopt 3.14 extra added some functions (`TNLP::get_curr_iterate()`) to make it easier to receive the current iterate in [this callback](https://coin-or.github.io/Ipopt/classIpopt_1_1TNLP.html#a2f962a4c43464adb7928771af84503d6). While the intermediate callback is available in many interfaces to Ipopt, I'm not sure about `TNLP::get_curr_iterate()`. I know it's there for C++, C, Fortran, and Java.
