### ISSUE TITLE
./get.Mumps states that service unavailable. Error not found with Ipopt 3.12.7.

### ISSUE THREAD

**Issue by vimalrajayyappan** [coin-or/Ipopt#596]

**Comment by vimalrajayyappan** [comment]
Kindly help

**Comment by svigerske** [comment]
The MUMPS webpage has been down for some days (or weeks) by now. Try replacing the link in the `get.Mumps` script by
https://coin-or-tools.github.io/ThirdParty-Mumps/MUMPS_4.10.0.tar.gz

**Comment by vimalrajayyappan** [comment]
Hey man.. Thanks a lot. Thats really helpful(ON TIME).. 

Adding to that. Even Metis has the same issue. I used the link for Metis in the similar way.
