### ISSUE TITLE
No executable found for solver 'ipopt' in Ubuntu

### ISSUE THREAD

**Issue by kmylonas92** [coin-or/Ipopt#598]
I am trying to solve an optimization problem in `pyomo` by using `ipopt` as solver. My OS is `ubuntu`. However I am getting the following error"

```
pyomo.common.errors.ApplicationError: No executable found for solver 'ipopt'
```

I tried the solution mentioned [here][1], namely I did the following:

```
sudo apt-get install gcc g++ gfortran git cmake liblapack-dev pkg-config --install-recommends
```

and

```
sudo apt-get install coinor-libipopt-dev
```

But I still getting the same error. Any idea of how can I bypass it?

  [1]: https://gist.github.com/silgon/0892f410b025f2a82f2b

**Comment by svigerske** [comment]
Looking at https://packages.ubuntu.com/bionic/coinor-libipopt-dev, it seems that this package doesn't include an Ipopt executable.
Also it is a very old Ipopt version.

The "solution" in the GitHub gist also refers to some very old Ipopt.

The best is to just build Ipopt from scratch, using [up-to-date installation instructions](https://coin-or.github.io/Ipopt/INSTALL.html). For use in Pyomo, you need to get ASL.

There are also sources for precompiled binaries mentioned in the README: https://github.com/coin-or/Ipopt/blob/stable/3.14/README.md#precompiled-binaries
