### ISSUE TITLE
Error message: EXIT: Library loading failure

### ISSUE THREAD

**Issue by kmylonas92** [coin-or/Ipopt#599]
I have installed IPOPT by using the instructions from this [source](https://coin-or.github.io/Ipopt/INSTALL.html). Specifically, from the part `Download, build, and install dependencies` I followed the instructions for `ASL (Ampl Solver Library)`. However, I am getting the following error:

```
Ipopt 3.14.9: 
Exception of type: DYNAMIC_LIBRARY_FAILURE in file "/root/energy_efficiency_flexibility_services/Ipopt/src/Common/IpLibraryLoader.cpp" at line 67:
 Exception message: libhsl.so: cannot open shared object file: No such file or directory

EXIT: Library loading failure.
WARNING: Loading a SolverResults object with a warning status into
    model.name="unknown";
      - termination condition: other
      - message from solver: <undefined>
      
ERROR: evaluating object as numeric value: Pbat_ch[1]
        (object: <class 'pyomo.core.base.var._GeneralVarData'>)
    No value for uninitialized NumericValue object Pbat_ch[1]
```

Any idea of what is causing the error?

I have to mention that the model is solvable with IPOPT, since I have solved it successfully locally, but now I need to use it for production purposes in Linux.

**Comment by svigerske** [comment]
Ipopt needs to have at least one linear solver, either added at buildtime, or available at runtime. The error you get is because you didn't include any linear solver when building Ipopt and did not provide HSL libraries at runtime, either.

**Comment by kmylonas92** [comment]
Thanks for your answer. Although I have installed HSL successfully, I am getting `configure: error: Provided package HSL is not working or does not contain MA27. See config.log for details on failed checks.` when I am trying to configure Ipopt.

**Comment by svigerske** [comment]
Maybe you could look at config.log for details on failed checks.

**Comment by kmylonas92** [comment]
config.log does not seem to provide any further relevant information rather than the following:

```
configure:12737: checking for MA27
configure:12747: result: no
```

**Comment by svigerske** [comment]
Please check your build of ThirdParty-HSL and whether it indeed found the HSL sources and build them.

**Comment by kmylonas92** [comment]
I managed to fix it and I am mentioning here what I missed for future reference:

I have not installed correctly the coinhsl part and I figured out how to do it correctly with the readme of [this repo](https://github.com/coin-or-tools/ThirdParty-HSL).
