### ISSUE TITLE
No ThirdParty folder

### ISSUE THREAD

**Issue by chintanp** [coin-or/Ipopt#6]
This download does not have the ThirdParty folder with some starter wget scripts. It is found in the svn and tarball downloads. 

That folder can help newbies with installing the third-party modules.

**Comment by svigerske** [comment]
It is known that the GitHub mirror of Ipopt is not complete, i.e., misses dependencies. @tkralphs is working on something to make this possible. Until this happens, the GitHub clones are not meant for newbies.

**Comment by tkralphs** [comment]
The script that fetches dependencies automatically and allows monolithic builds from git checkouts similar to how things work with subversion is fully available and working. For example, check how the builds are done on [Travis](https://github.com/coin-or/Ipopt/blob/master/.travis.yml). To fetch depencies, download all third party sources (that it is possible to download automatically), you can do

```
git clone git@github.com:coin-or/Ipopt.git
cd Ipopt
git clone --branch=stable/0.8 https://github.com/coin-or-tools/BuildTools
./BuildTools/get.dependencies.sh fetch
./BuildTools/get.dependencies.sh build --quiet --test 
```

For help, just do 

```
./BuildTools/get.dependencies.sh
```

Hope this helps!
