### ISSUE TITLE
`inf_pr` as passed into `intermediate_callback` different from displayed & recalculated value

### ISSUE THREAD

**Issue by DanielDoehring** [coin-or/Ipopt#600]
While constructing a custom stopping criterion based on the primal infeasibility `inf_pr` within [`intermediate_callback`](https://coin-or.github.io/Ipopt/classIpopt_1_1TNLP.html#a2f962a4c43464adb7928771af84503d6) I observed that `inf_pr` as passed into `intermediate_callback` is different from what is displayed when using the default `print_level = 5`.

I checked this by adding 

`std::cout << std::endl << "Check: " << iter << " " << obj_value << " " << inf_pr << " "  << inf_du << std::endl;` 

to the `intermediate_callback` function body.

At the same time, if one recalculates the maximum norm of the constraint violations, i.e., for the [`hs_071` example](https://github.com/coin-or/Ipopt/tree/stable/3.14/examples/hs071_cpp) as

`std::cout << "Inf_pr recomputed: " << std::max(constraint_violation[0], constraint_violation[1]) << std::endl;`

one obtains the same value as printed by Ipopt.

To reproduce: I am using `Ipopt 3.14.10` with `MUMPS 5.5.0` with default configuration file. 
The adjustments I made in the `hs_071` example are:

Line 39 of [`hs_071_nlp.hpp`](https://github.com/coin-or/Ipopt/blob/6378c1bccb8c6911883289f249e5fda40dadc782/examples/hs071_cpp/hs071_nlp.hpp#L39):

```diff
- bool printiterate = false   /**< whether to print the iterate at each iteration */
+ bool printiterate = true   /**< whether to print the iterate at each iteration */
```

And within `intermediate_callback` of [`hs_071_nlp.cpp`](https://github.com/coin-or/Ipopt/blob/stable/3.14/examples/hs071_cpp/hs071_nlp.cpp):

```diff
// [TNLP_intermediate_callback]
bool HS071_NLP::intermediate_callback(
   AlgorithmMode              mode,
   Index                      iter,
   Number                     obj_value,
   Number                     inf_pr,
   Number                     inf_du,
   Number                     mu,
   Number                     d_norm,
   Number                     regularization_size,
   Number                     alpha_du,
   Number                     alpha_pr,
   Index                      ls_trials,
   const IpoptData*           ip_data,
   IpoptCalculatedQuantities* ip_cq
)
{
   if( !printiterate_ )
   {
      return true;
   }

   Number x[4];
   Number x_L_viol[4];
   Number x_U_viol[4];
   Number z_L[4];
   Number z_U[4];
   Number compl_x_L[4];
   Number compl_x_U[4];
   Number grad_lag_x[4];

   Number g[2];
   Number lambda[2];
   Number constraint_violation[2];
   Number compl_g[2];

   bool have_iter = get_curr_iterate(ip_data, ip_cq, false, 4, x, z_L, z_U, 2, g, lambda);
   bool have_viol = get_curr_violations(ip_data, ip_cq, false, 4, x_L_viol, x_U_viol, compl_x_L, compl_x_U, grad_lag_x, 2, constraint_violation, compl_g);

+  std::cout << std::endl << "Check: " << iter << " " << obj_value << " " << inf_pr << " "  << inf_du << std::endl;
+  std::cout << "Inf_pr recomputed: " << std::max(constraint_violation[0], constraint_violation[1]) << std::endl;

+  /*
   printf("Current iterate:\n");
   printf("  %-12s %-12s %-12s %-12s %-12s %-12s %-12s\n", "x", "z_L", "z_U", "bound_viol", "compl_x_L", "compl_x_U", "grad_lag_x");
   for( int i = 0; i < 4; ++i )
   {
      if( have_iter )
      {
         printf("  %-12g %-12g %-12g", x[i], z_L[i], z_U[i]);
      }
      else
      {
         printf("  %-12s %-12s %-12s", "n/a", "n/a", "n/a");
      }
      if( have_viol )
      {
         printf(" %-12g %-12g %-12g %-12g\n", x_L_viol[i] > x_U_viol[i] ? x_L_viol[i] : x_U_viol[i], compl_x_L[i], compl_x_U[i], grad_lag_x[i]);
      }
      else
      {
         printf(" %-12s %-12s %-12s %-12s\n", "n/a", "n/a", "n/a", "n/a");
      }
   }

   printf("  %-12s %-12s %-12s %-12s\n", "g(x)", "lambda", "constr_viol", "compl_g");
   for( int i = 0; i < 2; ++i )
   {
      if( have_iter )
      {
         printf("  %-12g %-12g", g[i], lambda[i]);
      }
      else
      {
         printf("  %-12s %-12s", "n/a", "n/a");
      }
      if( have_viol )
      {
         printf(" %-12g %-12g\n", constraint_violation[i], compl_g[i]);
      }
      else
      {
         printf(" %-12s %-12s\n", "n/a", "n/a");
      }
   }
+  */
   return true;
}
// [TNLP_intermediate_callback]
```
I compiled the example as 

```
g++ -std=c++11 -Ofast -march=native  `PKG_CONFIG_PATH=/usr/local/lib/pkgconfig: pkg-config --cflags ipopt`  -c -o hs071_nlp.o hs071_nlp.cpp  
g++ -std=c++11 -Ofast -march=native  -o hs071_nlp.exe hs071_nlp.o hs071_main.o  `PKG_CONFIG_PATH=/usr/local/lib/pkgconfig: pkg-config --libs ipopt`
```
and obtained the output 

```
$ ./hs071_nlp.exe 

******************************************************************************
This program contains Ipopt, a library for large-scale nonlinear optimization.
 Ipopt is released as open source code under the Eclipse Public License (EPL).
         For more information visit https://github.com/coin-or/Ipopt
******************************************************************************

This is Ipopt version 3.14.10, running with linear solver MUMPS 5.5.0.

Number of nonzeros in equality constraint Jacobian...:        4
Number of nonzeros in inequality constraint Jacobian.:        4
Number of nonzeros in Lagrangian Hessian.............:       10

Total number of variables............................:        4
                     variables with only lower bounds:        0
                variables with lower and upper bounds:        4
                     variables with only upper bounds:        0
Total number of equality constraints.................:        1
Total number of inequality constraints...............:        1
        inequality constraints with only lower bounds:        1
   inequality constraints with lower and upper bounds:        0
        inequality constraints with only upper bounds:        0


Check: 0 16.1097 11.2434 0.527598
Inf_pr recomputed: 11.2434
iter    objective    inf_pr   inf_du lg(mu)  ||d||  lg(rg) alpha_du alpha_pr  ls
   0  1.6109693e+01 1.12e+01 5.28e-01   0.0 0.00e+00    -  0.00e+00 0.00e+00   0

Check: 1 17.4104 0.838228 22.4933
Inf_pr recomputed: 0.748946
   1  1.7410406e+01 7.49e-01 2.25e+01  -0.3 7.97e-01    -  3.19e-01 1.00e+00f  1

Check: 2 18.0016 0.0106104 4.96253
Inf_pr recomputed: 0.00752318
   2  1.8001613e+01 7.52e-03 4.96e+00  -0.3 5.60e-02   2.0 9.97e-01 1.00e+00h  1

Check: 3 17.1995 0.0904256 0.423862
Inf_pr recomputed: 0.0399534
   3  1.7199482e+01 4.00e-02 4.24e-01  -1.0 9.91e-01    -  9.98e-01 1.00e+00f  1

Check: 4 16.941 0.208847 0.0457835
Inf_pr recomputed: 0.15938
   4  1.6940955e+01 1.59e-01 4.58e-02  -1.4 2.88e-01    -  9.66e-01 1.00e+00h  1

Check: 5 17.0034 0.0229151 0.00841621
Inf_pr recomputed: 0.0215739
   5  1.7003411e+01 2.16e-02 8.42e-03  -2.9 7.03e-02    -  9.68e-01 1.00e+00h  1

Check: 6 17.014 0.000259262 8.64695e-05
Inf_pr recomputed: 0.000202585
   6  1.7013974e+01 2.03e-04 8.65e-05  -4.5 6.22e-03    -  1.00e+00 1.00e+00h  1

Check: 7 17.014 2.87749e-07 2.18243e-07
Inf_pr recomputed: 2.76267e-07
   7  1.7014017e+01 2.76e-07 2.18e-07 -10.3 1.43e-04    -  9.99e-01 1.00e+00h  1

Number of Iterations....: 7

                                   (scaled)                 (unscaled)
Objective...............:   1.7014017031783709e+01    1.7014017031783709e+01
Dual infeasibility......:   2.1824331205753585e-07    2.1824331205753585e-07
Constraint violation....:   2.7626678900105617e-07    2.7626678900105617e-07
Variable bound violation:   0.0000000000000000e+00    0.0000000000000000e+00
Complementarity.........:   1.0473361552967069e-07    1.0473361552967069e-07
Overall NLP error.......:   2.7626678900105617e-07    2.7626678900105617e-07


Number of objective function evaluations             = 8
Number of objective gradient evaluations             = 8
Number of equality constraint evaluations            = 8
Number of inequality constraint evaluations          = 8
Number of equality constraint Jacobian evaluations   = 8
Number of inequality constraint Jacobian evaluations = 8
Number of Lagrangian Hessian evaluations             = 7
Total seconds in IPOPT                               = 0.006

EXIT: Optimal Solution Found.


Solution of the primal variables, x
x[0] = 1
x[1] = 4.743
x[2] = 3.82115
x[3] = 1.37941


Solution of the bound multipliers, z_L and z_U
z_L[0] = 1.08787
z_L[1] = 4.63582e-09
z_L[2] = 9.08745e-09
z_L[3] = 8.55595e-09
z_U[0] = 4.47003e-09
z_U[1] = 4.07523e-07
z_U[2] = 1.18979e-08
z_U[3] = 6.39875e-09


Objective value
f(x*) = 17.014

Final value of the constraints:
g(0) = 25
g(1) = 40


*** The problem solved!
```

As you can see, `iter`, `obj_value` and `inf_du` are the same as printed by default, but `inf_pr` takes some different value.

**Comment by svigerske** [comment]
The value passed to the intermediate callback should correspond to the internal problem representation of Ipopt.
An inequality l <= g(x) <= u is there reformulated into g(x) - s = 0, l <= s <= u, with new slack variable s, and the violation is measured as |g(x)-s|.
See also
- https://github.com/coin-or/Ipopt/blob/stable/3.14/src/Algorithm/IpOptErrorConvCheck.cpp#L180
- https://github.com/coin-or/Ipopt/blob/stable/3.14/src/Algorithm/IpIpoptCalculatedQuantities.cpp#L2570-L2610

And then there is also scaling.

Using option [inf_pr_output](https://coin-or.github.io/Ipopt/OPTIONS.html#OPT_inf_pr_output), you can tell Ipopt to print the violation of the internal NLP to the log, but there is no option to tell Ipopt to get the value for the original NLP as inf_pr in the intermediate callback.
However, you should be able to request this value from the IpCQ object passed to the intermediate callback:
https://coin-or.github.io/Ipopt/classIpopt_1_1IpoptCalculatedQuantities.html#a10b3fcfcf4d2bd8fde1eb0533065aae4

**Comment by DanielDoehring** [comment]
Accessing the primal infeasibility of the "original" problem  through `IpIpoptCalculatedQuantities.unscaled_curr_nlp_constraint_violation(ENormType NormType = NORM_MAX)` works, thanks! 

EDIT: 
This works only in regular mode, i.e., if `AlgorithmMode = REGULARMODE = 0`. 
If Ipopt is in restoration phase, i.e., `AlgorithmMode = RESTORATIONPHASEMODE = 1` `IpIpoptCalculatedQuantities.unscaled_curr_nlp_constraint_violation(ENormType NormType = NORM_MAX)` returns always `0`.

This looked very much like a bug to me, given that all other variables are actually the same.

**Comment by svigerske** [comment]
I think this was intended. Given that there is the option `inf_pr_output`, I have the impression that originally also the log printed the violation of the scaled internal problem and this was changed later to print the one of the unscaled original one. The dual infeasibility reported corresponds to the internal scaled problem, too, which means that what you get in the intermediate callback is actually more consistent than what you see in the log by default.

Many of these values are of interest, as they are all compared to the various tolerances for the stopping criterion, but not all are printed to the iteration log line and not all are given explicitly to the intermediate callback.

Just changing the `inf_pr` that is given to the intermediate callback may break existing code.
So I'll just update the docu. The statement "The information provided by the entities in the argument list correspond to what Ipopt prints in the iteration summary" is indeed wrong.
