### ISSUE TITLE
libipoptamplinterface.so.3: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by kmylonas92** [coin-or/Ipopt#601]
I am following the instructions for the installation of IPOPT from here and I am getting the following error:

```
/usr/local/bin/ipopt: error while loading shared libraries: libipoptamplinterface.so.3: cannot open shared object file: No such file or directory
ERROR: Solver (ipopt) returned non-zero return code (127)
ERROR: See the solver log above for diagnostic information.
```

Any idea of what is wrong?

**Comment by svigerske** [comment]
The lib should be in `/usr/local/lib`, I guess. If it is not there, checkout why it wasn't installed when you installed Ipopt. If it is there, make sure it is found, e.g., due to the rpath in the `ipopt` executable or search paths of the dynamic linker (`ld`).
