### ISSUE TITLE
IPOPT w/SPRAL in WSL

### ISSUE THREAD

**Issue by chemrgineer** [coin-or/Ipopt#613]
Hi, I'm trying IPOPT compiling with SPRAL support. First I compiled SPRAL only CPU support. I follewed [this](https://github.com/ralna/spral/blob/master/COMPILE.md) instructions. I installed spral files my home directory. Then I cloned latest IPOPT repo from github. Then I run 
`../configure --with-spral-lflags="-L/home/erturk/spral/lib -lspral -lgfortran -lhwloc -lm -lcoinmetis -lopenblas -lstdc++ -fopenmp" --with-spral-cflags="-I/home/erturk/spral/include"` 
and I get:
```
configure: Compiler flags were "-I/home/erturk/spral/include". Use --with-spral-cflags to overwrite. Check config.log for details of failed compile attempt.
configure: Linker flags are "-L/home/erturk/spral/lib -lspral -lgfortran -lhwloc -lm -lcoinmetis -lopenblas -lstdc++ -fopenmp". Use --with-spral-lflags to overwrite. Check config.log for details of failed link attempt.
configure: error: user-specified flags for Spral do not work.
```
Where I make mistake dont know. Thanks for answers.

**Comment by svigerske** [comment]
As the message says, please check config.log for details.

**Comment by chemrgineer** [comment]
I found my mistake. I installed METIS from ubuntu official repositories (not compiled coinmetis), so I changed `-lcoinmetis` to `-lmetis` its worked.  Thanks.
