### ISSUE TITLE
Undefined References to libcoinmumps IPOPT ARM64

### ISSUE THREAD

**Issue by defencedog** [coin-or/Ipopt#614]
I am having these errors while compiling IPOPT ...I have successfully compiled `metis` & `mumps` 

My build command `FC=gfortran-11 CC=clang ./configure --prefix=$PREFIX/local --with-asl --with-lapack="-L/data/data/com.termux/files/usr/include/openblas/ -lopenblas"  --with-mumps-lfags=$PREFIX/local/lib/libcoinmumps.so   --build=aarch64-linux-android `

```
make[3]: Leaving directory '/data/data/com.termux/files/home/Ipopt-releases-3.14.4/src'
Making all in Apps/AmplSolver
make[3]: Entering directory '/data/data/com.termux/files/home/Ipopt-releases-3.14.4/src/Apps/AmplSolver'
  CXX      ampl_ipopt.o
  CXX      AmplTNLP.lo
  CXXLD    libipoptamplinterface.la
  CXXLD    ipopt
libtool: warning: '-version-info' is ignored for programs
/data/data/com.termux/files/usr/bin/ld: /data/data/com.termux/files/usr/local/lib/libcoinmumps.so: undefined reference to `metis_setdefaultoptions_'
/data/data/com.termux/files/usr/bin/ld: /data/data/com.termux/files/usr/local/lib/libcoinmumps.so: undefined reference to `metis_nodend_'
/data/data/com.termux/files/usr/bin/ld: /data/data/com.termux/files/usr/local/lib/libcoinmumps.so: undefined reference to `METIS_SetDefaultOptions'
/data/data/com.termux/files/usr/bin/ld: /data/data/com.termux/files/usr/local/lib/libcoinmumps.so: undefined reference to `METIS_PartGraphKway'
collect2: error: ld returned 1 exit status
make[3]: *** [Makefile:533: ipopt] Error 1
make[3]: Leaving directory '/data/data/com.termux/files/home/Ipopt-releases-3.14.4/src/Apps/AmplSolver'
make[2]: *** [Makefile:1575: all-recursive] Error 1
make[2]: Leaving directory '/data/data/com.termux/files/home/Ipopt-releases-3.14.4/src'
make[1]: *** [Makefile:872: all] Error 2
make[1]: Leaving directory '/data/data/com.termux/files/home/Ipopt-releases-3.14.4/src'
make: *** [Makefile:619: all-recursive] Error 1

```

**Comment by svigerske** [comment]
Maybe something went wrong when building the Mumps lib, so it is missing a dependency on Metis?
If you build Metis as shared lib, then it should be listed by `ldd /data/data/com.termux/files/usr/local/lib/libcoinmumps.so`.
If you build it as static lib, then it should have been linked into `libcoinmumps.so` when this lib was created.

You can call `make` with `V=1` to see linking commands.

**Comment by defencedog** [comment]
@svigerske It has been like x2 days while I try to build ipopt... so plz bear with me!
The above mentioned `undefined references` are resolved when I add `--with-mumps-cflags=$PREFIX/local/include/coin-or/mumps` alongwith  `--with-mumps-lflags=$PREFIX/local/lib/libcoinmumps.so`

Now the next fatal error is `Algorithm/LinearSolvers/IpMumpsSolverInterface.cpp:24:10: fatal error: mumps_compat.h: No such file or directory` 

It seems that header files are located in `$PREFIX/local/include/coin-or/mumps` thus these `.cpp` files are to be edited & give absolute locations. What is your view?

**Comment by svigerske** [comment]
The cflags option gives the arguments passed to the C/C++ compiler. To specify an additional header path, also clang uses `-I` flags, so it should be `--with-mumps-cflags=-I$PREFIX/local/include/coin-or/mumps`.

But you should not have to specify any `--with-mumps-cflags` or `--with-mumps-lflags`. Ipopt's configure should just pick up the Mumps that has been installed under the same prefix before.    
There is also no use for `--with-asl`.

**Comment by defencedog** [comment]
Ok I did like you instructed removed the extra flags: `make clean && FC=gfortran-11 CC=clang ./configure --prefix=$PREFIX/local --with-lapack="-L/data/data/com.termux/files/usr/include/openblas/ -lopenblas"   --build=aarch64-linux-android   && make -j4`

While configuring it successfully detected 
```
checking for package ASL... yes
checking for package Mumps... yes
```
But `undefined references` popped up & build failed...
I will resume frrom previous successful checkpoint

**Comment by defencedog** [comment]
@svigerske Ok now previous errors are gone & a different one appears. Google search does indicate its not be alone out there. Google string for error `libipopt.so: undefined reference to dmumps_c`

This error occurs at the very last step of build

Build command 
```make clean && FC=gfortran-11 CC=clang ./configure --prefix=/data/data/com.termux/files/usr/local/ --with-lapack="-L/data/data/com.termux/files/usr/include/openblas/ -lopenblas" --with-mumps-cflags=-I/data/data/com.termux/files/usr/local/include/coin-or/mumps  --build=aarch64-linux-android   && make -j4```

```
make[3]: Leaving directory '/data/data/com.termux/files/home/Ipopt-releases-3.14.4/src'
Making all in Apps/AmplSolver
make[3]: Entering directory '/data/data/com.termux/files/home/Ipopt-releases-3.14.4/src/Apps/AmplSolver'
  CXX      ampl_ipopt.o
  CXX      AmplTNLP.lo
  CXXLD    libipoptamplinterface.la
  CXXLD    ipopt
libtool: warning: '-version-info' is ignored for programs
/data/data/com.termux/files/usr/bin/ld: /data/data/com.termux/files/home/Ipopt-releases-3.14.4/src/.libs/libipopt.so: undefined reference to `dmumps_c'
collect2: error: ld returned 1 exit status
make[3]: *** [Makefile:533: ipopt] Error 1
make[3]: Leaving directory '/data/data/com.termux/files/home/Ipopt-releases-3.14.4/src/Apps/AmplSolver'
make[2]: *** [Makefile:1575: all-recursive] Error 1
make[2]: Leaving directory '/data/data/com.termux/files/home/Ipopt-releases-3.14.4/src'
make[1]: *** [Makefile:872: all] Error 2
make[1]: Leaving directory '/data/data/com.termux/files/home/Ipopt-releases-3.14.4/src'
make: *** [Makefile:619: all-recursive] Error 1
```
My header files are at
```
/data/data/com.termux/files/usr/local/include/coin-or/mumps/mumps_c_types.h
/data/data/com.termux/files/usr/local/include/coin-or/mumps/mumps_mpi.h
/data/data/com.termux/files/usr/local/include/coin-or/mumps/mumps_compat.h
/data/data/com.termux/files/usr/local/include/coin-or/mumps/mumps_int_def.h
/data/data/com.termux/files/usr/local/include/coin-or/mumps/dmumps_c.h
/data/data/com.termux/files/usr/local/include/coin-or/mumps/smumps_c.h
```
May be this helps to investigate; finding `dmumps` in all files. findTXT is my custom bash command....
```
~/Ipopt-releases-3.14.4 $ findTXT dmumps 
./src/Algorithm/LinearSolvers/IpMumpsSolverInterface.cpp:#include "dmumps_c.h"
./src/Algorithm/LinearSolvers/IpMumpsSolverInterface.cpp:#define mumps_c dmumps_c
./src/Algorithm/LinearSolvers/.deps/IpMumpsSolverInterface.Plo:
/data/data/com.termux/files/usr/local/include/coin-or/mumps/dmumps_c.h \
./src/Algorithm/LinearSolvers/.deps/IpMumpsSolverInterface.Plo:/data/data/com.termux/files/usr/local/include/coin-or/mumps/dmumps_c.h:
grep: ./src/Algorithm/LinearSolvers/.libs/IpMumpsSolverInterface.o: binary file matches
grep: ./src/.libs/libipopt.so: binary file matches
```

**Comment by svigerske** [comment]
As said in https://github.com/coin-or/Ipopt/issues/614#issuecomment-1312712402, something seems to be wrong with the Metis or Mumps lib that you build, if Metis symbols are unresolved in the Mumps lib. You just have to figure out what that is. `ldd`, `nm`, etc are your friends on this quest.

With your last attempt, you leave out the Mumps lib by specifying `--with-mumps-cflags` but leaving out `---with-mumps-lflags`. So no wonder that there is an unresolved symbol `dmumps_c`.

**Comment by defencedog** [comment]
@svigerske Beyond doubt its the **problem with `ipopt` package** & developer need to modify the build algo. I explicitly have to add `-lcoinmumps` & build is successful. It should've taken care of it automatically

`FC=gfortran-11 CC=clang ./configure --prefix=/data/data/com.termux/files/usr/local/ --with-lapack="-L/data/data/com.termux/files/usr/include/openblas/ -lopenblas" --with-mumps="-L/data/data/com.termux/files/usr/local/lib/ -lcoinmumps  -I/data/data/com.termux/files/usr/local/include/coin-or/mumps/" --build=aarch64-linux-android && make -j4`
