### ISSUE TITLE
Feature request - recovery of the best iteration

### ISSUE THREAD

**Issue by enricostragiotti** [coin-or/Ipopt#615]
Hello,
I have a feature request for IPOPT. I'm working at the moment on a problem that falls outside of the design domain very often. It would be interesting to add a feature that permits to recover the best iterate (based on overall NLP error for example) of the last X iterations when for example `MAX_ITER` is reached (I'm assuming that it is possible to store at least the design variable vector of the last X iterates). For example, CVXPY already does that when using MOSEK or ECOS solver. This feature would permit to have an approximated solution for highly non-linear problems that often "jump" inside and outside of the design domain. That way, the iteration returned to the user will be, for example, the last respecting the constraints instead of the very last of the optimization. 
Thank you very much!

**Comment by svigerske** [comment]
We have the intermediate callback (https://coin-or.github.io/Ipopt/INTERFACES.html#INTERFACE_CPP_ADDITIONAL) that would allow you to build this feature on your side. You can access there every iterate and the current constraint violation and store the point away if you think you may need it later.    
It means more effort on your side to implement this, but does not reduce code complexity on the Ipopt side :).

**Comment by enricostragiotti** [comment]
I will try that way! Thanks!
