### ISSUE TITLE
Failed tests when linking Ipopt with Intel MKL OneAPI

### ISSUE THREAD

**Issue by zornsllama** [coin-or/Ipopt#624]
Hi, I am trying to install Ipopt with the BLAS/LAPACK and PARDISO routines in the Intel MKL OneAPI. When I run the configure script with the --with-lapack-lflags indicating the MKL location, there are no issues and the MKL libraries are found. However, when I then run `make test`, the tests all fail and give the error

`/home/---/software/Ipopt/build/test/.libs/hs071_cpp: error while loading shared libraries: libmkl_intel_lp64.so.2: cannot open shared object file: No such file or directory`

Any help would be greatly appreciated!

**Comment by zornsllama** [comment]
Just didn't have the libraries in my path! Sorry, new to this!

**Comment by svigerske** [comment]
You should make sure that the libs are found by the dynamic linker at runtime. Set `LD_LIBRARY_PATH` or include the dir in your `/etc/ld.so.conf`.
