### ISSUE TITLE
Ipopt runtime loading issue

### ISSUE THREAD

**Issue by fambr** [coin-or/Ipopt#627]
Hello, 
my name is Francesco Ambrogi. I am trying to import ipopt-3.dll from python (anaconda3 shell) on windows

`import ctypes
lib = ctypes.CDLL("ipopt-3.dll")`

and I am getting a system message related to  runtime missing/mismatch. I wouldassume this is related to Intel Fortran.
![image](https://user-images.githubusercontent.com/95291048/212290867-7c3fbcc6-7169-4864-8cc0-7e6cb32f7fd5.png)

Could you please indicate which Intel oneAPI is used to compile and which runtime are eventually required/supported?

Thanks in advance
Francesco

**Comment by svigerske** [comment]
I'm going to assume you use a DLL that is attached to some of the recent releases (https://github.com/coin-or/Ipopt/releases).

For those, I actually hoped to have included the Intel Fortran runtime libraries necessary to load the DLL, e.g., `libifcoremd.dll` should be there.

Anyway, the README.txt lists the compiler versions:
```
Intel(R) Fortran Intel(R) 64 Compiler Classic for applications running on Intel(R) 64, Version 2021.2.0 Build 20210228_000000
```

**Comment by juanmanzanero** [comment]
Hi Francesco and Stefan,

Just to add a small detail on the issue, the DLLs that are dependent on coinmumps.dll after a symbol dump are:

- Dump of file coinmumps-3.dll

> File Type: DLL
> 
>   Image has the following dependencies:
> 
>     libiomp5md.dll
>     libifcoremd.dll
>     libmmd.dll
>     svml_dispmd.dll
>     KERNEL32.dll
>     VCRUNTIME140.dll
>     api-ms-win-crt-heap-l1-1-0.dll
>     api-ms-win-crt-stdio-l1-1-0.dll
>     api-ms-win-crt-environment-l1-1-0.dll
>     api-ms-win-crt-filesystem-l1-1-0.dll
>     api-ms-win-crt-runtime-l1-1-0.dll
>     api-ms-win-crt-string-l1-1-0.dll
>     api-ms-win-crt-time-l1-1-0.dll
>     api-ms-win-crt-utility-l1-1-0.dll
>     api-ms-win-crt-convert-l1-1-0.dll

Even though if depends on libifcoremd.dll, you can see it still depends on other DLLs, `api-ms-win-crt-*.dll`. After a quick search, it might be related to the [Windows C Runtime](https://helpx.adobe.com/in/download-install/kb/error_on_launch.html)

**Comment by fambr** [comment]
Hi Stefan and Juan,
thanks for your responses.

I installed the Intel Fortran runtime closest to the compiled version [2021.4.0](https://registrationcenter-download.intel.com/akdlm/irc_nas/18215/w_ifort_runtime_p_2021.4.0.3556.exe) but am still unsuccessful in loading the dll.

I suspect some conflict with my machine setup; I will try to investigate and eventually test on a different computer.

For the time being I think you can close the case.

Thanks
Francesco

**Comment by svigerske** [comment]
Maybe check that no other Intel runtime library was already loaded before.

Using `dumpbin -symbols` should help to figure out which symbols are provided by a library.

The symbol name (`for_...`) rather sounds like Intel Fortran than MSVC to me.

Process Monitor from the SysInternals Suite is usually a nice tool to see what libs a process is actually loading, and where it is looking for libs.

**Comment by juanmanzanero** [comment]
Hello Stefan,

Just FYI, Francesco was able to solve the issue by passing the library full path to `CDLL`.

Just in case another use needs to fix this problem.

Cheers,

Juan
