### ISSUE TITLE
problem about :Invalid number in NLP function or derivative detected

### ISSUE THREAD

**Issue by mupia123** [coin-or/Ipopt#629]
Hi,
I just started to use the Ipopt to solve some problems, there is a problem I don't know why and how to fix it:
I just changed some constraints values, just like change -4 to 1, then it comes to a error:
Invalid number in NLP function or derivative detected(Exception of type: Eval_Error in file "../../src/Algorithm/IpOrigIpoptNLP.cpp" at line 589: Exception message: Error evaluating the equality constraints).
when I changed the values back to -4, it was solved, I can't find where is the error, and I tried to change my initialGuess points, it didn't work, I double checked my constraints, didn't find error. now I don't know how to fix it!
Any help would be greatly appreciated! Thanks!!!

**Comment by svigerske** [comment]
This means that some of your evaluation functions returned a value that is not a finite number (e.g., Inf, NaN).

If you increase the print_level to 7 or higher, you may get more information where the invalid number occurred. But adding some asserts checking for [std::isfinite](https://en.cppreference.com/w/cpp/numeric/math/isfinite) on the values you return to Ipopt may also help. Note that your eval functions should return `false` if a point cannot be evaluated, i.e., is outside the domain of your function.
