### ISSUE TITLE
new version

### ISSUE THREAD

**Issue by saeedBabaSonic** [coin-or/Ipopt#632]
Can you please provide a guidance on how you built this binary?
also, it would be great to have binary of the newer release which is 3.14.

**Comment by svigerske** [comment]
Installation instructions are in the docu: https://coin-or.github.io/Ipopt/INSTALL.html

Regarding precompiled libraries, see the README: https://github.com/coin-or/Ipopt#precompiled-binaries

Also check whether the package manager of your OS distribution provides uptodate Ipopt binaries. Conda or Conda-Forge may also have some.
