### ISSUE TITLE
Follow-up to #637 (missing headers for using custom linear solver)

### ISSUE THREAD

**Issue by joaospinto** [coin-or/Ipopt#641]
This is in relation with #618 and #637. I think there is a bug in 29ea7c6958304d8c1d9bc9d1f4a587dee47a3216. Specifically, you wrote Algorithm/IpStdAugSystemSolver.cpp when you meant Algorithm/IpStdAugSystemSolver.hpp. Therefore, that header is still missing.

There are also more files missing:
Ipopt/src/Algorithm/LinearSolvers/IpTSymLinearSolver.hpp
Ipopt/src/Algorithm/LinearSolvers/IpSlackBasedTSymScalingMethod.hpp
Ipopt/src/Algorithm/LinearSolvers/IpTSymScalingMethod.hpp
Ipopt/src/Algorithm/LinearSolvers/IpTripletToCSRConverter.hpp

I would suggest coming up with a more automated method for adding header files to the Makefile, or possibly (and perhaps I don't have all the context here) even integrating this repository with some of the popular build systems (e.g. Bazel and CMake).

**Comment by joaospinto** [comment]
CC @svigerske

**Comment by svigerske** [comment]
Thank you for the fix.

And am I glad that we already have the popular autotools buildsystem integrated. :)
