### ISSUE TITLE
Dependency issue: libopenblas

### ISSUE THREAD

**Issue by Fabian42** [coin-or/Ipopt#643]
I'm trying to upgrade. I have `openblas` 0.3.21-4 installed, not `libopenblas`. Output looks like this:

```
/usr/bin/ld: warning: libopenblas.so.3, needed by /usr/lib/gcc/x86_64-pc-linux-gnu/12.2.1/../../../../lib/libcoinmumps.so, not found (try using -rpath or -rpath-link)
chmod u+x ./run_unitTests
./run_unitTests
 
Running unitTests...
 
Testing AMPL Solver Executable...
0 
 ---- 8< ---- Start of test program output ---- 8< ----
/home/fabian/.cache/yay/coin-or-ipopt/src/build/src/Apps/AmplSolver/.libs/ipopt: error while loading shared libraries: libopenblas.so.3: cannot open shared object file: No such file or directory
 ---- 8< ----  End of test program output  ---- 8< ----
[…then that a bunch of times…]
    ******** Test FAILED! ********
Test program existed with nonzero status.
make[1]: *** [Makefile:818: test] Error 1
make[1]: Leaving directory '/home/fabian/.cache/yay/coin-or-ipopt/src/build/test'
make: *** [Makefile:849: test] Error 2
make: Leaving directory '/home/fabian/.cache/yay/coin-or-ipopt/src/build'
==> ERROR: A failure occurred in check().
    Aborting...
```

**Comment by svigerske** [comment]
This looks like a build from AUR on ArchLinux.

The `openblas` package includes `libopenblas.so`, `libopenblas.so.0`, and `libopenblas.so.0.3`, but no `libopenblas.so.3`: https://archlinux.org/packages/community/x86_64/openblas/files/

Maybe there was some change in the `openblas` package that broken the dependency of the mumps lib? Maybe try rebuilding `coin-or-coinmumps` ?

**Comment by Fabian42** [comment]
I had uninstalled `coin-or-ipopt` before, now reinstalled `coin-or-coinmumps` and installed `coin-or-ipopt` again, that worked. As long as nobody else complains about upgrade issues, I'll close this report for now.

**Comment by Maik93** [comment]
Hi, I had the same issue (on ArchLinux too), but removing and reinstalling `coin-or-coinmumps` did not work.

I ended up with a savage `sudo ln -sr /lib/libopenblas.so.0.3 /lib/libopenblas.so.3` that let everything work. Not that nice however.
