### ISSUE TITLE
IPOPT for STM32  KBuild systems

### ISSUE THREAD

**Issue by rtkartista** [coin-or/Ipopt#647]

**Comment by svigerske** [comment]
I don't see this happening. I'm very reluctant to introduce additional build systems and KBuild looks as if this is for software that runs inside the Linux kernel. I don't think that Ipopt belong there.

STM32 seems to be ARM32. Ipopt's current buildsystem (autotools) is probably supporting ARM32, though I don't know about anyone testing this.
