### ISSUE TITLE
Does Ipopt support building with cmake?

### ISSUE THREAD

**Issue by fengweichangzi** [coin-or/Ipopt#649]
When I tried to build with cmake, I got the error info "popt-releases-3.14.11" does not appear to contain CMakeLists.txt."

Does it support cmake or not?

**Comment by svigerske** [comment]
No, it doesn't. I don't think it claims to do that anywhere either.

Installation instructions are found in the docu: https://coin-or.github.io/Ipopt/INSTALL.html

**Comment by ferdymercury** [comment]
There are some user doing some custom patches to support CMake builds:
https://github.com/rjodon/coinor-ipopt-with-cmake
https://github.com/ebertolazzi/mexIPOPT/tree/master/cmake_for_ma57_77_86_97
