### ISSUE TITLE
core dumped

### ISSUE THREAD

**Issue by zrd1234** [coin-or/Ipopt#652]
Hello, when I run a test code for ipopt and cppad, I encounter the following problem.
![8cfc097595639f5b40b92926db2cd57](https://user-images.githubusercontent.com/96851901/229531920-623db964-cd9a-4515-91b1-8b3a709dec77.jpg)
When I run the cpp_example that comes with ipopt, I get the following error.
![dc7fa8d5434d49a17b6c0f2cfd75524](https://user-images.githubusercontent.com/96851901/229532262-bd96b9ca-6a76-4089-85f3-0cab77e763f8.jpg)

**Comment by svigerske** [comment]
Make sure your Ipopt installation includes at least one linear solver (https://coin-or.github.io/Ipopt/#PREREQUISITES). It doesn't appear so, so that Ipopt tries to load one from libhsl.so at runtime, which also fails.

Further, 3.12.8 is very old.

I cannot say anything about the core dump of the CppAD example.

**Comment by zrd1234** [comment]
> Make sure your Ipopt installation includes at least one linear solver (https://coin-or.github.io/Ipopt/#PREREQUISITES). It doesn't appear so, so that Ipopt tries to load one from libhsl.so at runtime, which also fails.
> 
> Further, 3.12.8 is very old.
> 
> I cannot say anything about the core dump of the CppAD example.

Hello, if I use our ipopt source code, can it be used perfectly on arm architecture

**Comment by svigerske** [comment]
I assume this is a question. I don't know your Ipopt source, but the one from [here](https://github.com/Ipopt) should work fine on ARM architectures.

**Comment by zrd1234** [comment]
> 我认为这是一个问题。我不知道你的 Ipopt 源代码，但[这里的](https://github.com/Ipopt)源代码应该在 ARM 架构上工作正常。

Thank you very much for your timely reply. I will ask you if I have any questions after I try it. Thank you very much.
There is also the question of how these versions should be chosen.
