### ISSUE TITLE
Solve non-convex problem using ipopt

### ISSUE THREAD

**Issue by rlacjfjin** [coin-or/Ipopt#655]
Hi,
Now I want to solve Petroleum Refinery Problem, which contains bilinear(even trilinear) constraints, and it is non-convex problem.
I have compared ipopt and SLP(used comercial product, aspen-pims), some case ipopt result is worse than SLP. 
I know that the result of SLP has a lot to do with the choice of initial value, but I can't sure that how effect on IPOPT in select better initial value. Can you give me some advices? Such as tuning parametters or how to choose initial solution in IPOPT...
By the way, the size of problem is not too large. 
Thanks.

**Comment by svigerske** [comment]
No, I cannot give general advice. The starting point is also important for Ipopt.
