### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by skampezidou** [coin-or/Ipopt#660]
I am running the command:

pip install git+https://github.com/coin-or/Ipopt

inside the python environment terminal in pycharm (macos). I get the following error:

Collecting git+https://github.com/coin-or/Ipopt
  Cloning https://github.com/coin-or/Ipopt to /private/var/folders/y_/tcrcdcy92bn8_m0zj4c41rg00000gn/T/pip-req-build-w8k33xbu
  Running command git clone --filter=blob:none --quiet https://github.com/coin-or/Ipopt /private/var/folders/y_/tcrcdcy92bn8_m0zj4c41rg00000gn/T/pip-req-build-w8k33xbu
  Resolved https://github.com/coin-or/Ipopt to commit abff333317bfcead4d9cd90b2c3984f7734cd79e
ERROR: git+https://github.com/coin-or/Ipopt does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.

Any ideas how to resolve this? thank you.

**Comment by tkralphs** [comment]
As the error message indicates, Ipopt is not a Python package. I believe there are some Python wrappers for Ipopt around, but Ipopt itself is written in C++.

**Comment by svigerske** [comment]
Yes, what Ted said.

Ipopt installation instructions: https://coin-or.github.io/Ipopt/INSTALL.html

Some other interfaces to Ipopt: https://coin-or.github.io/Ipopt/index.html#HOWTOUSE

**Comment by skampezidou** [comment]
Thank you very much!
