### ISSUE TITLE
install issue: Required package LAPACK not found.

### ISSUE THREAD

**Issue by gigglesun** [coin-or/Ipopt#662]
I follow the installation guide to install latest 3.14 IPOPT on a cent os which has already installed lapack before and always get this LAPACK related error message:
 
**Command example 1:**
```bash
../configure  --prefix=${IPOPT_INSTALL_PATH}
```
I got
```bash
configure: error: Required package LAPACK not found
```
**Command example 2:**
```bash
../configure  --without-lapack --prefix=${IPOPT_INSTALL_PATH}
```
I got
```bash
configure: error: Required package LAPACK not found
```
seems the --without-lapack command do not take effect.

**Command example 3:**
```bash
../configure  --with-lapack-lflags="-L/usr/local/opt/lapack/lib/ -llapack -lblas" --prefix=${IPOPT_INSTALL_PATH}
```
I got
```bash
error: Cannot link to user-specified -L/usr/local/opt/lapack/lib/ -llapack -lblas.
```
seems the --with-lapack-lflags command do not take effect.

**Command example 4:**
```bash
export LIBRARY_PATH=/usr/local/opt/lapack/lib:${LIBRARY_PATH}
../configure  --with-lapack --prefix=${IPOPT_INSTALL_PATH}
```
I got
```bash
configure: error: Required package LAPACK not found
```

**Comment by svigerske** [comment]
The third example (setting `--with-lapack-lflags`) is the one that should be used if Lapack isn't installed in a default location. You'll have to look into config.log regarding details on why the link check has failed. Maybe there are more linker flags necessary.

**Comment by gigglesun** [comment]
> The third example (setting `--with-lapack-lflags`) is the one that should be used if Lapack isn't installed in a default location. You'll have to look into config.log regarding details on why the link check has failed. Maybe there are more linker flags necessary.

Thanks for your reply and help @svigerske , after checking the config.log and there is some dlopen related error, and add -ldl linker flags, it can configure successfully,   the command I used is as below: 

```bash
../configure  --disable-java --with-lapack-lflags="-L/usr/local/opt/lapack/lib/ -llapack -lblas -ldl" --prefix=${IPOPT_INSTALL_PATH}
```
