### ISSUE TITLE
MSVC Builds via .dll hog the CPU, inexplicably

### ISSUE THREAD

**Issue by mahonbt1** [coin-or/Ipopt#668]
For some reason when built using msvc 2019 and the Ipopt-3.dll's, one of my test programs will grab >60% of my CPU.  When run on the same Windows machine using Mingw-w64 and building from source with Thirdparty-MUMPS as the linear solver, it only claims about 5% peak CPU during the Ipopt iterations.  Are there some MPI calls or similar getting spun up in MUMPS that aren't getting mocked out appropriately when built via msvc?  This sort of looks like a busy_wait on some sort of resource.

**Comment by svigerske** [comment]
The binaries that are attached to the releases here are build with the multithreaded version of Intel MKL. Setting `OMP_NUM_THREADS=1` should restrict it to use only one core.

ThirdParty-Mumps builds MUMPS without OpenMP enabled and no use of MPI.
