### ISSUE TITLE
make: *** [Makefile:849: test] Error 2  when sudo make test

### ISSUE THREAD

**Issue by dbdxnuliba** [coin-or/Ipopt#670]
dell@dell:~/ref/ws_quad_sdk/THIRD/Ipopt/build$ sudo make test
Making all in src
make[1]: Entering directory '/home/dell/ref/ws_quad_sdk/THIRD/Ipopt/build/src'
make  all-recursive
make[2]: Entering directory '/home/dell/ref/ws_quad_sdk/THIRD/Ipopt/build/src'
Making all in .
make[3]: Entering directory '/home/dell/ref/ws_quad_sdk/THIRD/Ipopt/build/src'
make[3]: Nothing to be done for 'all-am'.
make[3]: Leaving directory '/home/dell/ref/ws_quad_sdk/THIRD/Ipopt/build/src'
Making all in Apps/AmplSolver
make[3]: Entering directory '/home/dell/ref/ws_quad_sdk/THIRD/Ipopt/build/src/Apps/AmplSolver'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/dell/ref/ws_quad_sdk/THIRD/Ipopt/build/src/Apps/AmplSolver'
make[2]: Leaving directory '/home/dell/ref/ws_quad_sdk/THIRD/Ipopt/build/src'
make[1]: Leaving directory '/home/dell/ref/ws_quad_sdk/THIRD/Ipopt/build/src'
Making all in contrib/sIPOPT
make[1]: Entering directory '/home/dell/ref/ws_quad_sdk/THIRD/Ipopt/build/contrib/sIPOPT'
Making all in src
make[2]: Entering directory '/home/dell/ref/ws_quad_sdk/THIRD/Ipopt/build/contrib/sIPOPT/src'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/dell/ref/ws_quad_sdk/THIRD/Ipopt/build/contrib/sIPOPT/src'
Making all in AmplSolver
make[2]: Entering directory '/home/dell/ref/ws_quad_sdk/THIRD/Ipopt/build/contrib/sIPOPT/AmplSolver'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/dell/ref/ws_quad_sdk/THIRD/Ipopt/build/contrib/sIPOPT/AmplSolver'
make[2]: Entering directory '/home/dell/ref/ws_quad_sdk/THIRD/Ipopt/build/contrib/sIPOPT'
make[2]: Nothing to be done for 'all-am'.
make[2]: Leaving directory '/home/dell/ref/ws_quad_sdk/THIRD/Ipopt/build/contrib/sIPOPT'
make[1]: Leaving directory '/home/dell/ref/ws_quad_sdk/THIRD/Ipopt/build/contrib/sIPOPT'
make[1]: Entering directory '/home/dell/ref/ws_quad_sdk/THIRD/Ipopt/build'
make[1]: Nothing to be done for 'all-am'.
make[1]: Leaving directory '/home/dell/ref/ws_quad_sdk/THIRD/Ipopt/build'
cd test; make test
make[1]: Entering directory '/home/dell/ref/ws_quad_sdk/THIRD/Ipopt/build/test'
chmod u+x ./run_unitTests
./run_unitTests
 
Running unitTests...
 
Testing AMPL Solver Executable...
    Test passed!
Testing C++ Example...
    Test passed!
Testing C Example...
    Test passed!
Testing Fortran Example...
    Test passed!
Testing Java Example...
0 
 ---- 8< ---- Start of test program output ---- 8< ----
Exception in thread "main" java.lang.UnsatisfiedLinkError: /home/dell/ref/ws_quad_sdk/THIRD/Ipopt/build/src/.libs/libipopt.so.3.14.12: libcoinhsl.so.2: cannot open shared object file: No such file or directory
	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2445)
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2501)
	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2700)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2662)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
	at java.base/java.lang.System.loadLibrary(System.java:1873)
	at org.coinor.Ipopt.<init>(Ipopt.java:231)
	at HS071.<init>(HS071.java:37)
	at HS071.main(HS071.java:396)
 ---- 8< ----  End of test program output  ---- 8< ----
 
    ******** Test FAILED! ********
Test program existed with nonzero status.
Testing sIpopt Example parametric_cpp...
    Test passed!
Testing sIpopt Example redhess_cpp...
    Test passed!
Testing EmptyNLP Example...
    Test passed!
Testing GetCurr Example...
    Test passed!
make[1]: *** [Makefile:818: test] Error 1
make[1]: Leaving directory '/home/dell/ref/ws_quad_sdk/THIRD/Ipopt/build/test'
make: *** [Makefile:849: test] Error 2

**Comment by svigerske** [comment]
Maybe try setting `LD_LIBRARY_PATH` such that the HSL lib is found.
