### ISSUE TITLE
Help about use of tiny_step_tol

### ISSUE THREAD

**Issue by mottelet** [coin-or/Ipopt#678]
Hello,
I am solving a numerically kind of ill-posed optimization problem (my gradient is not exact as it is approximated) and I have difficulties to stop the optimization. I try to use the tiny_step_tol parameter, but it does not seem to work. I have read in the documentation that only repeated violation of the step tolerance will stop the optimization. How do you control the macimum number of repeated violations ? 

S.

**Comment by svigerske** [comment]
I think it is 2:

https://github.com/coin-or/Ipopt/blob/1e0a5df94e3b71ce6bde972352f1b2f72f342af7/src/Algorithm/IpBacktrackingLineSearch.cpp#L393-L419

But it needs the step in the dual variables to be tiny (`tiny_step_y_tol`) as well for the first time.
(The t/T character is shown in the [iteration log](https://coin-or.github.io/Ipopt/OUTPUT.html).)
In the next iteration, only `tiny_step_tol` is relevant to set the tiny_step flag in `IpData()`.
If that is set, and no update for mu is computed, then Ipopt will terminate:

https://github.com/coin-or/Ipopt/blob/1e0a5df94e3b71ce6bde972352f1b2f72f342af7/src/Algorithm/IpMonotoneMuUpdate.cpp#L158-L161

However, there is some probably undocumented condition in the detection of a tiny step. If the constraint violation is still "large", then there can be no tiny steps, apparently:

https://github.com/coin-or/Ipopt/blob/1e0a5df94e3b71ce6bde972352f1b2f72f342af7/src/Algorithm/IpBacktrackingLineSearch.cpp#L1256-L1263

**Comment by mottelet** [comment]
OK thanks.
