### ISSUE TITLE
Use system installed MUMPS, ASL and HSL

### ISSUE THREAD

**Issue by catap** [coin-or/Ipopt#690]
Good day,

How can  I use system installed MUMPS, ASL and HSL to build Ipopt?

**Comment by svigerske** [comment]
`./configure --help` will list all the options you can use to specify how to use your installation of dependencies.

**Comment by catap** [comment]
@svigerske ah, you mean that if I add `--with-mumps-lflags=-lmumps` it picks the mumps? What makes things much easy, indeed.
