### ISSUE TITLE
Solver interface definitions

### ISSUE THREAD

**Issue by bharswami** [coin-or/Ipopt#696]
Hi, 
I am trying to build Ipopt from the source code to create a MATLAB mex file. I have been able to do that without the linear solver functions definitions.
Where can we get the source code for the linear solver function definitions (Interface files are available in IpSpralSolverInterface.cpp etc.)? I want to add that to my Visual Studio Project and compile.
Thanks
Bharath

**Comment by svigerske** [comment]
Regarding dependencies of Ipopt, see https://coin-or.github.io/Ipopt/INSTALL.html#EXTERNALCODE

For an existing Matlab interface, see https://github.com/ebertolazzi/mexIPOPT

**Comment by bharswami** [comment]
Thanks
