### ISSUE TITLE
configure.ac:24: error: possibly undefined macro: AC_COIN_INITIALIZE

### ISSUE THREAD

**Issue by itsmathtime** [coin-or/Ipopt#699]
I am new to autotools, and struggeling.

As I understand the build system, to add a new source file, I should add it to `Makefile.am` and then run autotools, but running autotools fails. I guess this is standard autotools stuff, but I could not find any information on how to get past the `AC_COIN_INITIALIZE` error online.

When I run `autoreconf` in the root of the project, I get the following output:
```
~/dev/Ipopt$ autoreconf
configure.ac:24: error: possibly undefined macro: AC_COIN_INITIALIZE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:31: error: possibly undefined macro: AC_COIN_PROG_CC
configure.ac:32: error: possibly undefined macro: AC_COIN_PROG_CXX
configure.ac:33: error: possibly undefined macro: AC_COIN_PROG_F77
configure.ac:37: error: possibly undefined macro: AC_COIN_F77_SETUP
configure.ac:44: error: possibly undefined macro: AC_COIN_PROG_LIBTOOL
configure.ac:48: error: possibly undefined macro: AC_COIN_RPATH_FLAGS
configure.ac:52: error: possibly undefined macro: AC_COIN_CXXLIBS
configure.ac:55: error: possibly undefined macro: AC_COIN_DOXYGEN
configure.ac:58: error: possibly undefined macro: AC_COIN_DEBUGLEVEL
configure.ac:69: error: possibly undefined macro: AC_DEFINE
configure.ac:71: error: possibly undefined macro: AC_MSG_ERROR
configure.ac:106: error: possibly undefined macro: AC_COIN_CHK_LIBM
configure.ac:108: error: possibly undefined macro: AC_COIN_CHK_LAPACK
configure.ac:116: error: possibly undefined macro: AC_COIN_CHK_PKG
configure.ac:157: error: possibly undefined macro: AC_COIN_FINALIZE_FLAGS
configure.ac:163: error: possibly undefined macro: AC_COIN_TRY_LINK
configure.ac:164: error: possibly undefined macro: AC_COIN_DEFINENAMEMANGLING
configure.ac:173: error: possibly undefined macro: AC_MSG_WARN
configure.ac:237: error: possibly undefined macro: AC_COIN_CHK_LIBHDR
configure.ac:300: error: possibly undefined macro: AC_COIN_CHECK_ISFINITE
configure.ac:320: error: possibly undefined macro: AC_COIN_CHECK_NAMESPACE_DECL
configure.ac:510: error: possibly undefined macro: AC_COIN_VPATH_LINK
configure.ac:670: error: possibly undefined macro: AC_COIN_FINALIZE
autoreconf: /usr/bin/autoconf failed with exit status: 1
```

**Comment by svigerske** [comment]
Yes, we have a special system on how to run the autotools in order to ensure that developers use consistent versions of the tools and macros.

The macros like `AC_COIN_INITIALIZE` and the scripts to run autotools live in a separate repository: https://github.com/coin-or-tools/BuildTools/. Folling the steps in the readme there should get you going.

**Comment by itsmathtime** [comment]
Ah, thanks. That was the missing piece. I am able to reconfigure the project now. Thank you.

**Comment by iamustcfw** [comment]
I also met the same problem, and i successfully installed the BuildTools.

`(base) hzr@ubuntu:~/local$ ./run_autotools /home/hzr/Clp-master_1
Using COIN_AUTOTOOLS_DIR=/home/hzr/local
candDirs (1): /home/hzr/Clp-master_1
Running autotools in /home/hzr/Clp-master_1
Processing /home/hzr/Clp-master_1 ...
  BuildTools directory: /home/hzr/local
  creating temporary link for ./BuildTools -> /home/hzr/local
  refreshing autotools scripts in this directory.
patching file compile
  running aclocal in /home/hzr/Clp-master_1
  apply libtool.m4 patch to support ICL
patching file aclocal.m4
Hunk #1 succeeded at 6662 (offset -76 lines).
Hunk #2 succeeded at 9117 (offset -76 lines).
Hunk #3 succeeded at 9751 (offset -76 lines).
Hunk #4 succeeded at 9797 (offset -76 lines).
Hunk #5 succeeded at 10829 (offset -76 lines).
  running autoheader in /home/hzr/Clp-master_1
  running automake in /home/hzr/Clp-master_1
  running autoconf in /home/hzr/Clp-master_1
  update BuildTools/headers/configall_system.h, if existing
  update BuildTools/headers/configall_system_msc.h, if existing
Removing temporary links to BuildTools.`

But the problem still exists,
