### ISSUE TITLE
SYMSOLVER_WRONG_INERTIA

### ISSUE THREAD

**Issue by bharswami** [coin-or/Ipopt#706]
I am getting SYMSOLVER_SUCCESS in first call and then SYMSOLVER_WRONG_INERTIA in subsequent calls. What could be the reason?

**Comment by svigerske** [comment]
The matrix could have changed, which then changed the inertia.
Ipopt then tries to deal with this (https://github.com/coin-or/Ipopt/blob/stable/3.14/src/Algorithm/IpPDFullSpaceSolver.cpp#L501-L641).
