### ISSUE TITLE
z_L, z_U, x_L, x_U, v_L, v_U

### ISSUE THREAD

**Issue by bharswami** [coin-or/Ipopt#708]
Are z_L, z_U, …. Etc the upper and lower bounds on the respective quantities which we specify at the beginning of the simulation? If so, why are they being reset to zero in the middle of the analysis?

**Comment by bharswami** [comment]
@svigerske Can you please shed some light on this?

**Comment by svigerske** [comment]
x_L and x_U are the lower and upper bounds on variables. They shouldn't be reset.

z_L and z_U are the dual variables corresponding to x_L and x_U. I haven't checked, but maybe Ipopt has a reason to reset them. It would allowed to.

v_L and v_U are the dual variables corresponding to slack variables that are introduced when Ipopt reformulates the given problem (TNLP) into its internal form (turning inequalities into equalities). So, they are similar to z_L and z_U.

Some info also at https://coin-or.github.io/Ipopt/classIpopt_1_1TNLPAdapter.html#details

Sorry, haven't had enough time to look at the issue with the nan's. That needs more digging.
