### ISSUE TITLE
Appending to the end of output_file while printing rather than overwirting it

### ISSUE THREAD

**Issue by zhengzl18** [coin-or/Ipopt#720]
I wonder if there is a way to append to the end of `output_file` while printing rather than overwirt it. I'd like to print the outputs of several solvings to one file, but by simply setting `output_file`, the contents of this file will be overwitten every solving. I have searched for output-related options but found nothing.

**Comment by svigerske** [comment]
No, there is no option so far. You could create your own version of the FileJournal class that does that, but it should also be possible to add an option that says whether to append or truncate.

**Comment by zhengzl18** [comment]
> No, there is no option so far. You could create your own version of the FileJournal class that does that, but it should also be possible to add an option that says whether to append or truncate.

THX a lot!
