### ISSUE TITLE
computation cost lots of time

### ISSUE THREAD

**Issue by Dong09** [coin-or/Ipopt#731]
Hello, I am using IPOPT to solve a physical optimization problem. It takes about 4 minutes to run 70 data, and most of the CPU time is spent on Evaluation. I would like to know how to accelerate or optimize this situation. I am using the latest version of IPOPT and MuMps, and I am very grateful.

**Comment by svigerske** [comment]
Evaluation is the time that is spent on your side, in the function/gradient/Hessian evaluation callbacks that you have implemented. So you may want to check whether you can speed these up.

If computing the Hessian is too costly, it can be worth to try whether enabling the [hessian_approximation](https://coin-or.github.io/Ipopt/OPTIONS.html#OPT_hessian_approximation) option is beneficial.
