### ISSUE TITLE
Hello, how do I set this option

### ISSUE THREAD

**Issue by ZEROS-L** [coin-or/Ipopt#741]
Hello, how do I set this option in AMPL?
In the process of solving the NLP model, there are the following problems, do you know the reason?

![image](https://github.com/coin-or/Ipopt/assets/52021625/3f941f29-aac7-468c-930c-2af146a16171)

![image](https://github.com/coin-or/Ipopt/assets/52021625/2def8182-c6b5-4efd-bc4e-52a817449d82)

**Comment by svigerske** [comment]
Looking at #743, you seem to have found a way to get this working.
