### ISSUE TITLE
How do I solve this problem, or how do I set limits

### ISSUE THREAD

**Issue by ZEROS-L** [coin-or/Ipopt#742]
![image](https://github.com/coin-or/Ipopt/assets/52021625/7b478e32-1a8c-4902-a1e8-9ef70ee9b0cf)
![image](https://github.com/coin-or/Ipopt/assets/52021625/992a303a-0f68-426f-a1e9-d76493c6886b)

Hello Because of the following formula, For D33 ,when (xr+12) > 0,  then yr>-∞,and that will cause the following solution to fail. For D11  when (xr+12) > 0,then  yr<∞,and that will also cause the following solution to fail.How do I solve this problem, or how do I set limits

![image](https://github.com/coin-or/Ipopt/assets/52021625/aaf9fa18-ca45-4a48-8f30-363cc97c12f1)

**Comment by svigerske** [comment]
Duplicate of  #743.
