### ISSUE TITLE
Error while loading shared libraries

### ISSUE THREAD

**Issue by Huang-XN** [coin-or/Ipopt#750]
Hi there, 

I have successfully installed Ipopt following the instructions. But when I ran `ipopt -v` or `ipopt -h`, it always reported an error as follow:
`ipopt: error while loading shared libraries: libcoinhsl.so.2: cannot open shared object file: No such file or directory`.

My system is Ubuntu 22.04.4 LTS, 64 bit.

Could you tell me how to solve it?

Xingnan

**Comment by svigerske** [comment]
Add the path with the Ipopt libraries to your library search path, e.g., `LD_LIBRARY_PATH` environment variable.
