### ISSUE TITLE
Auto computing jacobian and gradient

### ISSUE THREAD

**Issue by bharswami** [coin-or/Ipopt#753]
Is there a provision in ipopt for auto-computing jacobian and gradient? i.e. we don't have to specify those functions explicitly. Or do we have to use dependencies like mklJac etc?
Thanks in advance
Bharath

**Comment by svigerske** [comment]
Ipopt itself only includes an AMPL interface, so that if you use AMPL (or something else that generates .nl files, e.g., Pyomo), you will get AMPL's automatic differentiation.

But then there are a number of automatic differentiation packages and modeling systems that have interfaces to Ipopt: https://coin-or.github.io/Ipopt/#HOWTOUSE

**Comment by bharswami** [comment]
Thanks Stefan.
Also, in the cpp_example, there is a call to the function IpoptApplicationFactory().
   SmartPtr<IpoptApplication> app = IpoptApplicationFactory();
Is this defined in a pre-built library?
P.S.: I am trying to run ipopt problems in visual studio

**Comment by svigerske** [comment]
Yes, `IpoptApplicationFactory()` should be available in DLLs.
It doesn't do much, you should also be able to do a `new Ipopt::IpoptApplication` from your code.

https://github.com/coin-or/Ipopt/blob/5fd746337021543e78dc2d167cb1c15db81f68e1/src/Interfaces/IpIpoptApplication.cpp#L33-L38

**Comment by bharswami** [comment]
I was able to fix that by adding the path to the DLLs. 
Visual Studio is now telling me that Ipopt-vc8.dll cannot be opened

**Comment by bharswami** [comment]
I guess the libraries were built with mingw or something - not suited for MSVS2022.
Any suggestions/workarounds?

**Comment by svigerske** [comment]
`Ipopt-vc8.dll` sounds like a very old version of Ipopt. Binaries for current Ipopt are available at different places: https://github.com/coin-or/Ipopt?tab=readme-ov-file#precompiled-binaries

**Comment by bharswami** [comment]
Thanks Stefan. 
I am getting the error "ipopt-3.dll not found". Could this be a version incompatibility issue since I am using VS2022?

**Comment by svigerske** [comment]
It looks more of a problem of making sure that the library can be found. Check your library search paths, e.g., environment variable `PATH`.

**Comment by bharswami** [comment]
It is building fine. But not able to execute/debug. I strongly feel its a version compatibility issue since I tried with VS2019 as well. Was ipopt-3.dll built using mingW or something?
![image](https://github.com/coin-or/Ipopt/assets/30338689/e3625ba1-1908-4418-a0d2-56bc1ebab6b9)

**Comment by bharswami** [comment]
Also have a look at the dependencies I have.
![image](https://github.com/coin-or/Ipopt/assets/30338689/df593e49-1ae5-4e4b-9b4a-d4f4c5e28601)
![image](https://github.com/coin-or/Ipopt/assets/30338689/f97c92ea-42c4-42ec-ac18-484b4c741660)

**Comment by bharswami** [comment]
I tried adding these to the PATH environment variable as well

**Comment by bharswami** [comment]
Hi Stefan,
The issue was fixed by renaming the "ipopt.dll.lib" to "ipopt-3.lib"
