### ISSUE TITLE
Segmentation fault from from /lib/libipopt.so.1

### ISSUE THREAD

**Issue by cch-cs** [coin-or/Ipopt#758]
I have configured the Ipopt package (version 3.14) without-hsl. 
My module builds successfully, but when I call the solver to solve, 
I get segmentation fault for the function call `Ipopt::IpoptApplication::OptimizeTNLP(Ipopt::SmartPtr<Ipopt::TNLP> const&) ()` in the library `/lib/libipopt.so.1`

I am not sure why this issue happens

I do install the following modules for compiling my module

```
git clone -b master https://github.com/coin-or/CppAD.git
cd CppAD
mkdir build
cd build
cmake ..
make install

git clone https://github.com/coin-or-tools/ThirdParty-ASL.git
cd ThirdParty-ASL
./get.ASL
./configure
make
make install

git clone https://github.com/coin-or-tools/ThirdParty-Mumps.git
cd ThirdParty-Mumps
./get.Mumps
./configure
make
make install

git clone -b stable/3.14 https://github.com/coin-or/Ipopt.git
cd Ipopt
mkdir build
cd build
../configure --without-hsl
make
make test
make install
```

It would be great if you guys help me resolve this issue.
Thanks in advance.

**Comment by svigerske** [comment]
Maybe build Ipopt with `--enable-debug` (https://coin-or.github.io/Ipopt/INSTALL.html#CONFIGURE_FLAGS) and then run your code in a debugger or under valgrind.

**Comment by ShuqiXu** [comment]
I got the same issue for version 3.14.16
<img width="1070" alt="image" src="https://github.com/user-attachments/assets/78e191c9-6dd4-4143-9df8-47df16cb0fb7">

This issue happened rarely, but it happened from time to time.

**Comment by svigerske** [comment]
Could you add the following check
```patch
--- a/src/Algorithm/IpBacktrackingLineSearch.cpp
+++ b/src/Algorithm/IpBacktrackingLineSearch.cpp
@@ -871,6 +871,9 @@ void BacktrackingLineSearch::StopWatchDog(
 
    in_watchdog_ = false;
 
+   assert(IsValid(watchdog_iterate_));
+   assert(IsValid(watchdog_delta_));
+
    // Reset all fields in IpData to reference point
    SmartPtr<IteratesVector> old_trial = watchdog_iterate_->MakeNewContainer();
    IpData().set_trial(old_trial);
```
and build a debug version of Ipopt (configure with `--enable-debug`) and get the backtrace again?

**Comment by svigerske** [comment]
Closing due to no response and cannot reproduce.
