### ISSUE TITLE
Building ipopt with casadi

### ISSUE THREAD

**Issue by bharswami** [coin-or/Ipopt#763]
I have downloaded the casadi source code and I am able to use cmake with it to build binaries _without_ ipopt. What binaries do I need and where do I place them to build casadi _with_ ipopt. Thanks in advance.

**Comment by svigerske** [comment]
You probably want to ask this at https://github.com/casadi/casadi/issues
My guess is that they just need a build of Ipopt libraries and you need to tell Casadi where to find your Ipopt installation.
