### ISSUE TITLE
Installation guide for win64 Visual Studio

### ISSUE THREAD

**Issue by yuachen** [coin-or/Ipopt#765]
I was unable to build IPOPT from source for win64 Visual Studio 17 2022. It looks like that the [current installation guide](https://coin-or.github.io/Ipopt/INSTALL.html) only provides instructions for Mumps and IPOPT for UNIX environment. The UNIX guide works well in msys2 environment, but I did not manage to make it work for Visual Studio compilers. 

Then I saw that the latest binary release [3.14.16](https://github.com/coin-or/Ipopt/releases/tag/releases%2F3.14.16) is for win64, Visual Studio. It is very nice!
Would it be possible to update the installation guide with step-by-step instructions for Windows Visual Studio build from source (including MUMPS and IPOPT)?

**Comment by svigerske** [comment]
The guide also applied to using MS Visual Studio compilers. That's what the part starting with "If you want to use the native MSVC or Intel compiler..." on the instructions for Windows is about.

I have no intention on making another guide.
