### ISSUE TITLE
"Short tutorial" link is _Forbidden_

### ISSUE THREAD

**Issue by m4r35n357** [coin-or/Ipopt#770]
http://drops.dagstuhl.de/volltexte/2009/2089/pdf/09061.WaechterAndreas.Paper.2089.pdf

**Comment by svigerske** [comment]
Google points me to this one: https://drops.dagstuhl.de/storage/16dagstuhl-seminar-proceedings/dsp-vol09061/DagSemProc.09061.16/DagSemProc.09061.16.pdf
Will update the link.

**Comment by m4r35n357** [comment]
Cheers!
