### ISSUE TITLE
"Unresolved external symbol snprintf" when compiling with VS2015/ Ifort 2015?

### ISSUE THREAD

**Issue by nickvandewiele** [coin-or/Ipopt#8]
I am trying to compile Ipopt/MUMPS with 
- VS2015/ and 
- Intel ifort/MKL 2015 
- on a Win2012R2 x64 machine 
- through Cygwin, and MSVC++ compilers, 
- using Ipopt 3.12 from the svn repo
- Windows SDK 10

The (last) configure step of the Ipopt package showed the following error in the log:
```
configure:37890: checking for snprintf
configure:37955: cl -o conftest.exe -MT -O2 -nologo -wd4996 -D_CRT_SECURE_NO_DEPRECATE -DNDEBUG -DIPOPT_BUILD   conftest.c  >&5
conftest.c
conftest.obj : error LNK2001: unresolved external symbol snprintf
conftest.exe : fatal error LNK1120: 1 unresolved externals
cl : Command line warning D9035 : option 'o' has been deprecated and will be removed in a future release
configure:37961: $? = 2
configure: failed program was:
...
```

Although it did not crash during configure, the compilation step resulted in errors. S 

Sections in C files (e.g. [here](https://github.com/coin-or/Ipopt/blob/master/Ipopt/src/contrib/LinearSolverLoader/LibraryHandler.c#L18)) :
```
#ifdef HAVE_SNPRINTF
#define mysnprintf snprintf
#else
# ifdef HAVE__SNPRINTF
# define mysnprintf _snprintf
# else
#  define mysnprintf snprintf
#  error "Do not have function for save printing into a C-string (snprintf or _snprintf)"
# endif
#endif
```
that don't play nice with my VS2015 installation as the `snprintf` functions cannot be found, which was (silently) pointed out during the `configure`.

Has compilation of Ipopt 3.12 ever been tested with those specifics of VS/ifort?
What should my $LIB variable look like?

**Comment by svigerske** [comment]
It's normal that snprintf is not available with MS compiler, but usually _snprintf is available. But that has not been found by configure either?
What are the compilation errors?
As snprintf seems to be used only in the library loader, you could configure with --disable-linear-solver-loader do disable this part of the code.

I don't know what LIB should look like.

**Comment by nickvandewiele** [comment]
Thanks,

In the `Ipopt` subfolder of `CoinIpopt` I ran
`make clean;./configure -enable-doscompile=msvc --disable-linear-solver-loader;make`

which now compiles without problems. What am I missing out on with the `--disable-linear-solver-loader` flag?

**Comment by nickvandewiele** [comment]
Nevermind, the _linear solver loader_ mechanism is explained in http://web.mit.edu/ipopt_v3.11.6/doc/documentation.pdf.
