### ISSUE TITLE
Support ampl-mp 4.0.0

### ISSUE THREAD

**Issue by chenrui333** [coin-or/Ipopt#802]
Also, asl got removed from mp, https://github.com/ampl/asl/issues/21

relates to https://github.com/Homebrew/homebrew-core/pull/197123

**Comment by svigerske** [comment]
Does AMPL-MP now include automatic differentiation? The 4.0.0 release notes doesn't seem to mention that.

**Comment by chenrui333** [comment]
tbh, I am not familiar with it.

**Comment by svigerske** [comment]
If your AMPL-MP libs included ASL before, but don't include it anymore, then maybe you need a separate package for ASL, which then the Ipopt build can depend on. I don't think that switching to ampl-mp is an option for Ipopt at the moment.

There is an autotools-based buildsystem for ASL at https://github.com/coin-or-tools/ThirdParty-ASL

**Comment by chenrui333** [comment]
oh, that is good to know, I also just use the [coin-or-tools/ThirdParty-ASL](https://github.com/coin-or-tools/ThirdParty-ASL), what is the diff btw the ThirdParty-ASL and ampl/asl

**Comment by svigerske** [comment]
ThirdParty-ASL is just a script to download a fixed version of ASL from https://coin-or-tools.github.io/ThirdParty-ASL/ and an autotools-based buildsystem for ASL. The resulting library is named libcoinasl.so or similar.
We don't do GitHub releases for ThirdParty-ASL, but there are tagged versions.

**Comment by chenrui333** [comment]
having ipopt depend on ampl-asl work for us, closing the issue now. thanks! 🙏
