### ISSUE TITLE
Interest in tagging a new release? 

### ISSUE THREAD

**Issue by traversaro** [coin-or/Ipopt#806]
Thanks a lot for all the work in maintaining ipopt! I noticed that there are some useful commits in the default branch (https://github.com/coin-or/Ipopt/commit/d6a5f96988399dcfec1cc4bf2ef23502781cefd2) that have not been released. I was wondering if you may be interested in doing a new release of ipopt to include these commits?

Thanks in advance!

**Comment by svigerske** [comment]
Yes, but then there are always these little other things that I would like to get done first.
It won't be until November 2025 for the next release, though.

**Comment by traversaro** [comment]
> Yes, but then there are always these little other things that I would like to get done first. It won't be until November 2025 for the next release, though.

Sure, no problem! I just added the month to the issue title to permit to easily distinguish it from similar issues in the past of the future, I do not have any specific requirement on the release date. To avoid confusion I removed the reference to the month from the issue title.

**Comment by traversaro** [comment]
And I just realized I wanted to write "November 2024" to frame the time of the issue, and instead I wrote "November 2025", now I understand even more the confusion, sorry again.

**Comment by svigerske** [comment]
3.14.17 has been released.

**Comment by traversaro** [comment]
Thanks a lot!
