### ISSUE TITLE
When I cross-compiling, the error is "error: linking to Fortran libraries from C fails"

### ISSUE THREAD

**Issue by Frinklin-Wang** [coin-or/Ipopt#809]
I use linux. I want to cross-compiling for qnx710, and I run:
```
CURRY_DIR=$PWD
QNX_HOST=/opt/qnx/qnx710_v45601/host/linux/x86_64
QNX_TARGET=/opt/qnx/qnx710_v45601/target/qnx7
QNX_CONFIGURATION_EXCLUSIVE=$HOME/.qnx
QNX_CONFIGURATION=$QNX_CONFIGURATION_EXCLUSIVE
MAKEFLAGS=-I/opt/qnx/qnx710_v45601/target/qnx7/usr/include
MAKEFLAGS=-I$QNX_BASE/target/qnx7/usr/include
LDFLAGS="-lsocket"
PATH=$PATH:${QNX_HOST}/usr/bin:${QNX_CONFIGURATION}/bin:${QNX_BASE}/jre/bin:/usr/lib/gcc/x86_64-linux-gnu/9/
export QNX_TARGET QNX_HOST QNX_CONFIGURATION QNX_CONFIGURATION_EXCLUSIVE MAKEFLAGS PATH LDFLAGS
CC=/opt/qnx/qnx710_v45601/host/linux/x86_64/usr/bin/aarch64-unknown-nto-qnx7.1.0-gcc
CXX=/opt/qnx/qnx710_v45601/host/linux/x86_64/usr/bin/aarch64-unknown-nto-qnx7.1.0-g++ 
CFLAGS="-fPIC"
CXXFLAGS="-fPIC"
export CC CXX CFLAGS CXXFLAGS
./configure --prefix=$PWD/output/qnx_8650_45601 --host=aarch64-unknown-nto-qnx7.1.0
make clean
make -j8
make install
```
the error log is:
```
checking whether /opt/qnx/qnx710_v45601/host/linux/x86_64/usr/bin/aarch64-unknown-nto-qnx7.1.0-g++ accepts -g... yes
checking whether C++ compiler /opt/qnx/qnx710_v45601/host/linux/x86_64/usr/bin/aarch64-unknown-nto-qnx7.1.0-g++ works... yes
configure: C++ compiler options are: -fPIC   -DIPOPT_BUILD
configure: Assuming that CXXLIBS is "-lc++".
configure: Trying to determine Fortran compiler name
checking for aarch64-unknown-nto-qnx7.1.0-gfortran... no
checking for aarch64-unknown-nto-qnx7.1.0-ifort... no
checking for aarch64-unknown-nto-qnx7.1.0-g95... no
checking for aarch64-unknown-nto-qnx7.1.0-fort77... no
checking for aarch64-unknown-nto-qnx7.1.0-f77... no
checking for aarch64-unknown-nto-qnx7.1.0-g77... no
checking for aarch64-unknown-nto-qnx7.1.0-pgf90... no
checking for aarch64-unknown-nto-qnx7.1.0-pgf77... no
checking for aarch64-unknown-nto-qnx7.1.0-ifc... no
checking for aarch64-unknown-nto-qnx7.1.0-frt... no
checking for aarch64-unknown-nto-qnx7.1.0-af77... no
checking for aarch64-unknown-nto-qnx7.1.0-xlf_r... no
checking for gfortran... gfortran
checking for aarch64-unknown-nto-qnx7.1.0-gfortran... gfortran
checking whether we are using the GNU Fortran 77 compiler... yes
checking whether gfortran accepts -g... yes
configure: WARNING: The flags FFLAGS="" do not work.  I will now just try '-O', but you might want to set FFLAGS manually.
configure: WARNING: This value for FFLAGS does not work.  I will continue with empty FFLAGS, but you might want to set FFLAGS manually.
configure: Fortran compiler options are: 
checking how to get verbose linking output from gfortran... -v
checking for Fortran libraries of gfortran...  -L/usr/lib/gcc/x86_64-linux-gnu/9 -L/usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib -L/lib/x86_64-linux-gnu -L/lib/../lib -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/9/../../.. -lsocket -lgfortran -lm -lgcc_s -lquadmath
configure: Corrected Fortran libraries:  -L/usr/lib/gcc/x86_64-linux-gnu/9 -L/usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib -L/lib/x86_64-linux-gnu -L/lib/../lib -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/9/../../.. -lsocket -lgfortran -lm -lquadmath
checking for dummy main to link with Fortran libraries... unknown
configure: error: linking to Fortran libraries from C fails
See `config.log' for more details.
configure: error: /bin/sh './configure' failed for Ipopt
Making clean in Ipopt
```
How to fix this error?
**I want to know, when I cross-compile, do I need to connect to the host's fortran libraries or use the gfortran compiler(such as aarch64-unknown-nto-qnx7.1.0-gfortran)?**
I want to know if I can cross-compile without gfortran compiler, just gcc or g++, how do I set this up？
Can someone give me some advice? Thank you.

**Comment by svigerske** [comment]
configure option `--disable-f77` should disable the use of Fortran in Ipopt. That will mainly disable the Fortran interface.     
You will still need to provide a linear solver for Ipopt, and popular ones are written in Fortran.

We aren't testing cross compiling, so I don't really know how much it would work if you had the host's fortran libraries. You probably have to set `FFLAGS` and `CXXLIBS` manually.

**Comment by Frinklin-Wang** [comment]
> configure option `--disable-f77` should disable the use of Fortran in Ipopt. That will mainly disable the Fortran interface. You will still need to provide a linear solver for Ipopt, and popular ones are written in Fortran.
> 
> We aren't testing cross compiling, so I don't really know how much it would work if you had the host's fortran libraries. You probably have to set `FFLAGS` and `CXXLIBS` manually.

Thank u for your reply. I add `--disable-f77`, bui it doesn't work, The error log is same to above. I really don't konw how to solve this problem. Can anyone help me?

**Comment by svigerske** [comment]
Are you sure you use a current Ipopt release? We are at 3.14.16.

**Comment by Frinklin-Wang** [comment]
> Are you sure you use a current Ipopt release? We are at 3.14.16.
No.I use 3.12.8.

**Comment by Frinklin-Wang** [comment]
> Are you sure you use a current Ipopt release? We are at 3.14.16.
No. I use 3.12.8.

**Comment by Frinklin-Wang** [comment]
> Are you sure you use a current Ipopt release? We are at 3.14.16.

No. I use 3.12.8.

**Comment by svigerske** [comment]
Then figure it out by yourself.

**Comment by Frinklin-Wang** [comment]
> Then figure it out by yourself.

Can 3.14.16 support cross-compiling?

**Comment by svigerske** [comment]
Maybe. At least, if there is an issue that we are able to fix, we would do that.

Configure option `--disable-f77` was added with 3.13.0. 3.12.8 is from 2017.

**Comment by Frinklin-Wang** [comment]
> Maybe. At least, if there is an issue that we are able to fix, we would do that.
> 
> Configure option `--disable-f77` was added with 3.13.0. 3.12.8 is from 2017.

OK, thank u very much!
