### ISSUE TITLE
 the final optimization time exceeds the max cpu time

### ISSUE THREAD

**Issue by yueshinian** [coin-or/Ipopt#811]
Hello, I set the max_cpu_time to 0.1s, but the final optimization time, from TotalCpuTime(), will exceed 0.1s, for example 0.4s. May I ask why this is happening, and is there any way to avoid this situation?
Any help would be greatly appreciated.

**Comment by johannahaffner** [comment]
Hi, not an expert on this (or the IPOPT implementation), but I believe this is expected for multithreaded operations?

**Comment by svigerske** [comment]
Ipopt checks the time limit only once per iteration, so it cannot stop precisely when the allotted time has run out.

Much time per iteration is spent within the linear solver. These linear solvers usually do not have an option to set a time limit, or a way to be interrupted from Ipopt while running. So I don't think that there is something that can be done to really improve the situation.

**Comment by yueshinian** [comment]
> Hi, not an expert on this (or the IPOPT implementation), but I believe this is expected for multithreaded operations?

Thanks. You 're right. We use different configuration parameters each time to optimize and then select the optimal one. Have you also encountered this situation? Is there any solution? Thank you very much.

**Comment by yueshinian** [comment]
> Ipopt checks the time limit only once per iteration, so it cannot stop precisely when the allotted time has run out.
> 
> Much time per iteration is spent within the linear solver. These linear solvers usually do not have an option to set a time limit, or a way to be interrupted from Ipopt while running. So I don't think that there is something that can be done to really improve the situation.

Thank you for this.

**Comment by johannahaffner** [comment]
> Have you also encountered this situation? Is there any solution? Thank you very much.

The solution is usually just taking this into account :) Similar to getting "400 % CPU usage" if you force certain processes to go multi-core, while htop reports single-core.

But I think you should go with @svigerske's answer - the issue lies somewhere else here, namely with IPOPTs ability, or lack thereof, to interrupt processes in its dependencies.

**Comment by yueshinian** [comment]
> > Have you also encountered this situation? Is there any solution? Thank you very much.
> 
> The solution is usually just taking this into account :) Similar to getting "400 % CPU usage" if you force certain processes to go multi-core, while htop reports single-core.
> 
> But I think you should go with @svigerske's answer - the issue lies somewhere else here, namely with IPOPTs ability, or lack thereof, to interrupt processes in its dependencies.

OK. Thanks a lot.
